#!/usr/bin/env python3
"""Reverse-engineer a codebase's structure: components, dependencies, and gap signals.

Drawing an architecture by reading every file does not scale: the context window runs out
first. This script does the mechanical pass. It builds the import graph and groups files into
components. It measures coupling and stability, and finds entry points, external systems, and
deployment config. Then it emits gap *signals* against the standards in references/.

Every signal is a candidate, not a verdict. The agent must open the evidence and confirm it
before it reaches the report. Gap IDs match references/GAP_CATALOGUE.md.

Usage:
    scan-architecture.py [root] [--depth N] [--include-tests] [--json]
                         [--mermaid components|containers|all] [--max-nodes N]
    scan-architecture.py --self-test

Exits 0 for any scan result — this reports, it never gates.
--self-test exits non-zero on failure so it can be wired into a test suite.
"""

import argparse
import json
import math
import os
import re
import subprocess
import sys
from collections import defaultdict

MAX_FILE_BYTES = 1_500_000
DEFAULT_MAX_NODES = 30
GOD_FILE_LOC = 800
SPRAWL_COMPONENTS = 3           # an SDK imported from this many components has no port

SKIP_DIRS = {
    ".git", ".hg", ".svn", "node_modules", "vendor", "bower_components", "dist", "build",
    "out", "target", ".next", ".nuxt", ".svelte-kit", ".turbo", ".cache", "__pycache__",
    ".venv", "venv", "env", ".tox", ".mypy_cache", ".pytest_cache", ".ruff_cache",
    "coverage", "htmlcov", "Pods", "DerivedData", ".gradle", ".idea", ".vscode",
    "__generated__", "generated", ".terraform", "storybook-static", ".output", ".vercel",
    ".serverless", "obj", "storage", "tmp", "log", "logs",
    # Served or vendored assets: third-party builds, not the system's own code.
    "public", "static", "wwwroot", "third_party", "third-party", "external", "externals",
    "vendors", "assets/vendor",
}
VENDORED_HEAD_RE = re.compile(r"/\*!|@license\b|\(c\)\s*\d{4}|@preserve\b|"
                              r"^// Generated by |@generated\b|Code generated .{0,40}DO NOT EDIT",
                              re.M)
SKIP_FILE_RE = re.compile(r"(\.min\.(js|css)$|\.bundle\.|\.d\.ts$|\.pb\.go$|_pb2\.py$|"
                          r"\.generated\.|\.map$)")

LANG_BY_EXT = {
    ".js": "js", ".jsx": "js", ".mjs": "js", ".cjs": "js", ".ts": "js", ".tsx": "js",
    ".mts": "js", ".cts": "js", ".vue": "js", ".svelte": "js", ".astro": "js",
    ".py": "py", ".go": "go", ".php": "php", ".java": "jvm", ".kt": "jvm", ".kts": "jvm",
    ".scala": "jvm", ".cs": "cs", ".rb": "rb", ".rs": "rs", ".swift": "swift", ".dart": "dart",
    ".ex": "ex", ".exs": "ex",
}
LANG_NAME = {
    "js": "JavaScript/TypeScript", "py": "Python", "go": "Go", "php": "PHP",
    "jvm": "Java/Kotlin/Scala", "cs": "C#", "rb": "Ruby", "rs": "Rust", "swift": "Swift",
    "dart": "Dart", "ex": "Elixir",
}
JS_EXTS = [".ts", ".tsx", ".js", ".jsx", ".mjs", ".cjs", ".mts", ".cts", ".vue", ".svelte",
           ".astro", ".json"]

TEST_RE = re.compile(r"(^|/)(tests?|__tests__|spec|specs|e2e|cypress|playwright|fixtures|"
                     r"testdata|__mocks__|mocks?)(/|$)|(\.|_)(test|spec|e2e)\.[a-z]+$|"
                     r"(^|/)test_[^/]+\.py$|_test\.(go|py)$|Tests?\.(cs|java|kt|php)$")
SOURCE_ROOTS = ("src", "lib", "source", "sources")
GROUP_ROOTS = ("packages", "apps", "services", "modules", "libs", "cmd", "crates",
               "plugins", "projects")

# ---------------------------------------------------------------------------
# Files
# ---------------------------------------------------------------------------


def list_files(root):
    try:
        out = subprocess.run(["git", "-C", root, "ls-files", "-z", "--cached", "--others",
                              "--exclude-standard"], capture_output=True, text=True, timeout=60)
        if out.returncode == 0:
            return [f for f in out.stdout.split("\0") if f]
    except (OSError, subprocess.SubprocessError):
        pass
    files = []
    for dirpath, dirnames, filenames in os.walk(root):
        dirnames[:] = [d for d in dirnames if d not in SKIP_DIRS and not d.startswith(".")
                       or d in (".github",)]
        for f in filenames:
            files.append(os.path.relpath(os.path.join(dirpath, f), root))
    return files


def tracked_files(root):
    try:
        out = subprocess.run(["git", "-C", root, "ls-files", "-z"], capture_output=True,
                             text=True, timeout=60)
        if out.returncode == 0:
            return {f for f in out.stdout.split("\0") if f}
    except (OSError, subprocess.SubprocessError):
        pass
    return None


def skipped(rel):
    parts = rel.split("/")
    if any(p in SKIP_DIRS for p in parts[:-1]):
        return True
    return bool(SKIP_FILE_RE.search(parts[-1]))


def read(root, rel, limit=MAX_FILE_BYTES):
    path = os.path.join(root, rel)
    try:
        if os.path.getsize(path) > limit:
            return None
        with open(path, "r", encoding="utf-8", errors="replace") as fh:
            return fh.read()
    except OSError:
        return None


def is_vendored(text):
    """A licence banner, generator marker, or minified line means someone else's code."""
    head = text[:600]
    if VENDORED_HEAD_RE.search(head):
        return True
    return any(len(ln) > 1000 for ln in text.split("\n", 50)[:50])


def loose_json(text):
    """Parse JSON that may carry comments and trailing commas (tsconfig, jsconfig)."""
    if text is None:
        return None
    out, i, n, in_str = [], 0, len(text), False
    while i < n:
        c = text[i]
        if in_str:
            out.append(c)
            if c == "\\" and i + 1 < n:
                out.append(text[i + 1])
                i += 2
                continue
            if c == '"':
                in_str = False
            i += 1
            continue
        if c == '"':
            in_str = True
            out.append(c)
        elif text.startswith("//", i):
            j = text.find("\n", i)
            i = n if j == -1 else j
            continue
        elif text.startswith("/*", i):
            j = text.find("*/", i + 2)
            i = n if j == -1 else j + 2
            continue
        else:
            out.append(c)
        i += 1
    cleaned = re.sub(r",(\s*[}\]])", r"\1", "".join(out))
    try:
        return json.loads(cleaned)
    except ValueError:
        return None


# ---------------------------------------------------------------------------
# Import extraction and resolution, per language
# ---------------------------------------------------------------------------

JS_IMPORT_RE = re.compile(
    r"""(?:^|[;\s])(?:import|export)\s+(?:type\s+)?(?:[\w*{}\s,$]+?\s+from\s+)?['"]([^'"]+)['"]"""
    r"""|\brequire\(\s*['"]([^'"]+)['"]\s*\)|\bimport\(\s*['"]([^'"]+)['"]\s*\)""", re.M)
PY_IMPORT_RE = re.compile(r"^[ \t]*(?:from[ \t]+(\.*[\w.]*)[ \t]+import[ \t]+"
                          r"(\([^)]*\)|[\w*, \t]+)|import[ \t]+([\w., \t]+))", re.M)
GO_IMPORT_BLOCK_RE = re.compile(r"^import\s*\(([^)]*)\)", re.M | re.S)
GO_IMPORT_ONE_RE = re.compile(r'^import\s+(?:\w+\s+)?"([^"]+)"', re.M)
GO_STR_RE = re.compile(r'"([^"]+)"')
PHP_NS_RE = re.compile(r"^\s*namespace\s+([\w\\]+)\s*[;{]", re.M)
PHP_USE_RE = re.compile(r"^\s*use\s+(?:function\s+|const\s+)?([\w\\]+)(?:\\\{([^}]*)\})?",
                        re.M)
JVM_PKG_RE = re.compile(r"^\s*package\s+([\w.]+)", re.M)
JVM_IMPORT_RE = re.compile(r"^\s*import\s+(?:static\s+)?([\w.]+)(\.\*)?", re.M)
CS_NS_RE = re.compile(r"^\s*namespace\s+([\w.]+)", re.M)
CS_USING_RE = re.compile(r"^\s*(?:global\s+)?using\s+(?:static\s+)?([\w.]+)\s*;", re.M)
RB_REQ_RE = re.compile(r"^\s*require(_relative)?\s*\(?\s*['\"]([^'\"]+)['\"]", re.M)
RS_MOD_RE = re.compile(r"^\s*(?:pub(?:\([^)]*\))?\s+)?mod\s+(\w+)\s*;", re.M)
RS_USE_RE = re.compile(r"^\s*(?:pub(?:\([^)]*\))?\s+)?use\s+([\w:]+)", re.M)
DART_IMPORT_RE = re.compile(r"^\s*import\s+['\"]([^'\"]+)['\"]", re.M)
SWIFT_IMPORT_RE = re.compile(r"^\s*import\s+(\w+)", re.M)

# Martin's abstractness needs abstractions that callers depend on. In JS/TS most
# interfaces describe data shapes, so A would read near 1.0 and mean nothing; it is omitted.
ABSTRACT_RE = {
    "py": re.compile(r"^\s*class\s+\w+\s*\([^)]*\b(ABC|Protocol|ABCMeta)\b", re.M),
    "go": re.compile(r"^\s*type\s+\w+\s+interface\b", re.M),
    "php": re.compile(r"^\s*(?:interface\s+\w|abstract\s+class\s+\w|trait\s+\w)", re.M),
    "jvm": re.compile(r"^\s*(?:public\s+|internal\s+|private\s+|sealed\s+)*"
                      r"(?:interface\s+\w|abstract\s+class\s+\w|trait\s+\w)", re.M),
    "cs": re.compile(r"^\s*(?:public\s+|internal\s+)*(?:interface\s+\w|abstract\s+class\s+\w)",
                     re.M),
    "rs": re.compile(r"^\s*(?:pub(?:\([^)]*\))?\s+)?trait\s+\w", re.M),
    "swift": re.compile(r"^\s*(?:public\s+|internal\s+)?protocol\s+\w", re.M),
}
TYPE_RE = {
    "py": re.compile(r"^\s*class\s+\w", re.M),
    "go": re.compile(r"^\s*type\s+\w+\s+(?:struct|interface)\b", re.M),
    "php": re.compile(r"^\s*(?:final\s+|abstract\s+)?(?:class|interface|trait|enum)\s+\w", re.M),
    "jvm": re.compile(r"^\s*(?:public\s+|internal\s+|private\s+|sealed\s+|data\s+|open\s+|"
                      r"final\s+|abstract\s+)*(?:class|interface|trait|object|enum|record)\s+\w",
                      re.M),
    "cs": re.compile(r"^\s*(?:public\s+|internal\s+|sealed\s+|static\s+|abstract\s+|partial\s+)*"
                     r"(?:class|interface|struct|record|enum)\s+\w", re.M),
    "rs": re.compile(r"^\s*(?:pub(?:\([^)]*\))?\s+)?(?:struct|enum|trait)\s+\w", re.M),
    "swift": re.compile(r"^\s*(?:public\s+|internal\s+|final\s+)*(?:class|struct|protocol|enum)"
                        r"\s+\w", re.M),
}

try:
    PY_STDLIB = set(sys.stdlib_module_names)
except AttributeError:          # Python < 3.10
    PY_STDLIB = {"os", "sys", "re", "json", "typing", "collections", "itertools", "functools",
                 "datetime", "time", "math", "logging", "subprocess", "pathlib", "abc",
                 "dataclasses", "enum", "io", "unittest", "asyncio", "random", "string"}


def strip_c_comments(text):
    text = re.sub(r"/\*.*?\*/", lambda m: "\n" * m.group(0).count("\n"), text, flags=re.S)
    return re.sub(r"(?m)^\s*//.*$", "", text)


def strip_hash_comments(text):
    return re.sub(r"(?m)^\s*#.*$", "", text)


class Resolver:
    """Maps an import specifier to a file in the repo, or to an external package name."""

    def __init__(self, root, files):
        self.root = root
        self.files = set(files)
        self.by_dir = defaultdict(list)
        for f in files:
            self.by_dir[os.path.dirname(f)].append(f)
        self._js_config()
        self._py_index()
        self._go_module()
        self._php_psr4()
        self._jvm_index()
        self._cs_index()

    # -- JavaScript / TypeScript ------------------------------------------------

    def _js_config(self):
        self.js_paths = []          # (prefix, [targets]) from tsconfig/jsconfig paths
        self.js_base = []
        self.workspaces = {}        # package name → dir
        for cfg in sorted(f for f in self.files
                          if os.path.basename(f) in ("tsconfig.json", "jsconfig.json")):
            data = loose_json(read(self.root, cfg)) or {}
            opts = data.get("compilerOptions") or {}
            base = os.path.normpath(os.path.join(os.path.dirname(cfg), opts.get("baseUrl", ".")))
            if opts.get("baseUrl"):
                self.js_base.append(base)
            for alias, targets in (opts.get("paths") or {}).items():
                prefix = alias.rstrip("*")
                tg = [os.path.normpath(os.path.join(base, t.rstrip("*"))) for t in targets]
                self.js_paths.append((prefix, tg, alias.endswith("*")))
        self.js_paths.sort(key=lambda p: -len(p[0]))
        for pj in (f for f in self.files if os.path.basename(f) == "package.json"):
            if pj == "package.json":
                continue
            data = loose_json(read(self.root, pj)) or {}
            if data.get("name"):
                self.workspaces[data["name"]] = os.path.dirname(pj)

    def _js_file(self, base):
        base = os.path.normpath(base)
        if base in self.files and not base.endswith(".json"):
            return base
        for ext in JS_EXTS:
            if base + ext in self.files:
                return base + ext
        stem, ext = os.path.splitext(base)
        if ext in (".js", ".mjs", ".cjs", ".jsx"):          # TS ESM imports name the .js output
            for alt in (".ts", ".tsx", ".mts", ".cts"):
                if stem + alt in self.files:
                    return stem + alt
        for ext in JS_EXTS:
            if os.path.join(base, "index" + ext) in self.files:
                return os.path.join(base, "index" + ext)
        return None

    def resolve_js(self, src, spec):
        spec = spec.split("?")[0]
        if spec.startswith("."):
            hit = self._js_file(os.path.join(os.path.dirname(src), spec))
            return ("file", hit) if hit else (None, None)
        for prefix, targets, star in self.js_paths:
            if (star and spec.startswith(prefix)) or spec == prefix:
                rest = spec[len(prefix):] if star else ""
                for t in targets:
                    hit = self._js_file(os.path.join(t, rest))
                    if hit:
                        return "file", hit
        for name, d in self.workspaces.items():
            if spec == name or spec.startswith(name + "/"):
                rest = spec[len(name):].lstrip("/")
                hit = self._js_file(os.path.join(d, rest or "index"))
                if not hit:
                    for guess in ("src/index", "index", "src/main", "lib/index"):
                        hit = self._js_file(os.path.join(d, guess))
                        if hit:
                            break
                return ("file", hit) if hit else ("pkg", name)
        for base in self.js_base:
            hit = self._js_file(os.path.join(base, spec))
            if hit:
                return "file", hit
        if spec.startswith(("node:", "bun:", "deno:")) or spec in NODE_BUILTINS:
            return None, None
        parts = spec.split("/")
        name = "/".join(parts[:2]) if spec.startswith("@") else parts[0]
        return "ext", name

    # -- Python ------------------------------------------------------------------

    def _py_index(self):
        self.py_mods = {}
        roots = {""} | {r for r in ("src", "lib", "app") if any(
            f.startswith(r + "/") for f in self.files)}
        for f in self.files:
            if not f.endswith(".py"):
                continue
            for r in roots:
                if r and not f.startswith(r + "/"):
                    continue
                rel = f[len(r) + 1:] if r else f
                mod = rel[:-3].replace("/", ".")
                if mod.endswith(".__init__"):
                    mod = mod[:-9]
                self.py_mods.setdefault(mod, f)

    def resolve_py(self, src, module, names):
        out = []
        if module.startswith("."):
            dots = len(module) - len(module.lstrip("."))
            pkg = os.path.dirname(src).split("/") if os.path.dirname(src) else []
            pkg = pkg[:len(pkg) - (dots - 1)] if dots > 1 else pkg
            base = ".".join(pkg + ([module.lstrip(".")] if module.lstrip(".") else []))
            cands = [base + "." + n for n in names] + [base]
            for c in cands:
                for key in (c, c.split(".", 1)[-1] if "." in c else c):
                    if key in self.py_mods:
                        out.append(("file", self.py_mods[key]))
                        break
            return out[:1] if out else []
        for c in [module + "." + n for n in names] + [module]:
            if c in self.py_mods:
                return [("file", self.py_mods[c])]
        top = module.split(".")[0]
        if top and top not in PY_STDLIB and top != "__future__":
            return [("ext", top)]
        return []

    # -- Go ----------------------------------------------------------------------

    def _go_module(self):
        self.go_mods = []
        for gm in (f for f in self.files if os.path.basename(f) == "go.mod"):
            m = re.search(r"^module\s+(\S+)", read(self.root, gm) or "", re.M)
            if m:
                self.go_mods.append((m.group(1), os.path.dirname(gm)))
        self.go_mods.sort(key=lambda x: -len(x[0]))

    def resolve_go(self, spec):
        for mod, d in self.go_mods:
            if spec == mod or spec.startswith(mod + "/"):
                pkg_dir = os.path.normpath(os.path.join(d, spec[len(mod):].lstrip("/")))
                files = [f for f in self.by_dir.get(pkg_dir if pkg_dir != "." else "", [])
                         if f.endswith(".go") and not f.endswith("_test.go")]
                return ("file", files[0]) if files else (None, None)
        first = spec.split("/")[0]
        if "." not in first:
            return None, None       # standard library
        return "ext", "/".join(spec.split("/")[:3])

    # -- PHP ---------------------------------------------------------------------

    def _php_psr4(self):
        self.psr4 = []
        for cj in (f for f in self.files if os.path.basename(f) == "composer.json"):
            data = loose_json(read(self.root, cj)) or {}
            for sect in ("autoload", "autoload-dev"):
                for ns, dirs in ((data.get(sect) or {}).get("psr-4") or {}).items():
                    for d in (dirs if isinstance(dirs, list) else [dirs]):
                        self.psr4.append((ns, os.path.normpath(os.path.join(
                            os.path.dirname(cj), d))))
        self.psr4.sort(key=lambda x: -len(x[0]))

    def resolve_php(self, fqcn):
        fqcn = fqcn.lstrip("\\")
        for ns, d in self.psr4:
            if fqcn.startswith(ns) or fqcn + "\\" == ns:
                rel = fqcn[len(ns):].replace("\\", "/")
                cand = os.path.normpath(os.path.join(d, rel + ".php"))
                if cand in self.files:
                    return "file", cand
                pkg_dir = os.path.normpath(os.path.join(d, rel))
                files = [f for f in self.by_dir.get(pkg_dir, []) if f.endswith(".php")]
                return ("file", files[0]) if files else (None, None)
        parts = fqcn.split("\\")
        if len(parts) >= 2:
            return "ext", "\\".join(parts[:2])
        return None, None

    # -- Java / Kotlin / Scala ------------------------------------------------------

    def _jvm_index(self):
        self.jvm_classes, self.jvm_pkgs = {}, defaultdict(list)
        for f in self.files:
            if os.path.splitext(f)[1] not in (".java", ".kt", ".kts", ".scala"):
                continue
            m = JVM_PKG_RE.search((read(self.root, f, 200_000) or "")[:4000])
            if m:
                cls = os.path.splitext(os.path.basename(f))[0]
                self.jvm_classes[m.group(1) + "." + cls] = f
                self.jvm_pkgs[m.group(1)].append(f)

    def resolve_jvm(self, name, star):
        if star and name in self.jvm_pkgs:
            return "file", self.jvm_pkgs[name][0]
        probe = name
        while probe:
            if probe in self.jvm_classes:
                return "file", self.jvm_classes[probe]
            probe = probe.rpartition(".")[0]
        if name.split(".")[0] in ("java", "javax", "kotlin", "scala", "jdk", "sun"):
            return None, None
        return "ext", ".".join(name.split(".")[:3])

    # -- C# ------------------------------------------------------------------------

    def _cs_index(self):
        self.cs_ns = defaultdict(list)
        for f in self.files:
            if f.endswith(".cs"):
                for m in CS_NS_RE.finditer((read(self.root, f, 400_000) or "")[:8000]):
                    self.cs_ns[m.group(1)].append(f)

    def resolve_cs(self, ns):
        if ns in self.cs_ns:
            return "file", self.cs_ns[ns][0]
        if ns.split(".")[0] in ("System", "Microsoft"):
            return None, None
        return "ext", ".".join(ns.split(".")[:2])


NODE_BUILTINS = {
    "assert", "async_hooks", "buffer", "child_process", "cluster", "console", "constants",
    "crypto", "dgram", "dns", "domain", "events", "fs", "fs/promises", "http", "http2",
    "https", "inspector", "module", "net", "os", "path", "perf_hooks", "process",
    "punycode", "querystring", "readline", "repl", "stream", "string_decoder", "sys",
    "timers", "tls", "trace_events", "tty", "url", "util", "v8", "vm", "wasi",
    "worker_threads", "zlib", "path/posix", "stream/promises", "util/types",
}


def imports_of(resolver, rel, text, lang):
    """Yield (kind, target) — kind 'file' (repo path) or 'ext' (package name)."""
    out = []
    if lang == "js":
        body = strip_c_comments(text)
        for m in JS_IMPORT_RE.finditer(body):
            spec = m.group(1) or m.group(2) or m.group(3)
            kind, tgt = resolver.resolve_js(rel, spec)
            if kind:
                out.append((kind, tgt))
    elif lang == "py":
        body = strip_hash_comments(text)
        for m in PY_IMPORT_RE.finditer(body):
            if m.group(1) is not None:
                names = [n.strip().split(" as ")[0] for n in
                         m.group(2).replace("(", "").replace(")", "").split(",") if n.strip()]
                out += resolver.resolve_py(rel, m.group(1), names)
            else:
                for mod in m.group(3).split(","):
                    mod = mod.strip().split(" as ")[0].strip()
                    if mod:
                        out += resolver.resolve_py(rel, mod, [])
    elif lang == "go":
        body = strip_c_comments(text)
        specs = GO_IMPORT_ONE_RE.findall(body)
        for blk in GO_IMPORT_BLOCK_RE.findall(body):
            specs += GO_STR_RE.findall(blk)
        for spec in specs:
            kind, tgt = resolver.resolve_go(spec)
            if kind:
                out.append((kind, tgt))
    elif lang == "php":
        body = strip_c_comments(text)
        for m in PHP_USE_RE.finditer(body):
            base, group = m.group(1), m.group(2)
            names = ([base.rstrip("\\") + "\\" + g.strip().split(" as ")[0]
                      for g in group.split(",") if g.strip()] if group else [base])
            for n in names:
                kind, tgt = resolver.resolve_php(n)
                if kind:
                    out.append((kind, tgt))
    elif lang == "jvm":
        for m in JVM_IMPORT_RE.finditer(strip_c_comments(text)):
            kind, tgt = resolver.resolve_jvm(m.group(1), bool(m.group(2)))
            if kind:
                out.append((kind, tgt))
    elif lang == "cs":
        for m in CS_USING_RE.finditer(strip_c_comments(text)):
            kind, tgt = resolver.resolve_cs(m.group(1))
            if kind:
                out.append((kind, tgt))
    elif lang == "rb":
        for m in RB_REQ_RE.finditer(strip_hash_comments(text)):
            spec = m.group(2)
            base = (os.path.join(os.path.dirname(rel), spec) if m.group(1)
                    else os.path.join("lib", spec))
            base = os.path.normpath(base)
            cand = base if base.endswith(".rb") else base + ".rb"
            if cand in resolver.files:
                out.append(("file", cand))
            elif not m.group(1):
                out.append(("ext", spec.split("/")[0]))
    elif lang == "rs":
        body = strip_c_comments(text)
        here = os.path.dirname(rel)
        for m in RS_MOD_RE.finditer(body):
            for cand in (os.path.join(here, m.group(1) + ".rs"),
                         os.path.join(here, m.group(1), "mod.rs")):
                if cand in resolver.files:
                    out.append(("file", cand))
                    break
        crate_src = rel.split("src/")[0] + "src" if "src/" in rel else here
        for m in RS_USE_RE.finditer(body):
            path = m.group(1).split("::")
            if path[0] == "crate" and len(path) > 1:
                for i in range(len(path) - 1, 0, -1):
                    stem = os.path.join(crate_src, *path[1:i + 1])
                    hit = next((c for c in (stem + ".rs", os.path.join(stem, "mod.rs"))
                                if c in resolver.files), None)
                    if hit:
                        out.append(("file", hit))
                        break
            elif path[0] not in ("self", "super", "std", "core", "alloc", "crate"):
                out.append(("ext", path[0]))
    elif lang == "dart":
        for m in DART_IMPORT_RE.finditer(text):
            spec = m.group(1)
            if spec.startswith("package:"):
                out.append(("ext", spec[8:].split("/")[0]))
            elif not spec.startswith("dart:"):
                cand = os.path.normpath(os.path.join(os.path.dirname(rel), spec))
                if cand in resolver.files:
                    out.append(("file", cand))
    elif lang == "swift":
        for m in SWIFT_IMPORT_RE.finditer(text):
            if m.group(1) not in ("Foundation", "UIKit", "SwiftUI", "Combine", "XCTest"):
                out.append(("ext", m.group(1)))
    return out


# ---------------------------------------------------------------------------
# Components
# ---------------------------------------------------------------------------


def scoped(rel, scope):
    return rel[len(scope) + 1:] if scope and rel.startswith(scope + "/") else rel


def component_key(rel, depth, split_dirs=None):
    """Group a file into a component: its first `depth` directory segments.

    A monorepo group (packages/foo) counts as one segment and a source root (src/) is free.
    A loose file above the component level, such as `src/index.ts` beside `src/features/`,
    becomes its own node. That way a composition root and a types module never merge into one
    component and fake a cycle.
    """
    parts = rel.split("/")[:-1]
    if not parts:
        return "(root)"
    key, counted, i = [], 0, 0
    while i < len(parts) and counted < depth:
        seg = parts[i]
        if seg in GROUP_ROOTS and i + 1 < len(parts):
            key.append(seg + "/" + parts[i + 1])
            i += 2
        else:
            key.append(seg)
            i += 1
        if seg not in SOURCE_ROOTS:
            counted += 1
    if counted < depth and (split_dirs is None or os.path.dirname(rel) in split_dirs):
        key.append(os.path.splitext(rel.split("/")[-1])[0])
    return "/".join(key)


def mixed_dirs(files):
    """Directories that hold source files *and* subdirectories with source files."""
    dirs = {os.path.dirname(f) for f in files}
    parents = {os.path.dirname(d) for d in dirs if d}
    return dirs & parents


def choose_depth(sources):
    best = 1
    split = mixed_dirs(sources)
    for d in range(1, 6):
        n = len({component_key(f, d, split) for f in sources})
        if n > 40:
            break
        best = d
        if n >= 8:
            break
    return best


LAYERS = [
    ("presentation", r"(^|/)(ui|components?|pages|views?|screens|controllers?|routes?|"
                     r"handlers?|http|web|api|cli|cmd|graphql|resolvers|endpoints|"
                     r"presentation|interfaces|app/Http|widgets|layouts)(/|$)"),
    ("application", r"(^|/)(services?|use_?cases?|usecases|application|actions?|jobs|"
                    r"commands?|queries|workflows?|interactors?|features?)(/|$)"),
    ("domain", r"(^|/)(domain|entities|entity|models?|core|business|aggregates?|"
               r"value_?objects?)(/|$)"),
    ("infrastructure", r"(^|/)(infra|infrastructure|db|database|repositor(y|ies)|repos?|"
                       r"adapters?|persistence|gateways?|clients?|integrations?|"
                       r"migrations?|storage|providers?|drivers?|dal|orm|prisma)(/|$)"),
    ("shared", r"(^|/)(utils?|lib|libs|common|shared|helpers?|config|types?|constants?|"
               r"support|kernel)(/|$)"),
]
LAYER_RES = [(n, re.compile(p, re.I)) for n, p in LAYERS]
# layer → layers it must not import (Clean Architecture dependency rule, layered style).
FORBIDDEN = {
    "domain": {"presentation", "application", "infrastructure"},
    "application": {"presentation"},
    "infrastructure": {"presentation"},
    "shared": {"presentation", "application", "domain", "infrastructure"},
}


def layer_of(component):
    for name, rx in LAYER_RES:
        if rx.search(component):
            return name
    return None


# ---------------------------------------------------------------------------
# Graph algorithms
# ---------------------------------------------------------------------------


def tarjan(nodes, edges):
    """Strongly connected components with more than one node (the cycles)."""
    index, low, on, stack, out = {}, {}, set(), [], []
    counter = [0]
    sys.setrecursionlimit(max(10000, len(nodes) * 4))

    def visit(v):
        index[v] = low[v] = counter[0]
        counter[0] += 1
        stack.append(v)
        on.add(v)
        for w in edges.get(v, ()):
            if w not in index:
                visit(w)
                low[v] = min(low[v], low[w])
            elif w in on:
                low[v] = min(low[v], index[w])
        if low[v] == index[v]:
            comp = []
            while True:
                w = stack.pop()
                on.discard(w)
                comp.append(w)
                if w == v:
                    break
            if len(comp) > 1:
                out.append(sorted(comp))

    for v in sorted(nodes):
        if v not in index:
            visit(v)
    return sorted(out, key=lambda c: -len(c))


def cycle_path(scc, edges):
    """One concrete loop through an SCC, for the report's evidence line."""
    members = set(scc)
    start = scc[0]
    path, seen, node = [start], {start}, start
    while True:
        nxt = next((w for w in sorted(edges.get(node, ())) if w in members and w == start
                    and len(path) > 1), None)
        if nxt:
            return path + [start]
        nxt = next((w for w in sorted(edges.get(node, ())) if w in members and w not in seen),
                   None)
        if not nxt:
            return path + [start]
        path.append(nxt)
        seen.add(nxt)
        node = nxt


# ---------------------------------------------------------------------------
# Stack, entry points, external systems, infrastructure
# ---------------------------------------------------------------------------

EXTERNAL_CATALOGUE = [
    # (category, display name, package regex)
    ("database", "PostgreSQL", r"^(pg|postgres|pg-promise|@neondatabase/.*|psycopg2?(-binary)?|"
                               r"psycopg|asyncpg|github.com/jackc/pgx|github.com/lib/pq|npgsql)$"),
    ("database", "MySQL", r"^(mysql2?|mysqlclient|pymysql|github.com/go-sql-driver/mysql|"
                          r"@planetscale/.*)$"),
    ("database", "SQLite", r"^(sqlite3|better-sqlite3|@libsql/.*|libsql)$"),
    ("database", "MongoDB", r"^(mongodb|mongoose|pymongo|motor|go.mongodb.org/mongo-driver|"
                            r"mongoid)$"),
    ("database", "ORM (Prisma)", r"^(@prisma/client|prisma)$"),
    ("database", "ORM", r"^(typeorm|sequelize|drizzle-orm|knex|@mikro-orm/.*|objection|"
                        r"sqlalchemy|peewee|tortoise-orm|django|gorm.io/gorm|entgo.io/ent|"
                        r"illuminate/database|doctrine/orm|diesel|sqlx|sea-orm|"
                        r"microsoft.entityframeworkcore)$"),
    ("database", "DynamoDB", r"^(@aws-sdk/client-dynamodb|@aws-sdk/lib-dynamodb|dynamoose)$"),
    ("database", "Firestore/Firebase", r"^(firebase|firebase-admin|@google-cloud/firestore)$"),
    ("database", "Supabase", r"^(@supabase/supabase-js|supabase)$"),
    ("cache", "Redis", r"^(redis|ioredis|@upstash/redis|predis/predis|github.com/redis/go-redis|"
                       r"github.com/go-redis/redis|redis-py|aioredis)$"),
    ("cache", "Memcached", r"^(memcached|pymemcache|memjs)$"),
    ("queue", "Kafka", r"^(kafkajs|confluent-kafka|kafka-python|github.com/segmentio/kafka-go|"
                       r"@confluentinc/.*)$"),
    ("queue", "RabbitMQ", r"^(amqplib|amqp-connection-manager|pika|aio-pika|"
                          r"github.com/rabbitmq/amqp091-go|php-amqplib/php-amqplib)$"),
    ("queue", "Job queue", r"^(bullmq|bull|bee-queue|agenda|celery|rq|dramatiq|sidekiq|resque|"
                           r"laravel/horizon|@trigger.dev/.*|inngest|graphile-worker|pg-boss)$"),
    ("queue", "AWS SQS/SNS", r"^(@aws-sdk/client-sqs|@aws-sdk/client-sns|sqs-consumer)$"),
    ("queue", "Pub/Sub", r"^(@google-cloud/pubsub|nats|@nats-io/.*|google-cloud-pubsub)$"),
    ("search", "Search engine", r"^(@elastic/elasticsearch|elasticsearch|algoliasearch|"
                                r"meilisearch|typesense|@opensearch-project/.*|opensearch-py)$"),
    ("storage", "Object storage", r"^(@aws-sdk/client-s3|aws-sdk|boto3|@google-cloud/storage|"
                                  r"@azure/storage-blob|cloudinary|uploadthing|"
                                  r"league/flysystem.*|@vercel/blob)$"),
    ("payments", "Payments", r"^(stripe|@stripe/.*|braintree|@paypal/.*|paypal-rest-sdk|"
                             r"@paddle/.*|@lemonsqueezy/.*|@adyen/.*|laravel/cashier)$"),
    ("email", "Email/SMS", r"^(nodemailer|@sendgrid/.*|resend|postmark|mailgun.js|"
                           r"mailgun|twilio|@aws-sdk/client-ses|symfony/mailer|@react-email/.*|"
                           r"sendgrid)$"),
    ("auth", "Identity provider", r"^(next-auth|@auth/.*|passport|passport-.*|@clerk/.*|"
                                  r"auth0|@auth0/.*|better-auth|lucia|@kinde-oss/.*|"
                                  r"laravel/sanctum|laravel/passport|devise|django-allauth|"
                                  r"python-keycloak|@okta/.*|firebase-auth)$"),
    ("observability", "Error tracking", r"^(@sentry/.*|sentry-sdk|sentry/sentry-laravel|"
                                        r"sentry-ruby|@bugsnag/.*|rollbar|@honeybadger-io/.*)$"),
    ("observability", "Tracing/metrics", r"^(@opentelemetry/.*|opentelemetry-.*|"
                                         r"go.opentelemetry.io/.*|dd-trace|ddtrace|newrelic|"
                                         r"@newrelic/.*|prom-client|prometheus[-_]client|"
                                         r"@vercel/otel|elastic-apm-node)$"),
    ("observability", "Structured logging", r"^(pino|winston|bunyan|structlog|loguru|"
                                            r"go.uber.org/zap|github.com/rs/zerolog|"
                                            r"monolog/monolog|serilog)$"),
    ("analytics", "Product analytics", r"^(posthog-js|posthog-node|posthog|mixpanel|"
                                       r"@segment/.*|@amplitude/.*|@vercel/analytics)$"),
    ("ai", "LLM provider", r"^(openai|@anthropic-ai/sdk|anthropic|@google/generative-ai|"
                           r"@google/genai|google-generativeai|langchain|@langchain/.*|"
                           r"ai|@ai-sdk/.*|cohere-ai|cohere|replicate|@mistralai/.*|"
                           r"llamaindex|llama-index)$"),
    ("cms", "Headless CMS", r"^(contentful|@sanity/client|next-sanity|@strapi/.*|"
                            r"@prismicio/.*|@storyblok/.*|@payloadcms/.*|payload)$"),
    ("realtime", "Realtime", r"^(socket.io|socket.io-client|pusher|pusher-js|ably|ws|"
                             r"@liveblocks/.*|channels)$"),
    ("flags", "Feature flags", r"^(launchdarkly-.*|@launchdarkly/.*|@vercel/flags|flags|"
                               r"unleash-client|@growthbook/.*|flagsmith)$"),
    ("http", "Outbound HTTP", r"^(axios|got|node-fetch|undici|ky|requests|httpx|aiohttp|"
                              r"guzzlehttp/guzzle|github.com/go-resty/resty.*|faraday|"
                              r"httparty|reqwest|okhttp.*|retrofit.*)$"),
    ("api", "GraphQL", r"^(graphql|@apollo/.*|apollo-server.*|graphql-yoga|urql|"
                       r"@urql/.*|strawberry-graphql|graphene|gqlgen|lighthouse)$"),
    ("api", "gRPC/tRPC", r"^(@grpc/grpc-js|grpcio|google.golang.org/grpc|@trpc/.*)$"),
]
EXT_RES = [(c, n, re.compile(p, re.I)) for c, n, p in EXTERNAL_CATALOGUE]

FRAMEWORKS = [
    ("Next.js", r"^next$"), ("Nuxt", r"^nuxt$"), ("Remix", r"^@remix-run/"),
    ("React Router", r"^react-router$"), ("SvelteKit", r"^@sveltejs/kit$"),
    ("Astro", r"^astro$"), ("Angular", r"^@angular/core$"), ("Vue", r"^vue$"),
    ("React", r"^react$"), ("Express", r"^express$"), ("Fastify", r"^fastify$"),
    ("NestJS", r"^@nestjs/core$"), ("Hono", r"^hono$"), ("Koa", r"^koa$"),
    ("Electron", r"^electron$"), ("React Native", r"^react-native$"), ("Expo", r"^expo$"),
    ("Django", r"^django$"), ("Flask", r"^flask$"), ("FastAPI", r"^fastapi$"),
    ("Laravel", r"^laravel/framework$"), ("Symfony", r"^symfony/framework-bundle$"),
    ("Rails", r"^rails$"), ("Spring Boot", r"spring-boot"), ("Gin", r"gin-gonic/gin"),
    ("Echo", r"labstack/echo"), ("Fiber", r"gofiber/fiber"), ("Chi", r"go-chi/chi"),
    ("ASP.NET Core", r"^microsoft\.aspnetcore"), ("Actix", r"^actix-web$"),
    ("Axum", r"^axum$"), ("Phoenix", r"^phoenix$"), ("Flutter", r"^flutter$"),
]
FRAMEWORK_RES = [(n, re.compile(p, re.I)) for n, p in FRAMEWORKS]

# (label, languages or None for all, pattern). Receivers and verbs are narrowed per
# language: a single-letter receiver is idiomatic in Go (r.Get) but noise in JS (m.get).
ROUTE_RES = [
    ("http-route", {"js", "py"}, re.compile(
        r"\b(app|router|server|api|routes?|fastify|hono|koa|express|v1|v2|admin|public|"
        r"private|protected)\s*\.\s*(get|post|put|patch|delete|all|route|options)\s*"
        r"\(\s*['\"`]/", re.M)),
    ("http-route", {"go"}, re.compile(
        r"\b\w+\s*\.\s*(Get|Post|Put|Patch|Delete|GET|POST|PUT|PATCH|DELETE|Handle|HandleFunc|"
        r"Group|Any)\s*\(\s*\"/", re.M)),
    ("http-route", {"js", "jvm", "cs"}, re.compile(
        r"^[ \t]*@(Get|Post|Put|Patch|Delete|RequestMapping|GetMapping|PostMapping|PutMapping|"
        r"DeleteMapping|PatchMapping|HttpGet|HttpPost|HttpPut|HttpDelete|Route)\s*\(", re.M)),
    ("http-route", {"py"}, re.compile(
        r"^[ \t]*@(app|router|api|bp|blueprint|\w+_router)\.(get|post|put|patch|delete|route|"
        r"api_route)\s*\(", re.M)),
    ("http-route", {"php"}, re.compile(
        r"\bRoute::(get|post|put|patch|delete|resource|apiResource|match|any)\s*\(", re.M)),
    ("http-route", {"cs"}, re.compile(r"\bMap(Get|Post|Put|Patch|Delete)\s*\(", re.M)),
    ("http-route", {"rb"}, re.compile(
        r"^\s*(get|post|put|patch|delete|resources?)\s+['\":]", re.M)),
    ("http-route", {"py"}, re.compile(r"^\s*(re_)?path\s*\(\s*r?['\"]", re.M)),
    ("rpc", {"js"}, re.compile(r"\b(publicProcedure|protectedProcedure|t\.procedure)\b",
                               re.M)),
    ("worker", None, re.compile(
        r"\bnew\s+Worker\s*\(|@(shared_task|app\.task|celery\.task)\b|"
        r"implements\s+ShouldQueue|include\s+Sidekiq::(Job|Worker)|"
        r"@(Process|Processor|KafkaListener|RabbitListener|SqsListener)\b", re.M)),
    ("cron", None, re.compile(
        r"@Cron\s*\(|\bcron\.schedule\s*\(|->(daily|hourly|everyMinute|cron)\s*\(|"
        r"@(periodic_task|scheduled)\b|@Scheduled\s*\(", re.M)),
    ("serverless", {"js", "py"}, re.compile(
        r"^\s*export\s+(const|async\s+function|function)\s+handler\b|"
        r"^def\s+(lambda_)?handler\s*\(\s*event\s*,\s*context", re.M)),
    ("main", None, re.compile(
        r"^func\s+main\s*\(\s*\)|^if\s+__name__\s*==\s*['\"]__main__['\"]|"
        r"\bstatic\s+(async\s+)?(void|Task|int)\s+Main\s*\(|^fn\s+main\s*\(", re.M)),
]
# Next.js: route.ts and pages/api are HTTP endpoints; page.tsx and pages/* are UI routes.
API_FILE_RE = re.compile(r"(^|/)app/(.+/)?route\.(t|j)sx?$|(^|/)pages/api/.+\.(t|j)sx?$")
NEXT_ROUTE_RE = re.compile(r"(^|/)app/(.+/)?page\.(t|j)sx?$|(^|/)pages/(?!_|api/)[^/].*\."
                           r"(t|j)sx?$")
HEALTH_RE = re.compile(r"['\"`/](health|healthz|healthcheck|readyz|livez|ready|live|ping|up|"
                       r"status)['\"`]|actuator/health|AddHealthChecks|HealthCheck|"
                       r"health_check|/api/health", re.I)
ENV_READ_RE = re.compile(r"process\.env\.([A-Z][A-Z0-9_]+)|process\.env\[['\"]([A-Z0-9_]+)|"
                         r"import\.meta\.env\.([A-Z][A-Z0-9_]+)|os\.environ(?:\.get)?"
                         r"[\[(]\s*['\"]([A-Z0-9_]+)|os\.getenv\(\s*['\"]([A-Z0-9_]+)|"
                         r"\benv\(\s*['\"]([A-Z0-9_]+)|getenv\(\s*['\"]([A-Z0-9_]+)|"
                         r"ENV\[['\"]([A-Z0-9_]+)|Environment\.GetEnvironmentVariable\("
                         r"\s*\"([A-Z0-9_]+)|std::env::var\(\s*\"([A-Z0-9_]+)|"
                         r"os\.Getenv\(\s*\"([A-Z0-9_]+)")
SECRET_ENV_RE = re.compile(r"(SECRET|TOKEN|PASSWORD|PASSWD|API_KEY|PRIVATE_KEY|ACCESS_KEY|"
                           r"CLIENT_SECRET|DSN|DATABASE_URL|CONNECTION_STRING)", re.I)

INFRA_FILES = [
    ("container", "Dockerfile", re.compile(r"(^|/)(Dockerfile|Containerfile)(\.[\w.-]+)?$")),
    ("compose", "Docker Compose", re.compile(r"(^|/)(docker-)?compose(\.[\w-]+)?\.ya?ml$")),
    ("k8s", "Kubernetes", re.compile(r"(^|/)(k8s|kubernetes|manifests|deploy|charts)/.*\.ya?ml$")),
    ("helm", "Helm", re.compile(r"(^|/)Chart\.yaml$")),
    ("iac", "Terraform", re.compile(r"\.tf$")),
    ("iac", "Pulumi", re.compile(r"(^|/)Pulumi(\.[\w-]+)?\.ya?ml$")),
    ("iac", "AWS CDK", re.compile(r"(^|/)cdk\.json$")),
    ("iac", "CloudFormation/SAM", re.compile(r"(^|/)(template|samconfig)\.(ya?ml|json|toml)$")),
    ("iac", "Serverless Framework", re.compile(r"(^|/)serverless\.(ya?ml|ts|js)$")),
    ("paas", "Vercel", re.compile(r"(^|/)vercel\.json$")),
    ("paas", "Netlify", re.compile(r"(^|/)netlify\.toml$")),
    ("paas", "Fly.io", re.compile(r"(^|/)fly\.toml$")),
    ("paas", "Render", re.compile(r"(^|/)render\.ya?ml$")),
    ("paas", "Heroku", re.compile(r"(^|/)(Procfile|app\.json)$")),
    ("paas", "Cloudflare Workers", re.compile(r"(^|/)wrangler\.(toml|jsonc?)$")),
    ("paas", "Google App Engine", re.compile(r"(^|/)app\.ya?ml$")),
    ("paas", "Railway", re.compile(r"(^|/)railway\.(json|toml)$")),
    ("ci", "GitHub Actions", re.compile(r"^\.github/workflows/.+\.ya?ml$")),
    ("ci", "GitLab CI", re.compile(r"(^|/)\.gitlab-ci\.ya?ml$")),
    ("ci", "CircleCI", re.compile(r"^\.circleci/config\.ya?ml$")),
    ("ci", "Jenkins", re.compile(r"(^|/)Jenkinsfile$")),
    ("ci", "Azure Pipelines", re.compile(r"(^|/)azure-pipelines\.ya?ml$")),
    ("ci", "Bitbucket Pipelines", re.compile(r"(^|/)bitbucket-pipelines\.ya?ml$")),
]
GOVERNANCE = {
    "adr": re.compile(r"(^|/)(docs?/(adr|adrs|decisions|arch|architecture/decisions|"
                      r"architecture/adr)|adr|adrs|architecture/decisions)/[^/]+\."
                      r"(md|markdown|rst|adoc)$", re.I),
    "arch_doc": re.compile(r"(^|/)(ARCHITECTURE|architecture)\.(md|adoc|rst)$|"
                           r"(^|/)docs?/architecture(/|\.md$)|(^|/)workspace\.dsl$", re.I),
    "codeowners": re.compile(r"^(\.github/|docs/|\.gitlab/)?CODEOWNERS$"),
    "api_contract": re.compile(r"(^|/)(openapi|swagger)[\w.-]*\.(ya?ml|json)$|"
                               r"(^|/)asyncapi[\w.-]*\.(ya?ml|json)$|\.proto$|"
                               r"(^|/)schema\.(graphql|gql)$|\.graphql$", re.I),
    "threat_model": re.compile(r"(^|/)[\w./-]*threat[-_ ]?model[\w.-]*\.(md|adoc|rst|txt)$",
                               re.I),
    "env_example": re.compile(r"(^|/)\.env\.(example|sample|template|dist|defaults)$|"
                              r"(^|/)example\.env$", re.I),
    "fitness": re.compile(r"(^|/)\.dependency-cruiser\.(c?js|json|mjs)$|(^|/)\.importlinter$|"
                          r"(^|/)deptrac\.(php|ya?ml)$|(^|/)\.go-arch-lint\.ya?ml$|"
                          r"(^|/)(archunit|ArchUnit)[\w.-]*$|(^|/)\.madgerc$|"
                          r"(^|/)\.jqassistant\.ya?ml$", re.I),
}
FITNESS_DEP_RE = re.compile(r"^(dependency-cruiser|eslint-plugin-boundaries|"
                            r"eslint-plugin-import|@nx/enforce-module-boundaries|madge|"
                            r"import-linter|pytestarch|qossmic/deptrac.*|deptrac|"
                            r"com\.tngtech\.archunit.*|archunit.*|netarchtest.*|"
                            r"archunitnet|go-arch-lint|arch-go|konsist|spring-modulith.*|"
                            r"@softarc/sheriff-core|eslint-plugin-project-structure)$", re.I)
FITNESS_TEXT_RE = re.compile(r"\[tool\.importlinter\]|\[importlinter\]|ArchRule|"
                             r"NetArchTest|enforce-module-boundaries|boundaries/element-types")


def manifest_deps(root, files):
    """Declared dependencies per manifest, as {name: manifest path}."""
    deps = {}

    def add(name, where):
        name = name.strip().strip("\"'").lower()
        if name and not name.startswith(("#", "-")):
            deps.setdefault(name, where)

    for f in files:
        base = os.path.basename(f)
        if skipped(f):
            continue
        if base == "package.json":
            data = loose_json(read(root, f)) or {}
            for sect in ("dependencies", "devDependencies", "peerDependencies",
                         "optionalDependencies"):
                for n in (data.get(sect) or {}):
                    add(n, f)
        elif base == "composer.json":
            data = loose_json(read(root, f)) or {}
            for sect in ("require", "require-dev"):
                for n in (data.get(sect) or {}):
                    add(n, f)
        elif base in ("requirements.txt", "requirements-dev.txt", "requirements.in") or \
                re.match(r"requirements.*\.txt$", base):
            for ln in (read(root, f) or "").splitlines():
                m = re.match(r"\s*([A-Za-z0-9_.\-\[\]]+)", ln)
                if m and not ln.strip().startswith(("#", "-")):
                    add(re.sub(r"\[.*\]", "", m.group(1)), f)
        elif base == "pyproject.toml":
            text = read(root, f) or ""
            for m in re.finditer(r"^\s*['\"]([A-Za-z0-9_.\-]+)(?:\[[^\]]*\])?\s*[<>=!~;'\"]",
                                 text, re.M):
                add(m.group(1), f)
            for m in re.finditer(r"^([A-Za-z0-9_.\-]+)\s*=\s*[\"{]", text, re.M):
                if m.group(1).lower() not in ("name", "version", "description", "python",
                                              "readme", "license", "requires-python"):
                    add(m.group(1), f)
        elif base == "go.mod":
            for m in re.finditer(r"^\s*(?:require\s+)?([\w.\-]+\.[\w.\-]+/[\w.\-/]+)\s+v",
                                 read(root, f) or "", re.M):
                add(m.group(1), f)
        elif base == "Gemfile":
            for m in re.finditer(r"^\s*gem\s+['\"]([\w\-]+)", read(root, f) or "", re.M):
                add(m.group(1), f)
        elif base == "Cargo.toml":
            text = read(root, f) or ""
            for sect in re.finditer(r"^\[(?:dev-|build-)?dependencies\]\s*$(.*?)(?=^\[|\Z)",
                                    text, re.M | re.S):
                for m in re.finditer(r"^([\w\-]+)\s*=", sect.group(1), re.M):
                    add(m.group(1), f)
        elif base in ("pom.xml",):
            for m in re.finditer(r"<artifactId>([^<]+)</artifactId>", read(root, f) or ""):
                add(m.group(1), f)
        elif base.endswith((".gradle", ".gradle.kts")):
            for m in re.finditer(r"['\"]([\w.\-]+):([\w.\-]+):", read(root, f) or ""):
                add(m.group(1) + "." + m.group(2), f)
                add(m.group(2), f)
        elif base.endswith(".csproj"):
            for m in re.finditer(r"PackageReference\s+Include=\"([^\"]+)\"", read(root, f) or ""):
                add(m.group(1), f)
        elif base == "pubspec.yaml":
            text = read(root, f) or ""
            for sect in re.finditer(r"^(?:dev_)?dependencies:\s*$(.*?)(?=^\S|\Z)", text,
                                    re.M | re.S):
                for m in re.finditer(r"^  ([\w\-]+):", sect.group(1), re.M):
                    add(m.group(1), f)
        elif base == "mix.exs":
            for m in re.finditer(r"\{:(\w+),", read(root, f) or ""):
                add(m.group(1), f)
    return deps


PLACEHOLDER_VALUE_RE = re.compile(
    r"^(secret|password|passwd|root|test|testing|changeme|change_me|example|dummy|null|none|"
    r"local|dev|admin|postgres|mysql|homestead|sail|laravel|app|user|pass|x+|\*+|<[^>]*>|"
    r"\$\{[^}]*\}|your[_-].*)$", re.I)


def secret_like_keys(root, rel):
    """(names, all_placeholders) for keys that look like credentials. Values never leave."""
    names, real = [], False
    for ln in (read(root, rel, 200_000) or "").splitlines():
        m = re.match(r"^\s*(?:export\s+)?([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(\S.*)?$", ln)
        if not m or not m.group(2) or m.group(2).strip("\"' ") == "":
            continue
        if SECRET_ENV_RE.search(m.group(1)) and not re.match(
                r"^(NEXT_PUBLIC_|VITE_|PUBLIC_|REACT_APP_|EXPO_PUBLIC_|NUXT_PUBLIC_)", m.group(1)):
            names.append(m.group(1))
            value = m.group(2).split(" #")[0].strip().strip("\"'")
            if not PLACEHOLDER_VALUE_RE.match(value):
                real = True
    return names, not real


def compose_services(root, rel):
    """Minimal docker-compose reader: service names, images, depends_on. No YAML library."""
    text = read(root, rel) or ""
    services, cur, in_services, key = {}, None, False, None
    for ln in text.splitlines():
        if not ln.strip() or ln.lstrip().startswith("#"):
            continue
        indent = len(ln) - len(ln.lstrip())
        if indent == 0:
            in_services = ln.startswith("services:")
            cur = None
            continue
        if not in_services:
            continue
        m = re.match(r"^(\s+)([\w.\-]+):\s*$", ln)
        if m and (cur is None or indent <= services[cur]["_indent"]):
            cur = m.group(2)
            services[cur] = {"_indent": indent, "image": None, "build": False,
                             "depends_on": [], "ports": []}
            key = None
            continue
        if cur is None:
            continue
        s = ln.strip()
        m = re.match(r"^(image|build|depends_on|ports|environment)\s*:\s*(.*)$", s)
        if m:
            key = m.group(1)
            val = m.group(2).strip().strip("\"'")
            if key == "image" and val:
                services[cur]["image"] = val
            elif key == "build":
                services[cur]["build"] = True
            elif key == "depends_on" and val.startswith("["):
                services[cur]["depends_on"] += [v.strip().strip("\"'")
                                                for v in val.strip("[]").split(",") if v.strip()]
            continue
        if key == "depends_on":
            m = re.match(r"^-\s*([\w.\-]+)|^([\w.\-]+):\s*$", s)
            if m:
                services[cur]["depends_on"].append(m.group(1) or m.group(2))
        elif key == "ports":
            m = re.match(r"^-\s*['\"]?([\d.:\-/]+)", s)
            if m:
                services[cur]["ports"].append(m.group(1))
    for v in services.values():
        v.pop("_indent", None)
    return services


IMAGE_KIND = [
    ("database", re.compile(r"postgres|postgis|mysql|mariadb|mongo|cockroach|mssql|sqlserver|"
                            r"cassandra|scylla|clickhouse|timescale|supabase/postgres|neo4j|"
                            r"couchdb|dynamodb", re.I)),
    ("cache", re.compile(r"redis|valkey|memcached|keydb|dragonfly", re.I)),
    ("queue", re.compile(r"rabbitmq|kafka|redpanda|nats|localstack|zookeeper|activemq|"
                         r"pulsar", re.I)),
    ("search", re.compile(r"elasticsearch|opensearch|meilisearch|typesense|solr", re.I)),
    ("storage", re.compile(r"minio|azurite|fake-gcs", re.I)),
    ("observability", re.compile(r"jaeger|grafana|prometheus|otel|zipkin|loki|tempo|"
                                 r"datadog", re.I)),
    ("proxy", re.compile(r"nginx|traefik|caddy|haproxy|envoy", re.I)),
    ("email", re.compile(r"mailhog|mailpit|maildev", re.I)),
]


# ---------------------------------------------------------------------------
# The scan
# ---------------------------------------------------------------------------


def scan(root, depth=None, include_tests=False, scope=None):
    all_files = [f for f in list_files(root) if not skipped(f)]
    tracked = tracked_files(root)
    resolver = Resolver(root, all_files)

    # Dot directories (.claude, .husky, .storybook) hold tooling, not the product.
    sources = [f for f in all_files if os.path.splitext(f)[1] in LANG_BY_EXT
               and not any(p.startswith(".") for p in f.split("/")[:-1])]
    tests = [f for f in sources if TEST_RE.search(f)]
    graph_files = sources if include_tests else [f for f in sources if not TEST_RE.search(f)]
    scope = scope.strip("/") if scope else None
    in_scope = (lambda f: f.startswith(scope + "/")) if scope else (lambda f: True)
    split = mixed_dirs([scoped(f, scope) for f in graph_files if in_scope(f)])
    depth = depth or choose_depth([scoped(f, scope) for f in graph_files if in_scope(f)]
                                  or graph_files or sources)

    def key_of(f):
        # Inside the scope: components relative to it. Outside: one node per top-level
        # component, so a container's diagram still shows what it reaches for.
        if in_scope(f):
            k = component_key(scoped(f, scope), depth, split)
            return (scope + "/" + k if k != "(root)" else scope) if scope else k
        return "↗ " + component_key(f, 1, set())

    lang_loc = defaultdict(int)
    comp = {}
    comp_stats = defaultdict(lambda: {"files": 0, "loc": 0, "types": 0, "abstract": 0,
                                      "langs": defaultdict(int), "env_reads": 0})
    file_edges = defaultdict(set)
    comp_edges = defaultdict(lambda: defaultdict(int))
    ext_users = defaultdict(set)            # external package → components importing it
    ext_edges = defaultdict(lambda: defaultdict(int))
    file_loc, fan_in = {}, defaultdict(int)
    entry = defaultdict(list)
    health_hits, env_vars = [], defaultdict(set)
    texts, texts_out = {}, set()

    for f in graph_files:
        text = read(root, f)
        if text is None or is_vendored(text):
            continue
        lang = LANG_BY_EXT[os.path.splitext(f)[1]]
        loc = sum(1 for ln in text.splitlines() if ln.strip())
        if not in_scope(f):
            comp[f] = key_of(f)
            texts_out.add(f)
            continue
        file_loc[f] = loc
        lang_loc[lang] += loc
        c = key_of(f)
        comp[f] = c
        st = comp_stats[c]
        st["files"] += 1
        st["loc"] += loc
        st["langs"][lang] += loc
        if lang in TYPE_RE:
            st["types"] += len(TYPE_RE[lang].findall(text))
            st["abstract"] += len(ABSTRACT_RE[lang].findall(text))
        texts[f] = (text, lang)

    for f, (text, lang) in texts.items():
        c = comp[f]
        for kind, tgt in imports_of(resolver, f, text, lang):
            if kind == "file":
                if tgt == f or tgt not in comp:
                    continue
                if tgt not in file_edges[f]:
                    fan_in[tgt] += 1
                file_edges[f].add(tgt)
                if comp[tgt] != c:
                    comp_edges[c][comp[tgt]] += 1
            elif kind in ("ext", "pkg"):
                ext_users[tgt.lower()].add(c)
                ext_edges[c][tgt.lower()] += 1
        for label, langs, rx in ROUTE_RES:
            if langs and lang not in langs:
                continue
            n = len(rx.findall(text))
            if n:
                entry[label].append((f, n))
        if API_FILE_RE.search(f):
            entry["api-route"].append((f, 1))
        elif NEXT_ROUTE_RE.search(f):
            entry["page-route"].append((f, 1))
        if HEALTH_RE.search(text):
            health_hits.append(f)
        reads = set()
        for m in ENV_READ_RE.finditer(text):
            name = next(g for g in m.groups() if g)
            reads.add(name)
            env_vars[name].add(c)
        if reads:
            comp_stats[c]["env_reads"] += 1

    for f in texts_out:
        if any(comp[f] in outs for outs in comp_edges.values()):
            st = comp_stats[comp[f]]
            st["files"] += 1
            st["outside"] = True

    # Declared dependencies → frameworks and external systems.
    deps = manifest_deps(root, all_files)
    frameworks = sorted({n for d in deps for n, rx in FRAMEWORK_RES if rx.search(d)})
    externals = defaultdict(lambda: {"category": None, "packages": set(), "components": set(),
                                     "evidence": set()})
    for d, where in deps.items():
        for cat, name, rx in EXT_RES:
            if rx.search(d):
                e = externals[name]
                e["category"] = cat
                e["packages"].add(d)
                e["evidence"].add(where)
                e["components"] |= ext_users.get(d, set())
                break
    for pkg, users in ext_users.items():
        for cat, name, rx in EXT_RES:
            if rx.search(pkg):
                e = externals[name]
                e["category"] = cat
                e["packages"].add(pkg)
                e["components"] |= users
                break

    infra = defaultdict(list)
    for f in all_files:
        for kind, name, rx in INFRA_FILES:
            if rx.search(f):
                infra[kind].append((name, f))
                break
    services = {}
    for _, f in infra.get("compose", []):
        for name, svc in compose_services(root, f).items():
            svc["file"] = f
            svc["kind"] = next((k for k, rx in IMAGE_KIND if svc["image"]
                                and rx.search(svc["image"])), "app" if svc["build"] else
                               "service")
            services[name] = svc

    gov = {k: sorted(f for f in all_files if rx.search(f)) for k, rx in GOVERNANCE.items()}
    fitness = gov["fitness"] + sorted(
        "%s (%s)" % (d, w) for d, w in deps.items() if FITNESS_DEP_RE.search(d))
    for f in all_files:
        if os.path.basename(f) in ("pyproject.toml", "setup.cfg", "pom.xml", "build.gradle",
                                   "build.gradle.kts", ".eslintrc.json", ".eslintrc.js",
                                   ".eslintrc.cjs", "eslint.config.js", "eslint.config.mjs",
                                   "nx.json", "project.json"):
            if FITNESS_TEXT_RE.search(read(root, f, 400_000) or ""):
                fitness.append(f)
    env_committed = sorted(
        f for f in (tracked or set())
        if re.search(r"(^|/)\.env(\.[\w-]+)?$", f) and not gov["env_example"].__contains__(f)
        and not re.search(r"\.(example|sample|template|dist|defaults)$", f))

    # Metrics — Martin's package metrics over the component graph.
    nodes = sorted(comp_stats)
    ca = {n: 0 for n in nodes}
    ce = {n: len(comp_edges.get(n, {})) for n in nodes}
    for a, outs in comp_edges.items():
        for b in outs:
            ca[b] += 1
    metrics = {}
    for n in nodes:
        st = comp_stats[n]
        inst = ce[n] / (ca[n] + ce[n]) if (ca[n] + ce[n]) else 0.0
        abst = st["abstract"] / st["types"] if st["types"] else None
        metrics[n] = {
            "files": st["files"], "loc": st["loc"], "ca": ca[n], "ce": ce[n],
            "instability": round(inst, 2),
            "abstractness": round(abst, 2) if abst is not None else None,
            "distance": round(abs(abst + inst - 1), 2) if abst is not None else None,
            "layer": None if st.get("outside") else layer_of(n),
            "outside_scope": bool(st.get("outside")),
            "language": LANG_NAME.get(max(st["langs"], key=st["langs"].get), "?")
            if st["langs"] else "?",
        }

    edges_plain = {a: set(b) for a, b in comp_edges.items()}
    comp_cycles = tarjan(nodes, edges_plain)
    file_cycles = tarjan(list(texts), file_edges)

    signals = []

    def signal(gid, severity, title, evidence, standard):
        signals.append({"id": gid, "severity": severity, "title": title,
                        "evidence": evidence, "standard": standard})

    total_loc = sum(file_loc.values()) or 1
    sdp = []
    for scc in comp_cycles:
        path = cycle_path(scc, edges_plain)
        signal("STRUCT-CYCLE", "High" if len(scc) > 2 else "Medium",
               "Components depend on each other in a cycle (%d components)" % len(scc),
               "loop: %s; members: %s" % (" → ".join(path), ", ".join(scc)),
               "ADP — Acyclic Dependencies Principle")
    big_file_cycles = [c for c in file_cycles if len(c) >= 3]
    if big_file_cycles:
        signal("STRUCT-CYCLE-FILE", "Medium",
               "%d file-level import cycles (largest: %d files)"
               % (len(big_file_cycles), len(big_file_cycles[0])),
               ", ".join(big_file_cycles[0][:6]) + (" …" if len(big_file_cycles[0]) > 6 else ""),
               "ADP — Acyclic Dependencies Principle")
    for a, outs in sorted(comp_edges.items()):
        la = metrics[a]["layer"]
        for b, n in sorted(outs.items()):
            lb = metrics[b]["layer"]
            if la and lb and lb in FORBIDDEN.get(la, ()):
                signal("STRUCT-LAYER", "High" if la == "domain" else "Medium",
                       "%s layer (%s) imports %s layer (%s)" % (la, a, lb, b),
                       "%d import(s) %s → %s" % (n, a, b),
                       "Clean Architecture dependency rule / layered style")
            ia, ib = metrics[a]["instability"], metrics[b]["instability"]
            if ib > ia + 0.25 and metrics[b]["ca"] + metrics[b]["ce"] >= 2 and \
                    metrics[a]["ca"] >= 2 and not metrics[b]["outside_scope"]:
                sdp.append((ib - ia, "%s (I=%.2f) → %s (I=%.2f)" % (a, ia, b, ib)))
    if sdp:
        sdp.sort(key=lambda x: -x[0])
        signal("STRUCT-SDP", "Low",
               "%d dependencies point from stable to less stable components" % len(sdp),
               "; ".join(e for _, e in sdp[:5]) + (" …" if len(sdp) > 5 else ""),
               "SDP — Stable Dependencies Principle")
    big = [(f, loc) for f, loc in sorted(file_loc.items(), key=lambda kv: -kv[1])
           if loc >= GOD_FILE_LOC]
    if big:
        signal("STRUCT-GOD-FILE", "High" if big[0][1] >= 2 * GOD_FILE_LOC else "Medium",
               "%d files over %d non-blank lines (heuristic, no published threshold)"
               % (len(big), GOD_FILE_LOC),
               ", ".join("%s (%d)" % (f, loc) for f, loc in big[:5])
               + (" …" if len(big) > 5 else ""),
               "Modularity / SRP (ISO/IEC 25010 maintainability)")
    for n in nodes:
        if metrics[n]["outside_scope"]:
            continue
        share = metrics[n]["loc"] / total_loc
        if share > 0.5 and len(nodes) >= 4:
            signal("STRUCT-GOD-COMPONENT", "Low",
                   "One component holds %.0f%% of the code (heuristic)" % (share * 100), n,
                   "Modularity (ISO/IEC 25010 maintainability)")
        if (metrics[n]["layer"] == "shared" and metrics[n]["ce"] >= 4
                and metrics[n]["ca"] >= max(3, len(nodes) // 3)):
            signal("STRUCT-GRAB-BAG", "Low",
                   "Shared/util component is both heavily used and heavily dependent",
                   "%s (Ca=%d, Ce=%d)" % (n, metrics[n]["ca"], metrics[n]["ce"]),
                   "CRP / CCP — Common Reuse and Common Closure Principles")
        d = metrics[n]["distance"]
        if d is not None and d > 0.7 and comp_stats[n]["types"] >= 5 and metrics[n]["ca"] >= 3:
            zone = "pain" if metrics[n]["instability"] < 0.5 else "uselessness"
            signal("STRUCT-MAIN-SEQUENCE", "Low",
                   "Far from the main sequence (zone of %s)" % zone,
                   "%s (A=%.2f, I=%.2f, D=%.2f)" % (n, metrics[n]["abstractness"],
                                                    metrics[n]["instability"], d),
                   "SAP — Stable Abstractions Principle")

    for name, e in sorted(externals.items()):
        if e["category"] in ("database", "payments", "email", "storage", "queue", "ai",
                             "cms", "search", "auth") and len(e["components"]) >= SPRAWL_COMPONENTS:
            signal("DEP-SDK-SPRAWL", "Medium",
                   "%s SDK used directly from %d components" % (name, len(e["components"])),
                   ", ".join(sorted(e["components"])[:6]),
                   "Ports and Adapters (Hexagonal) / anti-corruption layer")

    config_comps = sorted({c for users in env_vars.values() for c in users})
    if len(config_comps) >= 4:
        signal("CFG-SPRAWL", "Low",
               "Environment variables read directly in %d components" % len(config_comps),
               ", ".join(config_comps[:6]), "Twelve-Factor III (Config) — one typed config module")

    has_http = bool(entry.get("http-route") or entry.get("api-route") or entry.get("rpc"))
    has_server = has_http or bool(entry.get("page-route"))
    deployable = bool(infra.get("container") or infra.get("k8s") or infra.get("paas")
                      or infra.get("iac"))
    obs = {n for n, e in externals.items() if e["category"] == "observability"}

    if not gov["adr"]:
        signal("GOV-ADR", "Medium", "No Architecture Decision Records found",
               "no docs/adr, doc/adr, docs/decisions, doc/arch, or adr/ directory",
               "arc42 §9 Architecture Decisions / Nygard ADRs / ISO/IEC/IEEE 42010 rationale")
    if not gov["arch_doc"]:
        signal("GOV-ARCH-DOC", "Low", "No architecture description in the repository",
               "no ARCHITECTURE.md or docs/architecture", "ISO/IEC/IEEE 42010 / arc42 / C4")
    if not gov["codeowners"] and len(nodes) >= 6:
        signal("GOV-OWNERS", "Low", "No CODEOWNERS — component ownership is implicit",
               "no CODEOWNERS in root, .github/, or docs/", "Conway's law / team topology")
    if has_http and not gov["api_contract"] and not any(
            re.search(r"swagger|openapi|spectacular|springdoc|swashbuckle|scramble|fastapi",
                      d) for d in deps):
        signal("API-CONTRACT", "Medium", "HTTP API has no machine-readable contract",
               "routes found, no openapi/swagger/asyncapi/proto/graphql schema",
               "OpenAPI Specification / API-first design")
    if has_server and deployable and not health_hits:
        signal("OPS-HEALTH", "Medium", "No health or readiness endpoint found",
               "no /health, /healthz, /readyz, /up, or health-check registration",
               "Twelve-Factor IX (Disposability) / Kubernetes probes")
    if not any(externals[n]["category"] == "observability" and n != "Structured logging"
               for n in obs) and (has_server or deployable):
        signal("OPS-OBSERVABILITY", "Medium", "No error tracking or tracing library",
               "no Sentry/OpenTelemetry/Datadog/New Relic/Prometheus client in manifests",
               "OpenTelemetry / Well-Architected operational excellence")
    for f in env_committed:
        keys, placeholders = secret_like_keys(root, f)
        if keys and placeholders:
            signal("SEC-ENV-COMMITTED", "Low",
                   "Environment file committed; its secret-like keys hold placeholder values",
                   "%s — keys: %s (values not read into this report)"
                   % (f, ", ".join(keys[:6])),
                   "Twelve-Factor III (Config) / OWASP Secrets Management")
        elif keys:
            signal("SEC-ENV-COMMITTED", "Critical",
                   "Environment file with secret-like keys committed to git",
                   "%s — keys: %s (values not read into this report)"
                   % (f, ", ".join(keys[:6]) + (" …" if len(keys) > 6 else "")),
                   "Twelve-Factor III (Config) / OWASP Secrets Management")
        else:
            signal("SEC-ENV-COMMITTED", "Low",
                   "Environment file committed to git (no secret-like key names)",
                   "%s — confirm every value is public" % f,
                   "Twelve-Factor III (Config) / OWASP Secrets Management")
    if env_vars and not gov["env_example"]:
        signal("CFG-ENV-EXAMPLE", "Low", "Env vars are read but no .env.example documents them",
               "%d distinct variables read" % len(env_vars), "Twelve-Factor III (Config)")
    if not gov["threat_model"] and has_http:
        signal("SEC-THREAT-MODEL", "Low", "No threat model document",
               "no *threat-model* file", "OWASP Threat Modeling / STRIDE")
    if not fitness and len(nodes) >= 6:
        signal("FIT-NONE", "Medium", "Architecture rules are not enforced in CI",
               "no dependency-cruiser, import-linter, deptrac, ArchUnit, boundaries rule, "
               "or equivalent", "Fitness functions (Building Evolutionary Architectures)")
    if not tests:
        signal("TEST-NONE", "High", "No test files found", "0 files match test conventions",
               "ISO/IEC 25010 maintainability (testability)")
    if not infra.get("ci"):
        signal("OPS-CI", "Medium", "No CI pipeline configuration found",
               "no .github/workflows, .gitlab-ci.yml, Jenkinsfile, …",
               "Twelve-Factor V (Build, release, run)")
    if (has_server or services) and not deployable and not services:
        signal("OPS-DEPLOY-UNKNOWN", "Info", "Deployment target not determinable from code",
               "no Dockerfile, IaC, or platform config", "C4 deployment view / arc42 §7")
    db_services = [n for n, s in services.items() if s["kind"] == "database"]
    app_services = [n for n, s in services.items() if s["kind"] in ("app",)]
    for db in db_services:
        users = [a for a in app_services if db in services[a]["depends_on"]]
        if len(users) >= 2:
            signal("DATA-SHARED-DB", "Medium",
                   "Database shared by %d deployable services" % len(users),
                   "%s ← %s" % (db, ", ".join(users)),
                   "Database per service / bounded contexts (DDD)")

    rank = {"Critical": 0, "High": 1, "Medium": 2, "Low": 3, "Info": 4}
    signals.sort(key=lambda s: (rank[s["severity"]], s["id"]))

    return {
        "version": 1,
        "root": root,
        "scope": scope,
        "depth": depth,
        "stats": {
            "files": len(all_files), "source_files": len(graph_files), "test_files": len(tests),
            "loc": sum(file_loc.values()),
            "languages": {LANG_NAME[k]: v for k, v in sorted(lang_loc.items(),
                                                             key=lambda kv: -kv[1])},
            "components": len(nodes),
            "component_edges": sum(len(v) for v in comp_edges.values()),
            "file_edges": sum(len(v) for v in file_edges.values()),
        },
        "frameworks": frameworks,
        "components": metrics,
        "edges": [{"from": a, "to": b, "imports": n}
                  for a, outs in sorted(comp_edges.items()) for b, n in sorted(outs.items())],
        "cycles": {"components": comp_cycles, "files": big_file_cycles[:20]},
        "hotspots": [{"file": f, "loc": file_loc[f], "fan_in": fan_in.get(f, 0),
                      "fan_out": len(file_edges.get(f, ()))}
                     for f in sorted(file_loc, key=lambda x: -(fan_in.get(x, 0)
                                                               + len(file_edges.get(x, ()))))[:15]],
        "entry_points": {k: sorted(v, key=lambda x: -x[1])[:25] for k, v in entry.items()},
        "entry_point_counts": {k: sum(n for _, n in v) for k, v in entry.items()},
        "externals": {n: {"category": e["category"], "packages": sorted(e["packages"]),
                          "components": sorted(e["components"]),
                          "evidence": sorted(e["evidence"])}
                      for n, e in sorted(externals.items())},
        "external_edges": {c: dict(v) for c, v in ext_edges.items()},
        "infrastructure": {k: [{"tool": n, "file": f} for n, f in v] for k, v in infra.items()},
        "compose_services": services,
        "governance": {k: v[:20] for k, v in gov.items()},
        "fitness_functions": fitness[:20],
        "env_vars": {k: sorted(v) for k, v in sorted(env_vars.items())},
        "health_endpoints": health_hits[:10],
        "signals": signals,
    }


# ---------------------------------------------------------------------------
# Mermaid
# ---------------------------------------------------------------------------


def _mm_label(s):
    return (s.replace("&", "#amp;").replace('"', "#quot;").replace("<", "#lt;")
            .replace(">", "#gt;"))


def _kloc(n):
    return "%.1fk LOC" % (n / 1000) if n >= 1000 else "%d LOC" % n


# Explicit fills with explicit text colour read the same on GitHub's light and dark themes.
# Plain flowchart syntax only: Mermaid's C4 diagrams are experimental and cannot draw a key.
CLASSDEFS = [
    "classDef comp fill:#1f6feb,stroke:#0b3d91,color:#ffffff",
    "classDef cycle fill:#cf222e,stroke:#82071e,color:#ffffff",
    "classDef ext fill:#6e7781,stroke:#424a53,color:#ffffff",
    "classDef store fill:#8250df,stroke:#512a97,color:#ffffff",
    "classDef person fill:#0969da,stroke:#033d8b,color:#ffffff",
    "classDef other fill:#afb8c1,stroke:#6e7781,color:#1f2328",
]


def _frontmatter(title):
    return ["---", "title: %s" % title.replace(":", " -"), "---"]


def _legend(entries):
    out = ['  subgraph Legend["Legend"]', "    direction LR"]
    for i, (cls, label, shape) in enumerate(entries):
        out.append("    lg%d%s" % (i, shape % _mm_label(label)))
    out.append("  end")
    for i, (cls, _, _) in enumerate(entries):
        out.append("  class lg%d %s" % (i, cls))
    return out


def mermaid_components(res, max_nodes, max_edges=60):
    comps = res["components"]
    cyc = {c for scc in res["cycles"]["components"] for c in scc}
    degree = defaultdict(int)
    for e in res["edges"]:
        degree[e["from"]] += 1
        degree[e["to"]] += 1
    ranked = sorted(comps, key=lambda c: -(comps[c]["loc"] + 400 * degree[c]
                                            + 5000 * (c in cyc)))
    keep = set(ranked[:max_nodes])
    dropped = [c for c in comps if c not in keep]
    ids = {c: "c%d" % i for i, c in enumerate(sorted(keep))}
    scope = res.get("scope") or os.path.basename(res["root"].rstrip("/"))
    lines = _frontmatter("Component dependencies - %s" % scope) + ["flowchart LR"]
    groups = defaultdict(list)
    for c in sorted(keep):
        m = comps[c]
        groups["outside" if m.get("outside_scope") else (m["layer"] or "other")].append(c)
    order = ["presentation", "application", "domain", "infrastructure", "shared", "other",
             "outside"]
    use_groups = len([g for g in groups if g not in ("other", "outside")]) >= 2
    for g in order:
        if g not in groups:
            continue
        boxed = use_groups or g == "outside"
        if boxed:
            title = "Outside this scope" if g == "outside" else g.capitalize()
            lines.append('  subgraph L_%s["%s"]' % (g, title))
        for c in groups[g]:
            m = comps[c]
            detail = ("%d files imported" % m["files"] if m.get("outside_scope")
                      else "%d files, %s" % (m["files"], _kloc(m["loc"])))
            lines.append('    %s["%s<br/>%s"]' % (ids[c], _mm_label(c), detail))
        if boxed:
            lines.append("  end")
    if dropped:
        lines.append('  other["%d smaller components"]' % len(dropped))
    cycle_pairs = {(a, b) for scc in res["cycles"]["components"] for a in scc for b in scc}
    agg = defaultdict(int)
    for e in res["edges"]:
        a = ids.get(e["from"], "other" if dropped else None)
        b = ids.get(e["to"], "other" if dropped else None)
        if not a or not b or a == b:
            continue
        agg[(a, b, (e["from"], e["to"]) in cycle_pairs)] += e["imports"]
    # Readability: every cycle edge stays; the rest keep the heaviest until the cap.
    cyc_edges = [kv for kv in agg.items() if kv[0][2]]
    rest = sorted((kv for kv in agg.items() if not kv[0][2]), key=lambda kv: -kv[1])
    shown = cyc_edges + rest[:max(0, max_edges - len(cyc_edges))]
    hidden = rest[len(shown) - len(cyc_edges):]
    red = []
    for i, ((a, b, is_cycle), n) in enumerate(sorted(shown)):
        lines.append("  %s -->|imports x%d| %s" % (a, n, b))
        if is_cycle:
            red.append(i)
    legend = [("comp", "Component", '["%s"]'), ("cycle", "In a dependency cycle", '["%s"]'),
              ("ext", "Outside scope", '["%s"]')]
    if hidden:
        heaviest = max(n for _, n in hidden)
        legend.append(("other", "%d lighter edges hidden (%s%d import%s each)"
                       % (len(hidden), "at most " if heaviest > 1 else "", heaviest,
                          "s" if heaviest > 1 else ""), '["%s"]'))
    lines += _legend(legend)
    lines += ["  " + c for c in CLASSDEFS]
    normal = [ids[c] for c in keep if c not in cyc and not comps[c].get("outside_scope")]
    if normal:
        lines.append("  class %s comp" % ",".join(sorted(normal)))
    hot = [ids[c] for c in keep if c in cyc]
    if hot:
        lines.append("  class %s cycle" % ",".join(sorted(hot)))
    outside = [ids[c] for c in keep if comps[c].get("outside_scope") and c not in cyc]
    if outside:
        lines.append("  class %s ext" % ",".join(sorted(outside)))
    if dropped:
        lines.append("  class other other")
    if red:
        lines.append("  linkStyle %s stroke:#cf222e,stroke-width:2px"
                     % ",".join(str(i) for i in red))
    return "\n".join(lines)


SHAPES = {"database": '[("%s")]', "cache": '[("%s")]', "queue": '[/"%s"/]',
          "storage": '[("%s")]', "search": '[("%s")]'}
STORE_KINDS = {"database", "cache", "queue", "storage", "search"}
INTENT = {"database": "reads and writes", "cache": "caches in", "queue": "publishes jobs to",
          "storage": "stores files in", "search": "indexes and queries", "payments":
          "charges via", "email": "sends email via", "auth": "authenticates with",
          "observability": "reports errors and traces to", "analytics": "sends events to",
          "ai": "calls", "cms": "reads content from", "realtime": "pushes updates via",
          "flags": "reads flags from"}


def _two_line(first, second):
    return "%s<br/>%s" % (_mm_label(first), _mm_label(second))


def mermaid_containers(res):
    name = os.path.basename(res["root"].rstrip("/")) or "System"
    lines = _frontmatter("Containers - %s (draft from code, verify intents)" % name)
    lines += ["flowchart TB", '  user(["User<br/>Person"])']
    services = res["compose_services"]
    runnable = {n for n, s in services.items() if s["kind"] in ("app", "service", "proxy")}
    lines.append('  subgraph SYS["%s - software system"]' % _mm_label(name))
    ids, klass = {}, {}
    tech = " / ".join(res["frameworks"][:3]) or "application"
    if runnable:
        for i, n in enumerate(sorted(runnable)):
            ids[n] = "a%d" % i
            klass[n] = "comp"
            role = "Reverse proxy" if services[n]["kind"] == "proxy" else "Container"
            lines.append('    %s["%s"]' % (ids[n], _two_line(n, "%s: %s" % (
                role, services[n]["image"] or tech))))
    else:
        ids["app"] = "a0"
        klass["app"] = "comp"
        lines.append('    a0["%s"]' % _two_line("Application", "Container: %s" % tech))
    others = sorted((n, s) for n, s in services.items() if n not in runnable)
    for i, (n, s) in enumerate(others):
        ids[n] = "s%d" % i
        klass[n] = "store" if s["kind"] in STORE_KINDS else "ext"
        shape = SHAPES.get(s["kind"], '["%s"]')
        lines.append("    %s%s" % (ids[n], shape % _two_line(n, s["image"] or s["kind"])))
    lines.append("  end")
    # The user reaches the system through the front proxy (one nothing else depends on),
    # else through the first application container.
    depended = {d for s in services.values() for d in s["depends_on"]}
    fronts = sorted(n for n in runnable if services[n]["kind"] == "proxy" and n not in depended)
    apps = sorted(n for n in runnable if services[n]["kind"] != "proxy")
    entry = ids[fronts[0]] if fronts else (ids[apps[0]] if apps else "a0")
    main_app = ids[apps[0]] if apps else entry
    lines.append('  user -->|"uses (HTTPS)"| %s' % entry)
    for n, s in sorted(services.items()):
        for dep in s["depends_on"]:
            if n in ids and dep in ids:
                if s["kind"] == "proxy":
                    label = "forwards requests to"
                else:
                    label = INTENT.get(services.get(dep, {}).get("kind"), "depends on")
                lines.append('  %s -->|"%s"| %s' % (ids[n], label, ids[dep]))
    k = 0
    covered = {s["kind"] for _, s in others}
    for ename, e in sorted(res["externals"].items()):
        if e["category"] in ("http", "api") or (e["category"] in covered
                                                 and e["category"] in SHAPES):
            continue
        k += 1
        nid = "x%d" % k
        shape = SHAPES.get(e["category"], '["%s"]')
        lines.append("  %s%s" % (nid, shape % _two_line(ename, "External: %s" % e["category"])))
        lines.append('  %s -.->|"%s"| %s' % (main_app, INTENT.get(e["category"], "uses"), nid))
    lines += _legend([("person", "Person", '(["%s"])'),
                      ("comp", "Container (this system)", '["%s"]'),
                      ("store", "Data store", '[("%s")]'),
                      ("ext", "External or dev-only service", '["%s"]')])
    lines += ["  " + c for c in CLASSDEFS]
    lines.append("  class user person")
    for cls in ("comp", "store", "ext"):
        members = [ids[n] for n, c in klass.items() if c == cls]
        if cls == "ext":
            members += ["x%d" % i for i in range(1, k + 1)]
        if members:
            lines.append("  class %s %s" % (",".join(members), cls))
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Text summary
# ---------------------------------------------------------------------------


def render(res):
    s, out = res["stats"], []
    out.append("## Architecture scan")
    out.append("")
    out.append("- Root: `%s`  (component depth %d)" % (res["root"], res["depth"]))
    out.append("- Files: %d total, %d source, %d test · %s"
               % (s["files"], s["source_files"], s["test_files"], _kloc(s["loc"])))
    out.append("- Languages: %s" % (", ".join("%s (%s)" % (k, _kloc(v))
                                              for k, v in s["languages"].items()) or "none"))
    out.append("- Frameworks: %s" % (", ".join(res["frameworks"]) or "none detected"))
    out.append("- Components: %d · component edges %d · file edges %d"
               % (s["components"], s["component_edges"], s["file_edges"]))
    out.append("")
    out.append("### Components (Martin metrics)")
    out.append("")
    out.append("| Component | Layer | Files | LOC | Ca | Ce | I | A | D |")
    out.append("|---|---|---:|---:|---:|---:|---:|---:|---:|")
    for c, m in sorted(res["components"].items(), key=lambda kv: -kv[1]["loc"])[:40]:
        out.append("| `%s` | %s | %d | %d | %d | %d | %.2f | %s | %s |"
                   % (c, m["layer"] or "—", m["files"], m["loc"], m["ca"], m["ce"],
                      m["instability"],
                      "—" if m["abstractness"] is None else "%.2f" % m["abstractness"],
                      "—" if m["distance"] is None else "%.2f" % m["distance"]))
    out.append("")
    out.append("### Heaviest dependencies")
    out.append("")
    for e in sorted(res["edges"], key=lambda e: -e["imports"])[:15]:
        out.append("- `%s` → `%s` (%d imports)" % (e["from"], e["to"], e["imports"]))
    if res["cycles"]["components"]:
        out.append("")
        out.append("### Component cycles")
        out.append("")
        for scc in res["cycles"]["components"]:
            out.append("- " + ", ".join("`%s`" % c for c in scc))
    out.append("")
    out.append("### Entry points")
    out.append("")
    if not res["entry_point_counts"]:
        out.append("- none detected")
    for k, n in sorted(res["entry_point_counts"].items(), key=lambda kv: -kv[1]):
        sample = ", ".join("`%s`" % f for f, _ in res["entry_points"][k][:4])
        out.append("- %s: %d in %d files — %s" % (k, n, len(res["entry_points"][k]), sample))
    out.append("")
    out.append("### External systems")
    out.append("")
    if not res["externals"]:
        out.append("- none detected")
    for n, e in sorted(res["externals"].items(), key=lambda kv: kv[1]["category"]):
        out.append("- **%s** (%s): %s — used in %s"
                   % (n, e["category"], ", ".join(e["packages"][:4]),
                      ", ".join("`%s`" % c for c in e["components"][:5]) or "no import found"))
    out.append("")
    out.append("### Infrastructure")
    out.append("")
    if not res["infrastructure"]:
        out.append("- none detected")
    for k, v in sorted(res["infrastructure"].items()):
        out.append("- %s: %s" % (k, ", ".join("%s `%s`" % (x["tool"], x["file"]) for x in v[:5])))
    if res["compose_services"]:
        out.append("- compose services: " + ", ".join(
            "%s (%s)" % (n, s["kind"]) for n, s in sorted(res["compose_services"].items())))
    out.append("")
    out.append("### Gap signals (candidates — confirm each before reporting)")
    out.append("")
    if not res["signals"]:
        out.append("- none")
    for g in res["signals"]:
        out.append("- **%s** [%s] %s — %s _(standard: %s)_"
                   % (g["id"], g["severity"], g["title"], g["evidence"], g["standard"]))
    out.append("")
    out.append("Gap IDs map to references/GAP_CATALOGUE.md.")
    return "\n".join(out)


# ---------------------------------------------------------------------------
# Self-test
# ---------------------------------------------------------------------------

FIXTURE = {
    "package.json": '{"name":"shop","dependencies":{"next":"15.0.0","react":"19.0.0",'
                    '"stripe":"1.0.0","@prisma/client":"5.0.0","axios":"1.0.0"}}',
    "tsconfig.json": '{\n  // comments are allowed here\n  "compilerOptions": {"baseUrl": ".",'
                     ' "paths": {"@/*": ["src/*"]},}\n}',
    "src/domain/order.ts": "import { formatPrice } from '@/ui/price';\n"
                           "export interface Order { id: string }\n",
    "src/ui/price.ts": "import { Order } from '../domain/order';\n"
                       "export const formatPrice = (o: Order) => o.id;\n",
    "src/services/checkout.ts": "import Stripe from 'stripe';\nimport { Order } from "
                                "'@/domain/order';\nimport { db } from '../infra/db';\n"
                                "export async function checkout(o: Order) {}\n",
    "src/infra/db.ts": "import { PrismaClient } from '@prisma/client';\n"
                       "export const db = new PrismaClient();\n",
    "src/billing/refund.ts": "import Stripe from 'stripe';\nexport const r = 1;\n",
    "src/admin/payouts.ts": "import Stripe from 'stripe';\nconst k = process.env.STRIPE_KEY;\n",
    "src/app/api/orders/route.ts": "import { checkout } from '@/services/checkout';\n"
                                   "export async function POST() {}\n",
    "src/app/page.tsx": "export default function Page() { return null }\n",
    "src/index.ts": "import { checkout } from './services/checkout';\n",
    "src/env.ts": "export type Env = { KEY: string };\n",
    "src/billing/tax.ts": "import type { Env } from '../env';\nexport const t = 1;\n",
    "config/app.php": "<?php return [];\n",
    "config/cache.php": "<?php return [];\n",
    "api/app.py": "from flask import Flask\nfrom models import user\n"
                  "app = Flask(__name__)\n@app.get('/users')\ndef users():\n    return []\n",
    "models/user.py": "from api import app\nclass User:\n    pass\n",
    "api/__init__.py": "",
    "models/__init__.py": "",
    ".env": "DB_PASSWORD=Zq8#long-real-looking-value\nAPP_NAME=shop\n",
    ".env.testing": "DB_PASSWORD=secret\n",
    "docker-compose.yml": "services:\n  web:\n    build: .\n    depends_on:\n      - db\n"
                          "  worker:\n    build: .\n    depends_on: [db]\n"
                          "  db:\n    image: postgres:16\n",
}


def self_test():
    import tempfile
    failures = []
    with tempfile.TemporaryDirectory() as tmp:
        for rel, body in FIXTURE.items():
            path = os.path.join(tmp, rel)
            os.makedirs(os.path.dirname(path), exist_ok=True)
            with open(path, "w", encoding="utf-8") as fh:
                fh.write(body)
        try:
            git_ok = subprocess.run(["git", "init", "-q", tmp], capture_output=True,
                                    timeout=30).returncode == 0 and subprocess.run(
                ["git", "-C", tmp, "add", "-A"], capture_output=True, timeout=30).returncode == 0
        except (OSError, subprocess.SubprocessError):
            git_ok = False
        res = scan(tmp, depth=1)
        ids = {s["id"] for s in res["signals"]}
        edges = {(e["from"], e["to"]) for e in res["edges"]}

        def expect(cond, msg):
            if not cond:
                failures.append(msg)

        expect(("src/domain", "src/ui") in edges, "tsconfig path alias '@/' not resolved")
        expect(("src/ui", "src/domain") in edges, "relative import not resolved")
        expect(("src/services", "src/infra") in edges, "relative sibling import not resolved")
        expect(any(set(c) == {"src/domain", "src/ui"} for c in res["cycles"]["components"]),
               "domain ↔ ui cycle not detected")
        expect("STRUCT-CYCLE" in ids, "STRUCT-CYCLE signal missing")
        expect(not any("src/index" in c and "src/env" in c for c in res["cycles"]["components"]),
               "loose root files merged into one component and faked a cycle")
        expect("src/index" in res["components"] and "src/env" in res["components"],
               "loose files above the component level are not their own nodes")
        res_d2 = scan(tmp, depth=2)
        expect("config" in res_d2["components"] and "config/app" not in res_d2["components"],
               "a directory of loose files was split into one node per file")
        expect("STRUCT-LAYER" in ids, "domain → presentation layer violation missing")
        expect("DEP-SDK-SPRAWL" in ids, "Stripe imported from 3 components not flagged")
        expect("Next.js" in res["frameworks"], "Next.js not detected from package.json")
        expect("Payments" in res["externals"], "Stripe not classified as Payments")
        expect("page-route" in res["entry_points"] and "api-route" in res["entry_points"],
               "Next.js page and API route files not told apart")
        expect("http-route" in res["entry_points"], "Flask route decorator not detected")
        expect(("api", "models") in edges, "Python absolute import not resolved")
        expect(("models", "api") in edges, "Python 'from package import module' not resolved")
        multi = imports_of(Resolver(tmp, list(FIXTURE)), "x.py",
                                        "from models import (\n    user,\n)\nimport api\n", "py")
        expect(("file", "models/user.py") in multi and ("file", "api/__init__.py") in multi,
               "parenthesized or plain Python imports not resolved")
        expect("DATA-SHARED-DB" in ids, "db shared by web and worker not flagged")
        expect("GOV-ADR" in ids and "TEST-NONE" in ids, "governance gaps missing")
        expect(res["compose_services"].get("db", {}).get("kind") == "database",
               "compose postgres not classified as database")
        env = {s["evidence"].split(" ")[0]: s["severity"] for s in res["signals"]
               if s["id"] == "SEC-ENV-COMMITTED"}
        if git_ok:
            expect(env.get(".env") == "Critical", "committed .env with a real value not Critical")
            expect(env.get(".env.testing") == "Low", "placeholder-only .env.testing not Low")
        expect(not any("Zq8" in json.dumps(s) for s in res["signals"]),
               "a secret value leaked into a signal")
        mm = mermaid_components(res, 30)
        expect(mm.startswith("---\ntitle:") and "flowchart LR" in mm
               and "classDef cycle" in mm and "linkStyle" in mm and "Legend" in mm,
               "component diagram missing title, legend, or cycle styling")
        expect("<small>" not in mm and "@{" not in mm,
               "diagram uses syntax GitHub may not render")
        mc = mermaid_containers(res)
        expect('[("db<br/>' in mc and "user -->" in mc, "container diagram missing store or user")
        expect("#lt;br" not in mc, "a <br/> in a container label was escaped into text")
        # Tests must not pollute the graph unless asked.
        os.makedirs(os.path.join(tmp, "src/ui/__tests__"))
        with open(os.path.join(tmp, "src/ui/__tests__/price.test.ts"), "w") as fh:
            fh.write("import { checkout } from '@/services/checkout';\n")
        res2 = scan(tmp, depth=1)
        expect(("src/ui", "src/services") not in {(e["from"], e["to"]) for e in res2["edges"]},
               "test imports leaked into the component graph")
        expect(res2["stats"]["test_files"] == 1, "test file not counted")
        expect("TEST-NONE" not in {s["id"] for s in res2["signals"]},
               "TEST-NONE fired although a test exists")

    for f in failures:
        print("FAIL  " + f, file=sys.stderr)
    if failures:
        print("\n%d checks failed" % len(failures), file=sys.stderr)
        return 1
    print("scan-architecture self-test: all checks passed")
    return 0


# ---------------------------------------------------------------------------


def main(argv):
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("root", nargs="?", default=".", help="repository root (default: .)")
    ap.add_argument("--depth", type=int, default=None,
                    help="path segments per component (default: auto)")
    ap.add_argument("--scope", metavar="PATH",
                    help="draw components inside one container (e.g. apps/api); imports "
                         "leaving it collapse to one node per target")
    ap.add_argument("--include-tests", action="store_true",
                    help="keep test files in the dependency graph")
    ap.add_argument("--json", action="store_true", help="emit the full scan as JSON")
    ap.add_argument("--mermaid", choices=("components", "containers", "all"),
                    help="emit Mermaid diagram source instead of the summary")
    ap.add_argument("--max-nodes", type=int, default=DEFAULT_MAX_NODES,
                    help="component nodes drawn before the rest collapse (default %d)"
                         % DEFAULT_MAX_NODES)
    ap.add_argument("--max-edges", type=int, default=60,
                    help="edges drawn before the lightest are hidden (default 60); "
                         "cycle edges are always drawn")
    ap.add_argument("--self-test", action="store_true", help="run the built-in fixture")
    args = ap.parse_args(argv)

    if args.self_test:
        return self_test()

    root = os.path.abspath(args.root)
    try:
        top = subprocess.run(["git", "-C", root, "rev-parse", "--show-toplevel"],
                             capture_output=True, text=True, timeout=30)
        if top.returncode == 0 and top.stdout.strip() and args.root == ".":
            root = top.stdout.strip()
    except (OSError, subprocess.SubprocessError):
        pass

    res = scan(root, args.depth, args.include_tests, args.scope)
    if args.json:
        print(json.dumps(res, indent=2, default=list))
    elif args.mermaid:
        if args.mermaid in ("components", "all"):
            print("```mermaid\n%s\n```" % mermaid_components(res, args.max_nodes,
                                                              args.max_edges))
        if args.mermaid in ("containers", "all"):
            print("```mermaid\n%s\n```" % mermaid_containers(res))
    else:
        print(render(res))
    return 0


if __name__ == "__main__":
    try:
        sys.exit(main(sys.argv[1:]))
    except KeyboardInterrupt:
        sys.exit(130)
