#!/usr/bin/env python3
"""Inventory a codebase's comments and flag cleanup candidates.

A repo-wide comment sweep is not tractable by reading every file: the context window runs
out long before the edits start. This script does the mechanical pass first — find every
comment, match it against the antipattern catalogue, and emit a work list the agent can act
on file by file.

Every finding is a *candidate*, not a verdict. The heuristics here cannot read intent, so the
agent must open the file and decide. Rule IDs match references/ANTIPATTERNS.md.

Usage:
    scan-comments.py [paths...] [--json] [--cap N] [--rules ID,ID] [--summary-only]
    scan-comments.py --self-test

Exits 0 for any scan result, including findings — this reports, it never gates.
--self-test exits non-zero on failure so it can be wired into a test suite.
"""

import argparse
import io
import json
import os
import re
import subprocess
import sys
import tokenize
from bisect import bisect_right

MAX_FILE_BYTES = 1_000_000
DEFAULT_INLINE_CAP = 3
LONG_TRAILING_CHARS = 80

# ---------------------------------------------------------------------------
# Language profiles
# ---------------------------------------------------------------------------


class Profile:
    def __init__(self, line=(), block=(), strings=(), regex=False, template=False):
        self.line = list(line)
        self.block = list(block)
        self.strings = list(strings)
        self.regex = regex          # JS-family regex literals, so /a//b/ is not a comment
        self.template = template    # backtick strings with ${} interpolation


DQ = ('"', '"', True)
SQ = ("'", "'", True)
SQ_RAW = ("'", "'", False)          # shell/SQL single quotes do not process backslash escapes

P_JS = Profile(["//"], [("/*", "*/")], [DQ, SQ], regex=True, template=True)
P_CLIKE = Profile(["//"], [("/*", "*/")], [DQ, SQ])
P_PHP = Profile(["//", "#"], [("/*", "*/")], [DQ, SQ])
P_HASH = Profile(["#"], [], [DQ, SQ_RAW])
P_SQL = Profile(["--"], [("/*", "*/")], [SQ_RAW, DQ])
P_HTML = Profile([], [("<!--", "-->")], [])
P_CSS = Profile([], [("/*", "*/")], [DQ, SQ])
P_LUA = Profile(["--"], [("--[[", "]]")], [DQ, SQ])
P_MIXED = Profile(["//"], [("/*", "*/"), ("<!--", "-->")], [DQ, SQ], regex=True, template=True)

EXT_PROFILE = {}
for _e in (".js", ".jsx", ".mjs", ".cjs", ".ts", ".tsx", ".mts", ".cts"):
    EXT_PROFILE[_e] = P_JS
for _e in (".java", ".c", ".h", ".cc", ".cpp", ".hpp", ".cxx", ".hh", ".cs", ".go", ".rs",
           ".swift", ".kt", ".kts", ".scala", ".dart", ".groovy", ".m", ".mm", ".proto",
           ".sol", ".zig", ".json5"):
    EXT_PROFILE[_e] = P_CLIKE
for _e in (".php", ".inc"):
    EXT_PROFILE[_e] = P_PHP
for _e in (".rb", ".sh", ".bash", ".zsh", ".ksh", ".yaml", ".yml", ".toml", ".ini", ".cfg",
           ".conf", ".pl", ".pm", ".r", ".jl", ".nim", ".cr", ".tf", ".tfvars", ".ex", ".exs"):
    EXT_PROFILE[_e] = P_HASH
EXT_PROFILE[".py"] = P_HASH          # replaced by the tokenize path; kept as the fallback
EXT_PROFILE[".pyi"] = P_HASH
EXT_PROFILE[".sql"] = P_SQL
for _e in (".html", ".htm", ".xml", ".svg", ".xhtml"):
    EXT_PROFILE[_e] = P_HTML
for _e in (".css", ".scss", ".sass", ".less", ".styl"):
    EXT_PROFILE[_e] = P_CSS
EXT_PROFILE[".lua"] = P_LUA
for _e in (".vue", ".svelte", ".astro"):
    EXT_PROFILE[_e] = P_MIXED

NAME_PROFILE = {"Dockerfile": P_HASH, "Makefile": P_HASH, "Gemfile": P_HASH, "Rakefile": P_HASH}

SKIP_DIRS = {
    ".git", ".hg", ".svn", "node_modules", "vendor", "bower_components", "dist", "build",
    "out", "target", ".next", ".nuxt", ".svelte-kit", ".turbo", ".cache", "__pycache__",
    ".venv", "venv", "env", ".tox", ".mypy_cache", ".pytest_cache", ".ruff_cache",
    "coverage", ".coverage", "htmlcov", "Pods", "DerivedData", ".gradle", ".idea", ".vscode",
    "migrations", "generated", "__generated__", ".terraform", "storybook-static",
}
SKIP_FILE_RE = re.compile(
    r"(\.min\.(js|css)$|\.bundle\.|[.-]lock\.|^package-lock\.json$|^yarn\.lock$|"
    r"^composer\.lock$|^Cargo\.lock$|^poetry\.lock$|^pnpm-lock\.yaml$|\.map$|"
    r"\.d\.ts$|\.pb\.go$|_pb2\.py$|\.generated\.)"
)
GENERATED_FILE_RE = re.compile(
    r"@generated\b|Code generated .{0,40}DO NOT EDIT|DO NOT EDIT THIS FILE|"
    r"(automatically|auto)[- ]generated|This file is generated", re.I
)

# ---------------------------------------------------------------------------
# Protected content — never a finding (except SECRET, which overrides everything)
# ---------------------------------------------------------------------------

# Pragmas change compiler, linter, or build behavior. They are code wearing a comment's
# syntax; deleting one is a functional change, so they are exempt from every rule.
PRAGMA_RE = re.compile(
    r"^(eslint[-\s]|prettier-ignore|@ts-|ts-ignore|ts-expect-error|tslint:|biome-ignore|"
    r"deno-lint-ignore|noqa|type:\s*ignore|pylint:|flake8:|mypy:|fmt:\s*(on|off)|"
    r"pragma[:\s]|shellcheck\s|rubocop:|nolint|lint:ignore|golint|go:|\+build|NOLINT|"
    r"clang-format\s|istanbul\s|c8\s|v8\s|coverage:|jscpd:|swiftlint:|phpcs:|phpstan-|"
    r"psalm-|phan-|codingStandardsIgnore|@codeCoverageIgnore|-\*-\s*coding|"
    r"frozen_string_literal|:nodoc:|@SuppressWarnings|region\b|endregion\b|MARK:|"
    r"namespace\s|webpack|vite-ignore|@jsx|@flow|@vue|sourceMappingURL|"
    r"eslint-disable|@preserve|@license|@ts-nocheck)", re.I
)
RAW_PRAGMA_PREFIXES = ("#!", "/*!", "<!--[if", "/*+", "//go:", "//!", "#include")
LICENCE_RE = re.compile(r"copyright|licen[cs]e|SPDX-License-Identifier|all rights reserved",
                        re.I)

# ---------------------------------------------------------------------------
# Rule patterns
# ---------------------------------------------------------------------------

TODO_RE = re.compile(r"\b(TODO|FIXME|HACK|XXX|BUG|KLUDGE|REFACTOR|OPTIMIZE|DEPRECATED)\b")
TODO_OK_RE = re.compile(r"\b(TODO|FIXME|HACK|XXX|BUG|KLUDGE|REFACTOR|OPTIMIZE)\("
                        r"[#A-Za-z0-9_/.-]+\)\s*:\s*\S")

BANNER_RE = re.compile(r"^[\s=\-*#/_~+.<>|!\\]{5,}$")
SLASH_BANNER_RE = re.compile(r"^/{4,}")
# A section label wrapped in divider runs — `---- Helpers -------` — is still banner art.
BANNER_TEXT_RE = re.compile(r"^[-=*#/_~+]{3,}[^-=*#/_~+]+[-=*#/_~+]{3,}\s*$"
                            r"|^[-=*#/_~+]{4,}\s*\w")
# Lines allowed above a file header: they open the file, they are not its first statement.
PROLOGUE_RE = re.compile(r"^\s*(#!|<\?php|<\?xml|['\"]use (strict|client|server)['\"];?\s*$"
                         r"|from __future__ import|#\s*-\*-\s*coding)")

CHANGELOG_RE = re.compile(
    r"\b(modified|updated|changed|revised|edited|refactored|added|created|fixed|patched)\b"
    r"[^.\n]{0,30}\b(by|on)\b", re.I)
DATE_RE = re.compile(r"\b(19|20)\d{2}[-/]\d{1,2}[-/]\d{1,2}\b|\b\d{1,2}[-/]\d{1,2}[-/]\d{2,4}\b")
VERSION_LOG_RE = re.compile(r"^\s*v?\d+(\.\d+)+\s*[:\-–]\s*\S", re.I)
CHANGELOG_EXEMPT_RE = re.compile(r"@since|@version|@date|@copyright|@author|copyright|SPDX",
                                 re.I)

GENERATED_RE = re.compile(
    r"\b(generated|written|created|produced|suggested|authored|refactored)\b[^.\n]{0,25}"
    r"\b(by|with|using)\b[^.\n]{0,25}"
    r"\b(ai|a\.i\.|gpt|chat ?gpt|claude|copilot|codex|cursor|gemini|llm|language model|"
    r"assistant|bot)\b", re.I)
AI_MARK_RE = re.compile(r"\bAI[-\s]generated\b", re.I)
FILLER_RE = re.compile(
    r"^(here'?s?\s+(is\s+)?(the|a|an|your)\b|note[:,]\s+this\s+is\s+(a|an|just)\b|"
    r"this\s+is\s+(a|an)\s+(simple|basic)\s+(example|implementation)\b|"
    r"(as|per)\s+(requested|asked)\b|i\s+(have\s+)?(added|created|implemented|refactored)\b)",
    re.I)

CODE_SIGNALS = (
    re.compile(r"[;{}]\s*$"),
    re.compile(r"^\s*(if|for|while|return|switch|case|else|elif|try|except|catch|finally|"
               r"function|def|class|const|let|var|import|from|export|public|private|"
               r"protected|new|await|async|foreach|echo|print|require|include|use|package|"
               r"fn|impl|struct|match|end|do|then|puts|console\.)\b"),
    # No space before `(` — `notify(user)` is a call, `defect (see below)` is prose.
    re.compile(r"\w+\([^()]*\)\s*[;{,.]?\s*$"),
    re.compile(r"^\s*</?[a-zA-Z][\w-]*[\s/>]"),
    re.compile(r"^\s*[\w$.]+\([^()]*\)\s*\.\s*\w"),
)
ASSIGN_RE = re.compile(r"^\s*([\w$.\[\]'\"]+)\s*(?:=|\+=|-=|\|\|=|\?\?=)\s*(.*)$")
POSITIONAL_RE = re.compile(r"^\$[\d@*#]")
# A bullet is prose, whatever punctuation it ends with.
LIST_ITEM_RE = re.compile(r"^\s*([-*+•]|\d+[.)])\s")
# A value enumeration documents allowed inputs; it is not narration of the code.
ENUM_RE = re.compile(r"^[^A-Za-z]|[|→]|->")
DEAD_EXEMPT_RE = re.compile(
    r"\b(TODO|FIXME|NOTE|HACK|XXX|e\.g\.|i\.e\.|example|Example|uncomment|Uncomment|"
    r"usage|Usage|for instance|such as|optional|Optional|default:|Default:)\b")

NARRATION_VERBS = {
    "loop", "iterate", "check", "call", "create", "initialize", "initialise", "declare",
    "define", "increment", "decrement", "assign", "add", "remove", "delete", "update",
    "print", "log", "import", "export", "return", "set", "get", "instantiate", "construct",
    "start", "stop", "close", "open", "convert", "cast", "parse", "build", "make", "run",
}
STOPWORDS = {
    "the", "a", "an", "this", "that", "these", "those", "and", "or", "but", "of", "to",
    "for", "in", "on", "at", "by", "with", "from", "into", "is", "are", "was", "were",
    "be", "been", "being", "it", "its", "we", "our", "you", "your", "they", "them",
    "then", "than", "here", "there", "all", "any", "not", "no", "if", "so", "as", "up",
    "out", "each", "which", "when", "where", "will", "can", "may", "must", "should",
}

SECRET_PATTERNS = (
    ("private key", re.compile(r"-----BEGIN [A-Z ]*PRIVATE KEY-----")),
    ("aws access key", re.compile(r"\bAKIA[0-9A-Z]{16}\b")),
    ("stripe key", re.compile(r"\bsk_(live|test)_[A-Za-z0-9]{10,}")),
    ("github token", re.compile(r"\bgh[pousr]_[A-Za-z0-9]{20,}")),
    ("slack token", re.compile(r"\bxox[baprs]-[A-Za-z0-9-]{10,}")),
    ("google api key", re.compile(r"\bAIza[0-9A-Za-z_\-]{35}\b")),
    ("bearer token", re.compile(r"\bBearer\s+[A-Za-z0-9._\-]{20,}")),
    ("jwt", re.compile(r"\beyJ[A-Za-z0-9_\-]{10,}\.[A-Za-z0-9_\-]{10,}\.")),
    ("credential in url", re.compile(r"\b\w+://[^\s:@/]+:[^\s:@/]{3,}@")),
    ("credential literal", re.compile(
        r"\b(password|passwd|pwd|secret|api[_-]?key|apikey|access[_-]?token|"
        r"client[_-]?secret|private[_-]?key)\b\s*[:=]\s*[\"']?[^\s\"'<>{}$]{6,}", re.I)),
)
# Placeholders and env lookups are documentation, not leaked credentials.
SECRET_FALSE_POSITIVE_RE = re.compile(
    r"env|getenv|process\.|os\.environ|secrets?\.|vault|\bxxx+\b|\*{3,}|redacted|placeholder|"
    r"your[_-]|<[^>]+>|\{\{|\$\{|example\.com|changeme|todo|none|null|\bhere\b", re.I)

DECL_RE = re.compile(
    r"^\s*(@|#\[)|"
    r"^\s*(export\s+)?(default\s+)?(declare\s+)?(public|private|protected|internal|static|"
    r"final|abstract|sealed|override|open|async|const|let|var|func|function|def|class|"
    r"interface|type|enum|struct|impl|trait|fn|package|module|namespace|val|object|record|"
    r"data|extension|protocol|template|inline|virtual|extern|pub)\b|"
    r"^\s*[\w$]+\s*[:=]\s*(async\s+)?(function\b|\([^)]*\)\s*(=>|:))|"
    r"^\s*[\w<>\[\],. *&]+\s+[\w$]+\s*\([^;]*\)\s*(const\s*)?\{?\s*$"
)

# Canonical docblock tag order. Unknown tags carry no rank and are never judged.
TAG_RANK = {
    "remarks": 10, "description": 10, "desc": 10, "summary": 10, "brief": 10, "detail": 10,
    "template": 15, "typeparam": 15, "generic": 15,
    "param": 20, "parameter": 20, "arg": 20, "argument": 20, "arguments": 20, "params": 20,
    "property": 22, "prop": 22, "var": 22, "type": 22,
    "return": 30, "returns": 30, "yield": 30, "yields": 30,
    "throw": 40, "throws": 40, "exception": 40, "raise": 40, "raises": 40, "error": 40,
    "deprecated": 50,
    "since": 55, "version": 55,
    "see": 60, "link": 60, "example": 60, "examples": 60, "sample": 60, "usage": 60,
    "author": 70, "copyright": 70, "license": 70, "licence": 70,
    "public": 90, "private": 90, "protected": 90, "internal": 90, "beta": 90, "alpha": 90,
    "experimental": 90, "sealed": 90, "override": 90, "readonly": 90, "virtual": 90,
    "eventproperty": 90, "packagedocumentation": 90,
}
TAG_LINE_RE = re.compile(r"^\s*[*#/]*\s*@([A-Za-z][\w-]*)\b(.*)$")
BARE_TAG_RE = re.compile(r"^\s*[*#/]*\s*@[A-Za-z][\w-]*(\s+\{[^}]*\})?"
                         r"(\s+[$]?[\w.\[\]|<>,]+)?\s*$")

DISPOSITION = {
    "DUP": "DELETE", "LEN": "SHORTEN", "ORD": "REORDER", "POS": "REPOSITION",
    "TODO": "ESCALATE", "DEAD": "DELETE", "BANNER": "DELETE", "CHANGELOG": "DELETE",
    "GENERATED": "DELETE", "EMPTY": "DELETE", "SECRET": "ESCALATE",
}
RULE_HELP = {
    "DUP": "comment restates the code beside it",
    "LEN": "inline comment over the line cap",
    "ORD": "docblock tags out of canonical order",
    "POS": "comment detached from, or trailing, its subject",
    "TODO": "marker without a tracked issue reference",
    "DEAD": "commented-out code",
    "BANNER": "divider or section art",
    "CHANGELOG": "version history that belongs in git",
    "GENERATED": "assistant attribution or filler",
    "EMPTY": "docblock with no information beyond the signature",
    "SECRET": "possible credential in a comment",
}
ALL_RULES = list(DISPOSITION)


# ---------------------------------------------------------------------------
# Comment extraction
# ---------------------------------------------------------------------------


def _line_index(text):
    starts = [0]
    for m in re.finditer("\n", text):
        starts.append(m.end())
    return starts


def _pos(starts, off):
    ln = bisect_right(starts, off)
    return ln, off - starts[ln - 1]


def _regex_allowed(text, i):
    """True when a `/` at offset i starts a JS regex literal rather than division."""
    j = i - 1
    while j >= 0 and text[j] in " \t\r\n":
        j -= 1
    if j < 0:
        return True
    if text[j] in "=(,:[!&|?{};+-*%~^<>":
        return True
    k = j
    while k >= 0 and (text[k].isalnum() or text[k] == "_"):
        k -= 1
    return text[k + 1:j + 1] in {
        "return", "typeof", "instanceof", "in", "of", "new", "delete", "void", "throw",
        "case", "do", "else", "yield", "await",
    }


def _skip_string(text, i, prof):
    """If a string literal starts at i, return the offset just past it, else None."""
    n = len(text)
    for opener, closer, escapes in prof.strings:
        if text.startswith(opener, i):
            j = i + len(opener)
            while j < n:
                c = text[j]
                if escapes and c == "\\":
                    j += 2
                    continue
                if c == "\n" and opener in ("'", '"'):
                    return j          # unterminated line string; resync at the newline
                if text.startswith(closer, j):
                    return j + len(closer)
                j += 1
            return n
    if prof.template and text[i] == "`":
        j, depth = i + 1, 0
        while j < n:
            c = text[j]
            if c == "\\":
                j += 2
                continue
            if text.startswith("${", j):
                depth += 1
                j += 2
                continue
            if c == "}" and depth:
                depth -= 1
            elif c == "`" and not depth:
                return j + 1
            j += 1
        return n
    return None


def _skip_regex(text, i):
    n, j, in_class = len(text), i + 1, False
    while j < n:
        c = text[j]
        if c == "\\":
            j += 2
            continue
        if c == "\n":
            return None
        if c == "[":
            in_class = True
        elif c == "]":
            in_class = False
        elif c == "/" and not in_class:
            j += 1
            while j < n and text[j].isalpha():
                j += 1
            return j
        j += 1
    return None


def extract_generic(text, prof):
    """Comment spans as (start_off, end_off, kind), string- and regex-aware."""
    spans, n, i = [], len(text), 0
    while i < n:
        c = text[i]
        if c in " \t\r\n":
            i += 1
            continue
        s = _skip_string(text, i, prof)
        if s is not None:
            i = s
            continue
        hit = None
        for opener, closer in prof.block:
            if text.startswith(opener, i):
                end = text.find(closer, i + len(opener))
                end = n if end == -1 else end + len(closer)
                hit = (i, end, "block")
                break
        if hit:
            spans.append(hit)
            i = hit[1]
            continue
        for marker in prof.line:
            if text.startswith(marker, i):
                end = text.find("\n", i)
                end = n if end == -1 else end
                hit = (i, end, "line")
                break
        if hit:
            spans.append(hit)
            i = hit[1]
            continue
        if prof.regex and c == "/" and _regex_allowed(text, i):
            r = _skip_regex(text, i)
            if r:
                i = r
                continue
        i += 1
    return spans


def extract_python(text):
    """Python comments and docstrings via tokenize, which never misreads a string."""
    out = []
    try:
        toks = list(tokenize.generate_tokens(io.StringIO(text).readline))
    except (tokenize.TokenError, IndentationError, SyntaxError, ValueError):
        return None
    at_stmt_start = True
    for tok in toks:
        if tok.type == tokenize.COMMENT:
            out.append((tok.start, tok.end, "line", tok.string))
        elif tok.type == tokenize.STRING:
            if at_stmt_start and tok.string.lstrip("rRbBuUfF")[:3] in ('"""', "'''"):
                out.append((tok.start, tok.end, "docstring", tok.string))
            at_stmt_start = False
        elif tok.type in (tokenize.NEWLINE, tokenize.NL, tokenize.INDENT,
                          tokenize.DEDENT, tokenize.ENCODING):
            at_stmt_start = True
        elif tok.type != tokenize.COMMENT:
            at_stmt_start = False
    return out


# ---------------------------------------------------------------------------
# Units — a comment plus the context needed to judge it
# ---------------------------------------------------------------------------


class Unit:
    def __init__(self, start, end, kind, raw, lines, indent, trailing):
        self.start = start          # 1-based first line
        self.end = end              # 1-based last line
        self.kind = kind            # line | block | docstring
        self.raw = raw
        self.lines = lines          # marker-stripped content, one entry per source line
        self.indent = indent
        self.trailing = trailing    # code precedes the comment on its first line
        self.own_code = ""          # that preceding code — the subject of a trailing comment
        self.next_code = None       # (lineno, text) of the next real code line
        self.blank_before_code = 0
        self.protected = False
        self.file_header = False    # states the file's purpose; length and gap are expected

    @property
    def height(self):
        return self.end - self.start + 1

    @property
    def text(self):
        return " ".join(x for x in self.lines if x).strip()

    @property
    def is_doc(self):
        r = self.raw.lstrip()
        return (self.kind == "docstring" or r.startswith("/**") or r.startswith("///")
                or r.startswith("//!") or r.startswith("/*!"))


def _strip_markers(raw, kind):
    lines = raw.split("\n")
    out = []
    for idx, ln in enumerate(lines):
        s = ln.strip()
        if kind == "block":
            if idx == 0:
                s = re.sub(r"^(/\*+!?|<!--)", "", s)
            if idx == len(lines) - 1:
                s = re.sub(r"(\*+/|-->)\s*$", "", s)
            s = re.sub(r"^\*+\s?", "", s)
        elif kind == "docstring":
            s = re.sub(r"^[rRbBuUfF]*(\"\"\"|''')", "", s)
            s = re.sub(r"(\"\"\"|''')\s*$", "", s)
        else:
            s = re.sub(r"^(//+!?|#+|--+)\s?", "", s)
        out.append(s.strip())
    return out


def build_units(path, text):
    ext = os.path.splitext(path)[1].lower()
    base = os.path.basename(path)
    lines = text.split("\n")
    raw_spans = []

    if ext in (".py", ".pyi"):
        toks = extract_python(text)
        if toks is not None:
            for (sr, sc), (er, ec), kind, s in toks:
                raw_spans.append((sr, sc, er, s, kind))
    if not raw_spans:
        prof = EXT_PROFILE.get(ext) or NAME_PROFILE.get(base)
        if prof is None:
            return None
        starts = _line_index(text)
        for so, eo, kind in extract_generic(text, prof):
            sr, sc = _pos(starts, so)
            er, _ = _pos(starts, max(so, eo - 1))
            raw_spans.append((sr, sc, er, text[so:eo], kind))

    raw_spans.sort(key=lambda s: (s[0], s[1]))
    units = []
    for sr, sc, er, raw, kind in raw_spans:
        before = lines[sr - 1][:sc] if sr - 1 < len(lines) else ""
        trailing = bool(before.strip())
        indent = len(before) - len(before.lstrip()) if not trailing else 0
        u = Unit(sr, er, kind, raw, _strip_markers(raw, kind), indent, trailing)
        u.own_code = before.strip()
        # Consecutive line comments at the same indent read as one paragraph; judge them
        # as one, or a five-line block gets reported five times.
        if (units and kind == "line" and not trailing and units[-1].kind == "line"
                and not units[-1].trailing and units[-1].end == sr - 1
                and units[-1].indent == indent):
            prev = units[-1]
            prev.end = er
            prev.raw += "\n" + raw
            prev.lines += u.lines
            continue
        units.append(u)

    for pos, u in enumerate(units):
        # A header is the first comment with no real code above it — only blanks, a shebang,
        # or a file-opening tag. A comment merely near the top is not a header.
        u.file_header = pos == 0 and not u.trailing and all(
            not lines[i].strip() or PROLOGUE_RE.match(lines[i])
            for i in range(u.start - 1))
        blanks = 0
        for ln in range(u.end, len(lines)):
            body = lines[ln].strip()
            if not body:
                blanks += 1
                continue
            u.next_code = (ln + 1, lines[ln])
            u.blank_before_code = blanks
            break
        head = u.text
        u.protected = (
            bool(PRAGMA_RE.match(head))
            or u.raw.lstrip().startswith(RAW_PRAGMA_PREFIXES)
            or (u.start <= 6 and bool(LICENCE_RE.search(u.raw)))
        )
    return units


# ---------------------------------------------------------------------------
# Rules
# ---------------------------------------------------------------------------


def _words(s):
    out = []
    for part in re.findall(r"[A-Za-z][A-Za-z0-9]*", s):
        out.extend(re.findall(r"[A-Z]+(?![a-z])|[A-Z][a-z0-9]*|[a-z0-9]+", part))
    res = []
    for w in out:
        w = w.lower()
        if len(w) <= 2 or w in STOPWORDS:
            continue
        res.append(w[:-1] if w.endswith("s") and len(w) > 3 else w)
    return res


def _assignment(line):
    """True for a real assignment, false for prose shaped like one.

    `# $1 = added+removed line count` documents a shell parameter and `null = absent`
    documents a return value; neither is commented-out code.
    """
    m = ASSIGN_RE.match(line)
    if not m:
        return False
    lhs, rhs = m.group(1), m.group(2).strip()
    if POSITIONAL_RE.match(lhs) or not rhs:
        return False
    return bool(re.search(r"[(){}\[\];\"'`]", rhs) or " " not in rhs)


def _code_like(line):
    return sum(1 for r in CODE_SIGNALS if r.search(line)) + (1 if _assignment(line) else 0)


def _tags(unit):
    found = []
    for ln in unit.lines:
        m = TAG_LINE_RE.match(ln)
        if m:
            found.append((m.group(1).lower(), ln))
    return found


def check_unit(unit, cap):
    findings = []

    def add(rule, line, excerpt, why, disposition=None):
        findings.append({
            "rule": rule, "line": line, "end_line": unit.end,
            "disposition": disposition or DISPOSITION[rule],
            "excerpt": excerpt[:160], "why": why,
        })

    # SECRET first: it applies even to protected units, and it never echoes the value.
    for label, pat in SECRET_PATTERNS:
        for idx, ln in enumerate(unit.lines):
            if pat.search(ln) and not SECRET_FALSE_POSITIVE_RE.search(ln):
                add("SECRET", unit.start + idx, "<redacted>",
                    "possible %s in a comment; verify and rotate, do not just delete" % label)
                break
    if unit.protected:
        return findings

    body = unit.text
    if not body and unit.is_doc:
        add("EMPTY", unit.start, unit.raw.strip().split("\n")[0], "docblock has no content")
        return findings
    if not body:
        return findings

    for idx, ln in enumerate(unit.lines):
        if not ln:
            continue
        if TODO_RE.search(ln) and not TODO_OK_RE.search(ln):
            add("TODO", unit.start + idx, ln, "no tracked issue reference; do not invent one")
            break

    for idx, ln in enumerate(unit.lines):
        if GENERATED_RE.search(ln) or AI_MARK_RE.search(ln) or FILLER_RE.match(ln):
            add("GENERATED", unit.start + idx, ln, "artifact of generation, not of the program")
            break

    banner = False
    if unit.height <= 6:
        for idx, ln in enumerate(unit.lines):
            raw_ln = unit.raw.split("\n")[idx].strip() if idx < unit.height else ""
            pure = (ln and BANNER_RE.match(ln)) or SLASH_BANNER_RE.match(raw_ln)
            labelled = ln and BANNER_TEXT_RE.match(ln)
            if pure:
                add("BANNER", unit.start + idx, raw_ln or ln, "carries no information")
            elif labelled:
                # The label is information; only the divider runs around it are art.
                add("BANNER", unit.start + idx, ln,
                    "strip the divider runs and keep the label, or delete if the label "
                    "only restates the code below", "SHORTEN")
            if pure or labelled:
                banner = True
                break

    for idx, ln in enumerate(unit.lines):
        if not ln or CHANGELOG_EXEMPT_RE.search(ln):
            continue
        if CHANGELOG_RE.search(ln) or VERSION_LOG_RE.match(ln) or DATE_RE.search(ln):
            add("CHANGELOG", unit.start + idx, ln,
                "git records this; keep only an issue link, if any")
            break

    # A docblock is documentation and a trailing note annotates live code — neither is ever
    # a commented-out block, and treating them as one misreads prose that contains parens.
    if not DEAD_EXEMPT_RE.search(body) and not unit.is_doc and not unit.trailing:
        hits = [(i, ln) for i, ln in enumerate(unit.lines)
                if ln and not LIST_ITEM_RE.match(ln) and _code_like(ln)]
        strong = [x for x in hits if re.search(r"[;{}]\s*$", x[1]) or _assignment(x[1])]
        if len(hits) >= 2 or (len(hits) == 1 and strong):
            add("DEAD", unit.start + hits[0][0], hits[0][1], "git already stores this")

    tags = _tags(unit)
    if tags:
        ranks = [(TAG_RANK[t], t) for t, _ in tags if t in TAG_RANK]
        for a, b in zip(ranks, ranks[1:]):
            if b[0] < a[0]:
                add("ORD", unit.start, "@%s before @%s" % (a[1], b[1]),
                    "canonical order is summary, @param, @return, @throws, @deprecated, @see")
                break
        first_tag = next(i for i, ln in enumerate(unit.lines) if TAG_LINE_RE.match(ln))
        if any(unit.lines[i] and not TAG_LINE_RE.match(unit.lines[i])
               and not unit.lines[i].startswith(("-", "*", "|", "```", "  "))
               for i in range(first_tag + 1, len(unit.lines))):
            add("ORD", unit.start + first_tag, unit.lines[first_tag],
                "prose stranded after the first block tag")
        if unit.is_doc and all(BARE_TAG_RE.match(ln) for ln in unit.lines if ln):
            add("EMPTY", unit.start, tags[0][1], "tags add nothing beyond the signature")

    # A file header states the file's purpose. It is expected to be long and to sit a blank
    # line above the first declaration, so the length and placement rules do not apply.
    # Banner art is already reported as BANNER; its placement is not a second finding.
    if not unit.file_header and not banner:
        if unit.trailing and (unit.height > 1 or len(body) > LONG_TRAILING_CHARS):
            add("POS", unit.start, body, "explanation trailing a line of code; move it above")
        elif (not unit.trailing and unit.blank_before_code >= 1 and unit.next_code
                and DECL_RE.match(unit.next_code[1])):
            add("POS", unit.start, body,
                "blank line detaches this from its declaration; doc tools drop it")

        if not unit.is_doc and not unit.trailing and unit.height > cap:
            add("LEN", unit.start, body,
                "%d lines; cap is %d — compress to the load-bearing sentence or move it into "
                "the docblock" % (unit.height, cap))

    # The subject of a trailing comment is the code it sits on, not the next line.
    subject = unit.own_code if unit.trailing else (
        unit.next_code[1] if unit.next_code and unit.blank_before_code == 0 else "")
    # A comment attached to a declaration is documentation, and naming the symbol is the
    # convention — `// Copy copies from src to dst.` is required Go doc form, not a duplicate.
    documents_decl = not unit.trailing and subject and DECL_RE.match(subject)
    if (unit.height == 1 and not unit.is_doc and subject and not documents_decl
            and not ENUM_RE.search(body)):
        cw = _words(body)
        if cw and len(cw) <= 6:
            code_w = set(_words(subject))
            shared = [w for w in cw if w in code_w]
            ratio = len(shared) / len(cw)
            if shared and (ratio >= 0.5 or (cw[0] in NARRATION_VERBS and ratio >= 0.3)):
                add("DUP", unit.start, body, "restates `%s`" % subject.strip()[:60])
    return findings


# ---------------------------------------------------------------------------
# Files
# ---------------------------------------------------------------------------


def discover(paths, root):
    files, seen = [], set()

    def want(p):
        base = os.path.basename(p)
        if SKIP_FILE_RE.search(base):
            return False
        ext = os.path.splitext(p)[1].lower()
        return ext in EXT_PROFILE or base in NAME_PROFILE

    for p in paths:
        if os.path.isfile(p):
            if want(p) and p not in seen:
                seen.add(p)
                files.append(p)
            continue
        listed = None
        try:
            out = subprocess.run(["git", "-C", p, "ls-files", "-z"], capture_output=True,
                                 text=True, timeout=60)
            if out.returncode == 0:
                listed = [os.path.join(p, f) for f in out.stdout.split("\0") if f]
        except (OSError, subprocess.SubprocessError):
            listed = None
        if listed is None:
            listed = []
            for dirpath, dirnames, filenames in os.walk(p):
                dirnames[:] = [d for d in dirnames if d not in SKIP_DIRS
                               and not d.startswith(".")]
                listed += [os.path.join(dirpath, f) for f in filenames]
        for f in listed:
            rel = os.path.relpath(f, root)
            if any(part in SKIP_DIRS for part in rel.split(os.sep)):
                continue
            if want(f) and f not in seen:
                seen.add(f)
                files.append(f)
    return sorted(files)


def scan_file(path, cap, rules):
    try:
        if os.path.getsize(path) > MAX_FILE_BYTES:
            return None, "too large"
        with open(path, "r", encoding="utf-8", errors="strict") as fh:
            text = fh.read()
    except (OSError, UnicodeDecodeError):
        return None, "unreadable"
    head = "\n".join(text.split("\n", 40)[:40])
    if GENERATED_FILE_RE.search(head):
        return None, "generated"
    if any(len(ln) > 500 for ln in text.split("\n")[:50]):
        return None, "minified"
    units = build_units(path, text)
    if units is None:
        return None, "unsupported"
    findings = []
    for u in units:
        findings += [f for f in check_unit(u, cap) if f["rule"] in rules]
    findings.sort(key=lambda f: (f["line"], f["rule"]))
    return {"comments": len(units), "findings": findings}, None


# ---------------------------------------------------------------------------
# Reporting
# ---------------------------------------------------------------------------


def render(results, totals, stats, root, summary_only, max_per_file):
    out = []
    if not summary_only:
        for path, res in results:
            if not res["findings"]:
                continue
            out.append(os.path.relpath(path, root))
            shown = res["findings"][:max_per_file]
            for f in shown:
                out.append("  %5d  %-9s %-11s %s"
                           % (f["line"], f["rule"], f["disposition"], f["excerpt"]))
            if len(res["findings"]) > len(shown):
                out.append("  ... %d more in this file"
                           % (len(res["findings"]) - len(shown)))
            out.append("")
    out.append("── comment scan " + "─" * 44)
    out.append("  files scanned       %d" % stats["files"])
    out.append("  files with findings %d" % stats["files_with_findings"])
    out.append("  comments            %d" % stats["comments"])
    out.append("  findings            %d" % sum(totals.values()))
    if stats["skipped"]:
        out.append("  skipped             %d (%s)"
                   % (sum(stats["skipped"].values()),
                      ", ".join("%s: %d" % kv for kv in sorted(stats["skipped"].items()))))
    if totals:
        out.append("")
        for rule, n in sorted(totals.items(), key=lambda kv: (-kv[1], kv[0])):
            out.append("  %-10s %5d  %-11s %s"
                       % (rule, n, DISPOSITION[rule], RULE_HELP[rule]))
    out.append("")
    out.append("  Candidates, not verdicts — open each file and decide.")
    out.append("  Rule IDs map to references/ANTIPATTERNS.md.")
    return "\n".join(out)


# ---------------------------------------------------------------------------
# Self-test
# ---------------------------------------------------------------------------

FIXTURES = [
    ("dup.js", "// increment the counter\ncounter++;\n", {"DUP"}, set()),
    ("banner.js", "// ==========================\n// HELPERS\n// ==========================\n"
                  "function a() {}\n", {"BANNER"}, set()),
    ("todo.js", "// TODO fix this later\nconst a = 1;\n", {"TODO"}, set()),
    ("todo_ok.js", "// TODO(#1234): switch to the batched endpoint.\nconst a = 1;\n",
     set(), {"TODO"}),
    ("dead.py", "# old_total = sum(x.price for x in items)\n"
                "# if old_total > threshold:\n#     notify(user)\ntotal = 1\n",
     {"DEAD"}, set()),
    ("ord.php", "<?php\n/**\n * @throws AuthException\n * @return User\n * @param int $id\n */\n"
                "function f($id) {}\n", {"ORD"}, set()),
    ("changelog.php", "<?php\n// Modified by A. Dev on 2024-03-11 to add caching\n$a = 1;\n",
     {"CHANGELOG"}, set()),
    ("generated.py", "# Generated by an AI assistant\nx = 1\n", {"GENERATED"}, set()),
    ("pos_go.go", "package main\n\nimport \"io\"\n\n// Copy copies from src to dst.\n\n"
                  "func Copy(dst io.Writer) {}\n", {"POS"}, set()),
    ("len.py", "def f():\n    # one\n    # two\n    # three\n    # four\n    # five\n"
               "    return 1\n", {"LEN"}, set()),
    ("secret.js", "// prod key: sk_live_51H8xQ2abcdefghijkl\nconst a = 1;\n", {"SECRET"}, set()),
    ("trailing_dup.js", "counter++; // increment the counter\n", {"DUP"}, set()),
    # Naming the symbol is required Go doc form, not a restatement.
    ("godoc.go", "package util\n\n// Copy copies from src to dst.\n"
                 "func Copy(dst, src string) error { return nil }\n", set(), {"DUP"}),
    ("banner_text.js", "const a = 1;\n\n"
                       "// ---- Skill discovery ----------------------------------\n\n"
                       "function discover() {}\n", {"BANNER"}, {"POS"}),
    # A prologue directive above the header does not stop it being the header.
    ("prologue.js", "#!/usr/bin/env node\n\"use strict\";\n\n/**\n * The installer.\n *\n"
                    " * Copies skill directories into the relevant skills folder for the\n"
                    " * selected client and scope.\n */\n\nconst fs = require(\"fs\");\n",
     set(), {"LEN", "POS"}),
    # Shell parameter documentation is not commented-out code.
    ("params.sh", "hint() {\n  # $1 = file, $2 = pattern, $3 = label\n  grep -q \"$2\" \"$1\"\n}\n",
     set(), {"DEAD"}),
    ("params2.sh", "dest_base() {\n"
                   "  # $1 = claude|codex|opencode  (OpenCode differs by scope)\n"
                   "  local client=\"$1\"\n}\n", set(), {"DEAD"}),
    # A file header is expected to be long and to sit a blank line above the first
    # declaration; neither is a defect.
    ("header.mjs", "// Redirect-aware fetch helpers built on native fetch (Node 18+).\n//\n"
                   "// Captures the redirect chain, final status, headers, and body so\n"
                   "// checks can reason about HTTP behaviour.\n\nconst UA = \"x\";\n",
     set(), {"LEN", "POS"}),
    # Prose containing parentheses or bullets is not commented-out code.
    ("docbullet.mjs", "/**\n * Build one finding. `status`:\n"
                      " *   - \"fail\" → a real defect (penalises the score by severity)\n"
                      " *   - \"info\" → could not be measured (never penalises)\n */\n"
                      "export function finding() {}\n", set(), {"DEAD"}),
    # A trailing note annotates the line it sits on, and a value list is documentation.
    ("enum.mjs", "const o = {\n  scope: \"page\",        // \"page\" | \"site\"\n};\n",
     set(), {"DUP", "DEAD"}),
    ("trailing_note.mjs", "const a = {\n  alt: null, // null = attribute absent\n};\n",
     set(), {"DUP", "DEAD"}),
    # Protected content must never be flagged.
    ("pragma.js", "// eslint-disable-next-line no-console\nconsole.log(1);\n", set(), {"DUP", "DEAD"}),
    ("pragma.py", "x = 1  # noqa: E501\n", set(), {"POS", "DUP"}),
    ("build.go", "//go:build linux\n\npackage main\n", set(), {"POS", "DEAD", "BANNER"}),
    ("shebang.sh", "#!/usr/bin/env bash\nset -e\n", set(), {"DUP", "DEAD", "BANNER"}),
    ("licence.js", "/* Copyright 2026 Example Inc. Licensed under MIT. */\nconst a = 1;\n",
     set(), {"CHANGELOG", "LEN", "DEAD"}),
    # Strings that look like comments must not be parsed as comments.
    ("string.js", 'const url = "https://example.com//path";\nconst re = /https:\\/\\//;\n',
     set(), ALL_RULES),
    ("string.py", 'url = "# not a comment"\n', set(), ALL_RULES),
    # Good comments must stay quiet.
    ("good.js", "// Upstream 502s under load; 3 retries covers the observed p99.\n"
                "const retries = 3;\n", set(), ALL_RULES),
    ("good.php", "<?php\n/**\n * Loads the billing owner for a tenant.\n *\n"
                 " * @param  int $tenantId\n * @return User\n * @throws AuthException\n */\n"
                 "function f($tenantId) {}\n", set(), ALL_RULES),
]


def self_test():
    import tempfile
    failures = []
    with tempfile.TemporaryDirectory() as tmp:
        for name, src, expect, forbid in FIXTURES:
            path = os.path.join(tmp, name)
            with open(path, "w", encoding="utf-8") as fh:
                fh.write(src)
            res, why = scan_file(path, DEFAULT_INLINE_CAP, set(ALL_RULES))
            if res is None:
                failures.append("%s: not scanned (%s)" % (name, why))
                continue
            got = {f["rule"] for f in res["findings"]}
            missing = expect - got
            leaked = got & set(forbid)
            if missing:
                failures.append("%s: expected %s, got %s" % (name, sorted(missing), sorted(got)))
            if leaked:
                failures.append("%s: false positive %s" % (name, sorted(leaked)))
            for f in res["findings"]:
                if f["rule"] == "SECRET" and f["excerpt"] != "<redacted>":
                    failures.append("%s: SECRET finding echoed the value" % name)

    for f in failures:
        print("FAIL  " + f, file=sys.stderr)
    if failures:
        print("\n%d/%d fixtures failed" % (len(failures), len(FIXTURES)), file=sys.stderr)
        return 1
    print("scan-comments self-test: %d fixtures passed" % len(FIXTURES))
    return 0


# ---------------------------------------------------------------------------


def main(argv):
    ap = argparse.ArgumentParser(add_help=True, description=__doc__.split("\n")[0])
    ap.add_argument("paths", nargs="*", default=None,
                    help="files or directories to scan (default: repository root)")
    ap.add_argument("--json", action="store_true", help="emit JSON instead of a table")
    ap.add_argument("--cap", type=int, default=DEFAULT_INLINE_CAP,
                    help="inline comment line cap (default %d)" % DEFAULT_INLINE_CAP)
    ap.add_argument("--rules", default="", help="comma-separated rule IDs to report")
    ap.add_argument("--summary-only", action="store_true", help="totals only, no per-file list")
    ap.add_argument("--max-per-file", type=int, default=25, help="findings shown per file")
    ap.add_argument("--self-test", action="store_true", help="run the built-in fixtures")
    args = ap.parse_args(argv)

    if args.self_test:
        return self_test()

    rules = set(ALL_RULES)
    if args.rules:
        asked = {r.strip().upper() for r in args.rules.split(",") if r.strip()}
        unknown = asked - rules
        if unknown:
            print("unknown rule(s): %s" % ", ".join(sorted(unknown)), file=sys.stderr)
            return 0
        rules = asked

    paths = args.paths or ["."]
    root = os.getcwd()
    try:
        top = subprocess.run(["git", "rev-parse", "--show-toplevel"], capture_output=True,
                             text=True, timeout=30)
        if top.returncode == 0 and top.stdout.strip():
            root = top.stdout.strip()
    except (OSError, subprocess.SubprocessError):
        pass

    results, totals, skipped = [], {}, {}
    comments = files_with = 0
    for path in discover(paths, root):
        res, why = scan_file(path, args.cap, rules)
        if res is None:
            skipped[why] = skipped.get(why, 0) + 1
            continue
        comments += res["comments"]
        if res["findings"]:
            files_with += 1
            for f in res["findings"]:
                totals[f["rule"]] = totals.get(f["rule"], 0) + 1
        results.append((path, res))

    stats = {"files": len(results), "files_with_findings": files_with,
             "comments": comments, "skipped": skipped}

    if args.json:
        print(json.dumps({
            "version": 1,
            "root": root,
            "cap": args.cap,
            "stats": stats,
            "totals": totals,
            "dispositions": DISPOSITION,
            "files": [{"path": os.path.relpath(p, root), "comments": r["comments"],
                       "findings": r["findings"]}
                      for p, r in results if r["findings"]],
        }, indent=2))
    else:
        print(render(results, totals, stats, root, args.summary_only, args.max_per_file))
    return 0


if __name__ == "__main__":
    try:
        sys.exit(main(sys.argv[1:]))
    except KeyboardInterrupt:
        sys.exit(130)
