#!/usr/bin/env python3
"""Flag code comments whose wording is wordy, vague, robotic, or hard to read.

A repo-wide rewording pass cannot start by reading every file: the context window runs out
first. This script does the mechanical pass. It finds every English prose comment, checks its
wording against the style rules, and emits a work list the agent can act on file by file.

It judges wording only. Whether a comment should exist, how long it is, and where it sits
belong to the comment-cleanup skill. Every finding is a *candidate*, not a verdict: the
heuristics cannot read intent, so the agent must open the file and decide. Rule IDs match
references/REWRITE_RULES.md.

Usage:
    scan-prose.py [paths...] [--json] [--rules ID,ID] [--since REF] [--summary-only]
                  [--max-words N] [--grade N]
    scan-prose.py --self-test

Exits 0 for any scan result, including findings — this reports, it never gates.
--self-test exits non-zero on failure so it can be wired into a test suite.
"""

import argparse
import io
import json
import os
import re
import subprocess
import sys
import tokenize
from bisect import bisect_right

MAX_FILE_BYTES = 1_000_000
# A licence banner at the top of a file marks someone else's code; its comments are not ours
# to reword.
VENDORED_RE = re.compile(r"/\*!|@license\b|@preserve\b")
DEFAULT_MAX_WORDS = 25      # ASD-STE100 descriptive-writing sentence limit
DEFAULT_GRADE = 14          # Flesch-Kincaid grade; plain-language targets sit near 8
MIN_WORDS_FOR_GRADE = 30    # the formula is noise on shorter text

# ---------------------------------------------------------------------------
# Language profiles
# ---------------------------------------------------------------------------


class Profile:
    def __init__(self, line=(), block=(), strings=(), regex=False, template=False):
        self.line = list(line)
        self.block = list(block)
        self.strings = list(strings)
        self.regex = regex          # JS-family regex literals, so /a//b/ is not a comment
        self.template = template    # backtick strings with ${} interpolation


DQ = ('"', '"', True)
SQ = ("'", "'", True)
SQ_RAW = ("'", "'", False)          # shell/SQL single quotes do not process backslash escapes

P_JS = Profile(["//"], [("/*", "*/")], [DQ, SQ], regex=True, template=True)
P_CLIKE = Profile(["//"], [("/*", "*/")], [DQ, SQ])
P_PHP = Profile(["//", "#"], [("/*", "*/")], [DQ, SQ])
P_HASH = Profile(["#"], [], [DQ, SQ_RAW])
P_SQL = Profile(["--"], [("/*", "*/")], [SQ_RAW, DQ])
P_HTML = Profile([], [("<!--", "-->")], [])
P_CSS = Profile([], [("/*", "*/")], [DQ, SQ])
P_LUA = Profile(["--"], [("--[[", "]]")], [DQ, SQ])
P_MIXED = Profile(["//"], [("/*", "*/"), ("<!--", "-->")], [DQ, SQ], regex=True, template=True)

EXT_PROFILE = {}
for _e in (".js", ".jsx", ".mjs", ".cjs", ".ts", ".tsx", ".mts", ".cts"):
    EXT_PROFILE[_e] = P_JS
for _e in (".java", ".c", ".h", ".cc", ".cpp", ".hpp", ".cxx", ".hh", ".cs", ".go", ".rs",
           ".swift", ".kt", ".kts", ".scala", ".dart", ".groovy", ".m", ".mm", ".proto",
           ".sol", ".zig", ".json5"):
    EXT_PROFILE[_e] = P_CLIKE
for _e in (".php", ".inc"):
    EXT_PROFILE[_e] = P_PHP
for _e in (".rb", ".sh", ".bash", ".zsh", ".ksh", ".yaml", ".yml", ".toml", ".ini", ".cfg",
           ".conf", ".pl", ".pm", ".r", ".jl", ".nim", ".cr", ".tf", ".tfvars", ".ex", ".exs"):
    EXT_PROFILE[_e] = P_HASH
EXT_PROFILE[".py"] = P_HASH          # replaced by the tokenize path; kept as the fallback
EXT_PROFILE[".pyi"] = P_HASH
EXT_PROFILE[".sql"] = P_SQL
for _e in (".html", ".htm", ".xml", ".svg", ".xhtml"):
    EXT_PROFILE[_e] = P_HTML
for _e in (".css", ".scss", ".sass", ".less", ".styl"):
    EXT_PROFILE[_e] = P_CSS
EXT_PROFILE[".lua"] = P_LUA
for _e in (".vue", ".svelte", ".astro"):
    EXT_PROFILE[_e] = P_MIXED

NAME_PROFILE = {"Dockerfile": P_HASH, "Makefile": P_HASH, "Gemfile": P_HASH, "Rakefile": P_HASH}

SKIP_DIRS = {
    ".git", ".hg", ".svn", "node_modules", "vendor", "bower_components", "dist", "build",
    "out", "target", ".next", ".nuxt", ".svelte-kit", ".turbo", ".cache", "__pycache__",
    ".venv", "venv", "env", ".tox", ".mypy_cache", ".pytest_cache", ".ruff_cache",
    "coverage", ".coverage", "htmlcov", "Pods", "DerivedData", ".gradle", ".idea", ".vscode",
    "public", "static", "wwwroot", "third_party", "third-party", "vendors",
    "migrations", "generated", "__generated__", ".terraform", "storybook-static",
}
SKIP_FILE_RE = re.compile(
    r"(\.min\.(js|css)$|\.bundle\.|[.-]lock\.|^package-lock\.json$|^yarn\.lock$|"
    r"^composer\.lock$|^Cargo\.lock$|^poetry\.lock$|^pnpm-lock\.yaml$|\.map$|"
    r"\.d\.ts$|\.pb\.go$|_pb2\.py$|\.generated\.)"
)
GENERATED_FILE_RE = re.compile(
    r"@generated\b|Code generated .{0,40}DO NOT EDIT|DO NOT EDIT THIS FILE|"
    r"(automatically|auto)[- ]generated|This file is generated", re.I
)

# ---------------------------------------------------------------------------
# Protected content — never a finding (except SECRET, which overrides everything)
# ---------------------------------------------------------------------------

# Pragmas change compiler, linter, or build behavior. They are code wearing a comment's
# syntax; deleting one is a functional change, so they are exempt from every rule.
PRAGMA_RE = re.compile(
    r"^(eslint[-\s]|prettier-ignore|@ts-|ts-ignore|ts-expect-error|tslint:|biome-ignore|"
    r"deno-lint-ignore|noqa|type:\s*ignore|pylint:|flake8:|mypy:|fmt:\s*(on|off)|"
    r"pragma[:\s]|shellcheck\s|rubocop:|nolint|lint:ignore|golint|go:|\+build|NOLINT|"
    r"clang-format\s|istanbul\s|c8\s|v8\s|coverage:|jscpd:|swiftlint:|phpcs:|phpstan-|"
    r"psalm-|phan-|codingStandardsIgnore|@codeCoverageIgnore|-\*-\s*coding|"
    r"frozen_string_literal|:nodoc:|@SuppressWarnings|region\b|endregion\b|MARK:|"
    r"namespace\s|webpack|vite-ignore|@jsx|@flow|@vue|sourceMappingURL|"
    r"eslint-disable|@preserve|@license|@ts-nocheck)", re.I
)
RAW_PRAGMA_PREFIXES = ("#!", "/*!", "<!--[if", "/*+", "//go:", "//!", "#include")
LICENCE_RE = re.compile(r"copyright|licen[cs]e|SPDX-License-Identifier|all rights reserved",
                        re.I)

PROLOGUE_RE = re.compile(r"^\s*(#!|<\?php|<\?xml|['\"]use (strict|client|server)['\"];?\s*$"
                         r"|from __future__ import|#\s*-\*-\s*coding)")

CODE_SIGNALS = (
    re.compile(r"[;{}]\s*$"),
    re.compile(r"^\s*(if|for|while|return|switch|case|else|elif|try|except|catch|finally|"
               r"function|def|class|const|let|var|import|from|export|public|private|"
               r"protected|new|await|async|foreach|echo|print|require|include|use|package|"
               r"fn|impl|struct|match|end|do|then|puts|console\.)\b"),
    # No space before `(` — `notify(user)` is a call, `defect (see below)` is prose.
    re.compile(r"\w+\([^()]*\)\s*[;{,.]?\s*$"),
    re.compile(r"^\s*</?[a-zA-Z][\w-]*[\s/>]"),
    re.compile(r"^\s*[\w$.]+\([^()]*\)\s*\.\s*\w"),
)
ASSIGN_RE = re.compile(r"^\s*([\w$.\[\]'\"]+)\s*(?:=|\+=|-=|\|\|=|\?\?=)\s*(.*)$")
POSITIONAL_RE = re.compile(r"^\$[\d@*#]")
# A bullet is prose, whatever punctuation it ends with.
LIST_ITEM_RE = re.compile(r"^\s*([-*+•]|\d+[.)])\s")

SECRET_PATTERNS = (
    ("private key", re.compile(r"-----BEGIN [A-Z ]*PRIVATE KEY-----")),
    ("aws access key", re.compile(r"\bAKIA[0-9A-Z]{16}\b")),
    ("stripe key", re.compile(r"\bsk_(live|test)_[A-Za-z0-9]{10,}")),
    ("github token", re.compile(r"\bgh[pousr]_[A-Za-z0-9]{20,}")),
    ("slack token", re.compile(r"\bxox[baprs]-[A-Za-z0-9-]{10,}")),
    ("google api key", re.compile(r"\bAIza[0-9A-Za-z_\-]{35}\b")),
    ("bearer token", re.compile(r"\bBearer\s+[A-Za-z0-9._\-]{20,}")),
    ("jwt", re.compile(r"\beyJ[A-Za-z0-9_\-]{10,}\.[A-Za-z0-9_\-]{10,}\.")),
    ("credential in url", re.compile(r"\b\w+://[^\s:@/]+:[^\s:@/]{3,}@")),
    ("credential literal", re.compile(
        r"\b(password|passwd|pwd|secret|api[_-]?key|apikey|access[_-]?token|"
        r"client[_-]?secret|private[_-]?key)\b\s*[:=]\s*[\"']?[^\s\"'<>{}$]{6,}", re.I)),
)
# Placeholders and env lookups are documentation, not leaked credentials.
SECRET_FALSE_POSITIVE_RE = re.compile(
    r"env|getenv|process\.|os\.environ|secrets?\.|vault|\bxxx+\b|\*{3,}|redacted|placeholder|"
    r"your[_-]|<[^>]+>|\{\{|\$\{|example\.com|changeme|todo|none|null|\bhere\b", re.I)

# ---------------------------------------------------------------------------
# Comment extraction
# ---------------------------------------------------------------------------


def _line_index(text):
    starts = [0]
    for m in re.finditer("\n", text):
        starts.append(m.end())
    return starts


def _pos(starts, off):
    ln = bisect_right(starts, off)
    return ln, off - starts[ln - 1]


def _regex_allowed(text, i):
    """True when a `/` at offset i starts a JS regex literal rather than division."""
    j = i - 1
    while j >= 0 and text[j] in " \t\r\n":
        j -= 1
    if j < 0:
        return True
    if text[j] in "=(,:[!&|?{};+-*%~^<>":
        return True
    k = j
    while k >= 0 and (text[k].isalnum() or text[k] == "_"):
        k -= 1
    return text[k + 1:j + 1] in {
        "return", "typeof", "instanceof", "in", "of", "new", "delete", "void", "throw",
        "case", "do", "else", "yield", "await",
    }


def _skip_string(text, i, prof):
    """If a string literal starts at i, return the offset just past it, else None."""
    n = len(text)
    for opener, closer, escapes in prof.strings:
        if text.startswith(opener, i):
            j = i + len(opener)
            while j < n:
                c = text[j]
                if escapes and c == "\\":
                    j += 2
                    continue
                if c == "\n" and opener in ("'", '"'):
                    return j          # unterminated line string; resync at the newline
                if text.startswith(closer, j):
                    return j + len(closer)
                j += 1
            return n
    if prof.template and text[i] == "`":
        j, depth = i + 1, 0
        while j < n:
            c = text[j]
            if c == "\\":
                j += 2
                continue
            if text.startswith("${", j):
                depth += 1
                j += 2
                continue
            if c == "}" and depth:
                depth -= 1
            elif c == "`" and not depth:
                return j + 1
            j += 1
        return n
    return None


def _skip_regex(text, i):
    n, j, in_class = len(text), i + 1, False
    while j < n:
        c = text[j]
        if c == "\\":
            j += 2
            continue
        if c == "\n":
            return None
        if c == "[":
            in_class = True
        elif c == "]":
            in_class = False
        elif c == "/" and not in_class:
            j += 1
            while j < n and text[j].isalpha():
                j += 1
            return j
        j += 1
    return None


def extract_generic(text, prof):
    """Comment spans as (start_off, end_off, kind), string- and regex-aware."""
    spans, n, i = [], len(text), 0
    while i < n:
        c = text[i]
        if c in " \t\r\n":
            i += 1
            continue
        s = _skip_string(text, i, prof)
        if s is not None:
            i = s
            continue
        hit = None
        for opener, closer in prof.block:
            if text.startswith(opener, i):
                end = text.find(closer, i + len(opener))
                end = n if end == -1 else end + len(closer)
                hit = (i, end, "block")
                break
        if hit:
            spans.append(hit)
            i = hit[1]
            continue
        for marker in prof.line:
            if text.startswith(marker, i):
                end = text.find("\n", i)
                end = n if end == -1 else end
                hit = (i, end, "line")
                break
        if hit:
            spans.append(hit)
            i = hit[1]
            continue
        if prof.regex and c == "/" and _regex_allowed(text, i):
            r = _skip_regex(text, i)
            if r:
                i = r
                continue
        i += 1
    return spans


def extract_python(text):
    """Python comments and docstrings via tokenize, which never misreads a string."""
    out = []
    try:
        toks = list(tokenize.generate_tokens(io.StringIO(text).readline))
    except (tokenize.TokenError, IndentationError, SyntaxError, ValueError):
        return None
    at_stmt_start = True
    for tok in toks:
        if tok.type == tokenize.COMMENT:
            out.append((tok.start, tok.end, "line", tok.string))
        elif tok.type == tokenize.STRING:
            if at_stmt_start and tok.string.lstrip("rRbBuUfF")[:3] in ('"""', "'''"):
                out.append((tok.start, tok.end, "docstring", tok.string))
            at_stmt_start = False
        elif tok.type in (tokenize.NEWLINE, tokenize.NL, tokenize.INDENT,
                          tokenize.DEDENT, tokenize.ENCODING):
            at_stmt_start = True
        elif tok.type != tokenize.COMMENT:
            at_stmt_start = False
    return out


# ---------------------------------------------------------------------------
# Units — a comment plus the context needed to judge it
# ---------------------------------------------------------------------------


class Unit:
    def __init__(self, start, end, kind, raw, lines, indent, trailing):
        self.start = start          # 1-based first line
        self.end = end              # 1-based last line
        self.kind = kind            # line | block | docstring
        self.raw = raw
        self.lines = lines          # marker-stripped content, one entry per source line
        self.indent = indent
        self.trailing = trailing    # code precedes the comment on its first line
        self.own_code = ""          # that preceding code — the subject of a trailing comment
        self.next_code = None       # (lineno, text) of the next real code line
        self.blank_before_code = 0
        self.protected = False
        self.file_header = False    # states the file's purpose; length and gap are expected

    @property
    def height(self):
        return self.end - self.start + 1

    @property
    def text(self):
        return " ".join(x for x in self.lines if x).strip()

    @property
    def is_doc(self):
        r = self.raw.lstrip()
        return (self.kind == "docstring" or r.startswith("/**") or r.startswith("///")
                or r.startswith("//!") or r.startswith("/*!"))


def _strip_markers(raw, kind):
    lines = raw.split("\n")
    out = []
    for idx, ln in enumerate(lines):
        s = ln.strip()
        if kind == "block":
            if idx == 0:
                s = re.sub(r"^(/\*+!?|<!--)", "", s)
            if idx == len(lines) - 1:
                s = re.sub(r"(\*+/|-->)\s*$", "", s)
            s = re.sub(r"^\*+\s?", "", s)
        elif kind == "docstring":
            s = re.sub(r"^[rRbBuUfF]*(\"\"\"|''')", "", s)
            s = re.sub(r"(\"\"\"|''')\s*$", "", s)
        else:
            s = re.sub(r"^(//+!?|#+|--+)\s?", "", s)
        out.append(s.strip())
    return out


def build_units(path, text):
    ext = os.path.splitext(path)[1].lower()
    base = os.path.basename(path)
    lines = text.split("\n")
    raw_spans = []

    if ext in (".py", ".pyi"):
        toks = extract_python(text)
        if toks is not None:
            for (sr, sc), (er, ec), kind, s in toks:
                raw_spans.append((sr, sc, er, s, kind))
    if not raw_spans:
        prof = EXT_PROFILE.get(ext) or NAME_PROFILE.get(base)
        if prof is None:
            return None
        starts = _line_index(text)
        for so, eo, kind in extract_generic(text, prof):
            sr, sc = _pos(starts, so)
            er, _ = _pos(starts, max(so, eo - 1))
            raw_spans.append((sr, sc, er, text[so:eo], kind))

    raw_spans.sort(key=lambda s: (s[0], s[1]))
    units = []
    for sr, sc, er, raw, kind in raw_spans:
        before = lines[sr - 1][:sc] if sr - 1 < len(lines) else ""
        trailing = bool(before.strip())
        indent = len(before) - len(before.lstrip()) if not trailing else 0
        u = Unit(sr, er, kind, raw, _strip_markers(raw, kind), indent, trailing)
        u.own_code = before.strip()
        # Consecutive line comments at the same indent read as one paragraph; judge them
        # as one, or a five-line block gets reported five times.
        if (units and kind == "line" and not trailing and units[-1].kind == "line"
                and not units[-1].trailing and units[-1].end == sr - 1
                and units[-1].indent == indent):
            prev = units[-1]
            prev.end = er
            prev.raw += "\n" + raw
            prev.lines += u.lines
            continue
        units.append(u)

    for pos, u in enumerate(units):
        # A header is the first comment with no real code above it — only blanks, a shebang,
        # or a file-opening tag. A comment merely near the top is not a header.
        u.file_header = pos == 0 and not u.trailing and all(
            not lines[i].strip() or PROLOGUE_RE.match(lines[i])
            for i in range(u.start - 1))
        blanks = 0
        for ln in range(u.end, len(lines)):
            body = lines[ln].strip()
            if not body:
                blanks += 1
                continue
            u.next_code = (ln + 1, lines[ln])
            u.blank_before_code = blanks
            break
        head = u.text
        u.protected = (
            bool(PRAGMA_RE.match(head))
            or u.raw.lstrip().startswith(RAW_PRAGMA_PREFIXES)
            or (u.start <= 6 and bool(LICENCE_RE.search(u.raw)))
        )
    return units


# ---------------------------------------------------------------------------
# Code detection
# ---------------------------------------------------------------------------


def _assignment(line):
    """True for a real assignment, false for prose shaped like one.

    `# $1 = added+removed line count` documents a shell parameter and `null = absent`
    documents a return value; neither is commented-out code.
    """
    m = ASSIGN_RE.match(line)
    if not m:
        return False
    lhs, rhs = m.group(1), m.group(2).strip()
    if POSITIONAL_RE.match(lhs) or not rhs:
        return False
    return bool(re.search(r"[(){}\[\];\"'`]", rhs) or " " not in rhs)


def _code_like(line):
    return sum(1 for r in CODE_SIGNALS if r.search(line)) + (1 if _assignment(line) else 0)


# ---------------------------------------------------------------------------
# Files
# ---------------------------------------------------------------------------


def discover(paths, root):
    files, seen = [], set()

    def want(p):
        base = os.path.basename(p)
        if SKIP_FILE_RE.search(base):
            return False
        ext = os.path.splitext(p)[1].lower()
        return ext in EXT_PROFILE or base in NAME_PROFILE

    for p in paths:
        if os.path.isfile(p):
            if want(p) and p not in seen:
                seen.add(p)
                files.append(p)
            continue
        listed = None
        try:
            # Include untracked files: a pass over "my changes" must see new, unstaged files.
            out = subprocess.run(["git", "-C", p, "ls-files", "-z", "--cached", "--others",
                                  "--exclude-standard"], capture_output=True, text=True,
                                 timeout=60)
            if out.returncode == 0:
                listed = [os.path.join(p, f) for f in out.stdout.split("\0") if f]
        except (OSError, subprocess.SubprocessError):
            listed = None
        if listed is None:
            listed = []
            for dirpath, dirnames, filenames in os.walk(p):
                dirnames[:] = [d for d in dirnames if d not in SKIP_DIRS
                               and not d.startswith(".")]
                listed += [os.path.join(dirpath, f) for f in filenames]
        for f in listed:
            rel = os.path.relpath(f, root)
            if any(part in SKIP_DIRS for part in rel.split(os.sep)):
                continue
            if want(f) and f not in seen:
                seen.add(f)
                files.append(f)
    return sorted(files)


# ---------------------------------------------------------------------------
# Wording rules — each table cites its source in references/
# ---------------------------------------------------------------------------

def _ci(pattern):
    return re.compile(pattern, re.I)


# Wordy phrase → plain replacement. Source: plainlanguage.gov "Use simple words and
# phrases", Google developer documentation style guide word list. See WORD_LIST.md.
WORDY = [
    (r"\bin order to\b", "to"),
    (r"\bso as to\b", "to"),
    (r"\butili[sz](e|es|ed|ing)\b", "use"),
    (r"\butili[sz]ation\b", "use"),
    (r"\bmake use of\b", "use"),
    (r"\bprior to\b", "before"),
    (r"\bsubsequent to\b", "after"),
    (r"\bsubsequently\b", "later / then"),
    (r"\bin the event (that|of)\b", "if"),
    (r"\bdue to the fact that\b", "because"),
    (r"\bowing to the fact that\b", "because"),
    (r"\bin view of the fact that\b", "because"),
    (r"\bin spite of the fact that\b", "although"),
    (r"\bdespite the fact that\b", "although"),
    (r"\bat this point in time\b", "drop it, or name the version"),
    (r"\bat the present time\b", "drop it, or name the version"),
    (r"\bat this moment in time\b", "drop it, or name the version"),
    (r"\bfor the purpose of\b", "to / for"),
    (r"\bwith (regard|respect|reference) to\b", "about / for"),
    (r"\bin (regard|relation|reference) to\b", "about / for"),
    (r"\bin terms of\b", "for / in"),
    (r"\bis able to\b", "can"),
    (r"\bare able to\b", "can"),
    (r"\bhas the (ability|capability|capacity) to\b", "can"),
    (r"\bhave the (ability|capability|capacity) to\b", "can"),
    (r"\bis capable of\b", "can"),
    (r"\bin close proximity( to)?\b", "near"),
    (r"\ba (large|great|significant) number of\b", "many"),
    (r"\ba (small )?number of\b", "some / several"),
    (r"\bthe (vast )?majority of\b", "most"),
    (r"\bcommenc(e|es|ed|ing)\b", "start"),
    (r"\bendeavou?r(s|ed|ing)? to\b", "try to"),
    (r"\bascertain(s|ed|ing)?\b", "find out / check"),
    (r"\bfacilitat(e|es|ed|ing)\b", "help / allow"),
    (r"\bapproximately\b", "about"),
    (r"\bsufficient\b", "enough"),
    (r"\bnumerous\b", "many"),
    (r"\bin addition to\b", "besides / and"),
    (r"\bwhether or not\b", "whether"),
    (r"\beach and every\b", "each / every"),
    (r"\bfirst and foremost\b", "first"),
    (r"\bend result\b", "result"),
    (r"\bfuture plans\b", "plans"),
    (r"\bcompletely (eliminate|remove|destroy)\b", r"\1"),
    (r"\bin the process of\b", "(drop it)"),
    (r"\bon a (daily|weekly|monthly|regular) basis\b", r"\1 / regularly"),
    (r"\bat all times\b", "always"),
    (r"\bin a timely (manner|fashion)\b", "quickly / on time"),
    (r"\bas a means (of|to)\b", "to"),
    (r"\bwith the exception of\b", "except"),
    (r"\buntil such time as\b", "until"),
    (r"\bnotwithstanding\b", "despite"),
    (r"\bpursuant to\b", "under"),
    (r"\bhenceforth\b", "from now on"),
    (r"\b(herein|therein|hereby|thereof|heretofore|aforementioned)\b", "here / this"),
    (r"\bin excess of\b", "more than"),
    (r"\bin the near future\b", "soon"),
    (r"\bhas a tendency to\b", "tends to"),
    (r"\bit is (necessary|required|mandatory|essential) (that|to)\b", "must"),
    (r"\bperform(s|ed|ing)? (a |an |the )?(validation|check|verification|calculation|"
     r"conversion|lookup|update|deletion|initiali[sz]ation) (of|on)\b",
     "use the verb: validate / check / convert …"),
    (r"\bmak(e|es|ing) a decision\b", "decide"),
    (r"\bprovid(e|es|ed|ing) assistance\b", "help"),
    (r"\bgiv(e|es|ing) consideration to\b", "consider"),
    (r"\btak(e|es|ing) into (consideration|account)\b", "consider"),
    (r"\bis (dependent|reliant) (on|upon)\b", "depends on"),
    (r"\bis indicative of\b", "indicates / shows"),
    (r"\bis (in )?need of\b", "needs"),
    (r"\bin the case (that|of)\b", "if / for"),
    (r"\bfor the reason that\b", "because"),
    (r"\bthe reason (why )?is (because|that)\b", "because"),
    (r"\bin conjunction with\b", "with"),
    (r"\bby means of\b", "by / with"),
    (r"\bthe question as to whether\b", "whether"),
    (r"\bin lieu of\b", "instead of"),
    (r"\battempt(s|ed|ing)? to\b", "try to"),
    (r"\bregarding\b", "about"),
    (r"\bpossess(es|ed|ing)?\b", "have"),
    (r"\bconsequently\b", "so"),
    (r"\badditional\b", "more / extra"),
    (r"\bthere (is|are) (a |an )?\w+ (that|which|who)\b", "start with the subject"),
]
WORDY = [(_ci(p), s) for p, s in WORDY]

# Minimizers and throat-clearing. Sources: the Google developer documentation word list and
# the Kubernetes and Microsoft style guides. See WORD_LIST.md.
FILLER = [
    (r"\bsimply\b", "drop it"),
    (r"\bjust\b(?!\s+(before|after|past|below|above|once|as|like|in time|enough|now|then)\b)",
     "drop it (or 'only')"),
    (r"\bbasically\b", "drop it"),
    (r"\bactually\b", "drop it, unless it contrasts with an expectation"),
    (r"\breally\b", "drop it"),
    (r"\bvery\b", "drop it or use a precise word"),
    (r"\b(obviously|clearly|of course|needless to say)\b",
     "drop it — what is obvious to you is not obvious to the reader"),
    (r"\b(easily|easy to|trivially|trivial to)\b", "drop it — do not promise ease"),
    (r"\bquite\b", "drop it"),
    (r"\bliterally\b", "drop it"),
    (r"\bplease\b", "drop it — state the instruction"),
    (r"\b(note that|it should be noted that|be aware that|keep in mind that|remember that)\b",
     "drop it — state the fact"),
    (r"\bas you can see\b", "drop it"),
    (r"\bin fact\b", "drop it"),
    (r"\b(totally|completely|absolutely|entirely) (necessary|required|safe|sure)\b",
     "drop the intensifier"),
]
FILLER = [(_ci(p), s) for p, s in FILLER]

# Stacked or empty hedges. Real uncertainty is fine; state what is unknown instead.
HEDGE = [
    (r"\bI (think|believe|guess|suppose|assume)\b", "state the fact, or say what is unverified"),
    (r"\b(I'?m|I am|not) (not )?(sure|certain) (if|why|whether|what|how)\b",
     "say what is unknown: 'Unverified: …' or a TODO with an issue"),
    (r"\b(probably|presumably|hopefully|supposedly)\b", "state it, or say what is unverified"),
    (r"\b(seems|appears) to\b", "state what it does"),
    (r"\b(sort|kind) of\b", "drop it"),
    (r"\bsomewhat\b", "drop it or quantify"),
    (r"\b(might|may|could) (possibly|potentially|perhaps)\b", "one hedge at most: 'may'"),
    (r"\b(maybe|perhaps)\b", "state it, or say what is unverified"),
    (r"\bshould (work|be fine|be ok|be okay|be good)\b", "say what was verified"),
    (r"\bin theory\b", "say what was verified"),
]
HEDGE = [(_ci(p), s) for p, s in HEDGE]

# Vocabulary and patterns over-represented in LLM output. Mostly Wikipedia, "Signs of AI
# writing"; "leverage" and "seamless" come from the Google word list and marketing-tone
# guidance instead. See WORD_LIST.md. A human may use any one of these; a cluster is the
# signal.
AI_WORDS = [
    (r"\bdelv(e|es|ed|ing)\b", "look at / cover"),
    (r"\bleverag(e|es|ed|ing)\b", "use"),
    (r"\brobust(ly|ness)?\b", "say what failure it survives"),
    (r"\bseamless(ly)?\b", "drop it"),
    (r"\b(showcas(e|es|ed|ing)|bolster(s|ed|ing)?|garner(s|ed|ing)?)\b", "show / add / get"),
    (r"\b(serves|stands|functions) as (a|an|the)\b", "is"),
    (r"\binterplay\b", "interaction"),
    (r"\bvibrant\b", "drop it"),
    (r"\bdeep dive\b", "look / detail"),
    (r"\bcomprehensive(ly)?\b", "full / complete, or drop it"),
    (r"\b(crucial|pivotal|vital|paramount)\b", "required / important — or say why"),
    (r"\bstreamlin(e|es|ed|ing)\b", "simplify / speed up"),
    (r"\bempower(s|ed|ing)?\b", "let / allow"),
    (r"\belevat(e|es|ed|ing)\b", "improve / raise"),
    (r"\bmeticulous(ly)?\b", "careful(ly), or drop it"),
    (r"\bintricate\b", "complex"),
    (r"\bholistic(ally)?\b", "whole / overall"),
    (r"\bsynerg(y|ies|istic)\b", "drop it"),
    (r"\bparadigm\b", "model / approach"),
    (r"\b(cutting[- ]edge|state[- ]of[- ]the[- ]art|game[- ]chang(er|ing)|best[- ]in[- ]class)\b",
     "drop it"),
    (r"\bplays? an? (crucial|key|vital|pivotal|important|significant|central) role in\b",
     "say what it does"),
    (r"\bit(?:'s| is) (important|worth|crucial|essential) (to note|noting|to mention|to remember)"
     r"( that)?\b", "drop it — state the fact"),
    (r"\ba testament to\b", "drop it"),
    (r"\bin the (realm|world|landscape) of\b", "in / for"),
    (r"\bnavigat(e|es|ing) the (complexities|intricacies|challenges)\b", "handle"),
    (r"\bever[- ](evolving|changing|growing)\b", "drop it"),
    (r"\btapestry\b", "drop it"),
    (r"\bunderscor(e|es|ed|ing)\b", "show / stress"),
    (r"\bfoster(s|ed|ing)?\b", "encourage / build"),
    (r"\bharness(es|ed|ing)?\b", "use"),
    (r"\bunlock(s|ed|ing)? (the )?(power|potential|full)\b", "enable / allow"),
    (r"\bembark(s|ed|ing)? on\b", "start"),
    (r"\bboasts?\b", "has"),
    (r"^(moreover|furthermore|additionally)\b,?", "also — or drop it"),
    (r"\b(happy coding|hope this helps|great question|certainly!?|absolutely!)\b", "drop it"),
    (r"\ba (wide|broad|diverse) (range|array|variety) of\b", "many / several"),
    (r"\bensur(e|es|ing) (a )?(smooth|seamless|optimal|consistent) \w+", "say what it guarantees"),
    (r"\b(optimal|optimi[sz]ed) (performance|experience|results?)\b", "say what gets faster"),
    (r"\b(enhanc(e|es|ed|ing)|elevat(e|es|ing)) (the )?(user )?(experience|functionality)\b",
     "say what changes"),
]
AI_WORDS = [(_ci(p), s) for p, s in AI_WORDS]
EMOJI_RE = re.compile("[\U0001F300-\U0001FAFF\U00002700-\U000027BF\U0001F000-\U0001F2FF"
                      "☀-⛿⭐⬆⬇↔-⇿]")

# Openers that describe the comment instead of the code: "This function is used to …".
OPENER_RE = _ci(
    r"^\s*(?:(?:this|the following|the below|below)\s+"
    r"(?:function|method|class|module|file|code|helper|hook|component|snippet|block|"
    r"variable|constant|const|line|loop|script|test|util|utility|endpoint|handler|"
    r"middleware|service|type|interface|property|field|function\s+call|section|piece of code)"
    r"\s+(?:is\s+(?:used|responsible|designed|meant|intended|here)\s*(?:to|for)?|will\b|"
    r"basically\b|simply\b|just\b|is\s+an?\s+\w+\s+(?:that|which|to)\b|"
    r"handles\b|takes care of\b|does\b|helps\b)"
    r"|(?:a\s+)?(?:function|method|helper|class|util(?:ity)?)\s+(?:that|which|to|for|used to)\s"
    r"|(?:the\s+)?(?:purpose|goal|job|role)\s+of\s+this\b"
    r"|this\s+is\s+(?:a|an|the|where|how|what)\b"
    r"|here\s+(?:is|are)\b)")

# First-person narration and tutorial voice.
NARRATE = [
    (r"(?<![\w/])I(?:'m|'ve|'ll|'d)?(?![\w/.])", "drop the first person — state the fact"),
    (r"\b(my|me)\b", "drop the first person"),
    (r"\blet'?s\b", "use the imperative or state the fact"),
    (r"^(here|now|next|first|finally),?\s+we\b", "state what the code does"),
    (r"\bwe(?:'re| are) going to\b", "state what the code does"),
    (r"\bwe'll\b", "state what the code does"),
    (r"\b(as we can see|you'?ll notice|as you know)\b", "drop it"),
]
NARRATE = [(re.compile(p, re.I if not p.startswith("(?<![\\w/])I") else 0), s)
           for p, s in NARRATE]

IRREGULAR_PARTICIPLES = (
    "done|made|built|sent|set|put|run|read|written|given|taken|kept|held|found|shown|known|"
    "thrown|drawn|chosen|begun|broken|brought|bought|caught|fed|got|gotten|hidden|hit|left|"
    "lost|meant|paid|said|seen|sold|shut|spent|split|spread|struck|told|thought|understood|"
    "won|bound|cast|dealt|forbidden|forgotten|frozen|ridden|shaken|slid|spun|stolen|stuck|"
    "swept|torn|woken|worn|withdrawn")
PASSIVE_RE = _ci(
    r"\b(is|are|was|were|be|been|being|gets|get|got)\s+(?:\w+ly\s+)?"
    r"(\w+ed|" + IRREGULAR_PARTICIPLES + r")\s+by\s+"
    r"(?!default\b|design\b|convention\b|hand\b|reference\b|value\b|itself\b|themselves\b|"
    r"name\b|id\b|key\b|index\b|position\b|type\b|the way\b|far\b|\d)"
    r"((?:the\s+|a\s+|an\s+|our\s+|its\s+)?[\w.`$()-]+)")

# Non-inclusive or ableist terms. Sources: Google "Write inclusive documentation",
# IETF draft-knodel-terminology, Microsoft bias-free communication. See WORD_LIST.md.
TERMS = [
    (r"\bwhite[- ]?list(s|ed|ing)?\b", "allowlist"),
    (r"\bblack[- ]?list(s|ed|ing)?\b", "denylist / blocklist"),
    (r"\bmaster\b", "primary / main / leader"),
    (r"\bslaves?\b", "replica / secondary / follower"),
    (r"\bsanity[- ]check(s|ed|ing)?\b", "quick check / confidence check"),
    (r"\bsane(ly)?\b", "valid / sensible"),
    (r"\bgr[ae]y[- ]?list(s|ed|ing)?\b", "provisional list"),
    (r"\bdummy\b", "placeholder / stub / sample"),
    (r"\bgrandfather(ed|ing)?\b", "legacy / exempt"),
    (r"\bman[- ]?(hours?|days?|power)\b", "person-hours / staff"),
    (r"\bblind(ly)? to\b", "unaware of"),
    (r"\b(crazy|insane|lame|dumb)\b", "unexpected / surprising / simple"),
    (r"\bcrippl(e|es|ed|ing)\b", "disable / slow down"),
    (r"\bguys\b", "everyone / folks"),
    (r"\b(he|she) or (she|he)\b", "they"),
    (r"\b(he|she)/(she|he)\b", "they"),
    (r"\bnative(s)? (speaker|feature)s?\b", "built-in / fluent"),
]
TERMS = [(_ci(p), s) for p, s in TERMS]

# Common misspellings seen in code comments.
MISSPELLINGS = {
    "teh": "the", "recieve": "receive", "recieved": "received", "occured": "occurred",
    "occurence": "occurrence", "seperate": "separate", "seperately": "separately",
    "dependant": "dependent", "accomodate": "accommodate", "lenght": "length",
    "retreive": "retrieve", "paramter": "parameter", "parmeter": "parameter",
    "funtion": "function", "fucntion": "function", "functoin": "function",
    "arguement": "argument", "arguements": "arguments", "definately": "definitely",
    "enviroment": "environment", "enviornment": "environment", "existant": "existent",
    "compatable": "compatible", "succesful": "successful", "successfull": "successful",
    "sucessful": "successful", "untill": "until", "wich": "which", "whcih": "which",
    "adress": "address", "calender": "calendar", "concurent": "concurrent",
    "dependancy": "dependency", "dependancies": "dependencies", "initalize": "initialize",
    "initalise": "initialise", "intialize": "initialize", "occassionally": "occasionally",
    "priviledge": "privilege", "refered": "referred", "reponse": "response",
    "responce": "response", "requst": "request", "sucess": "success", "thier": "their",
    "threshhold": "threshold", "transfered": "transferred", "truely": "truly",
    "unneccessary": "unnecessary", "unecessary": "unnecessary", "neccessary": "necessary",
    "necesary": "necessary", "overriden": "overridden", "accross": "across",
    "acheive": "achieve", "beggining": "beginning", "begining": "beginning",
    "wether": "whether", "withing": "within", "reciever": "receiver", "incase": "in case",
    "alot": "a lot", "doesnt": "doesn't", "dont": "don't", "isnt": "isn't", "didnt": "didn't", "shouldnt": "shouldn't", "wouldnt": "wouldn't",
    "coudn't": "couldn't", "retured": "returned", "reutrn": "return", "valiation": "validation",
    "validaiton": "validation", "calcualte": "calculate", "authentification": "authentication",
    "comparision": "comparison", "explicitely": "explicitly", "implicitely": "implicitly",
    "persistant": "persistent", "consistant": "consistent", "independant": "independent",
    "maintainance": "maintenance", "occurance": "occurrence", "posible": "possible",
    "prefered": "preferred", "propogate": "propagate", "recursivly": "recursively",
    "similiar": "similar", "sepcific": "specific", "specifc": "specific", "stragety": "strategy",
    "strucure": "structure", "suport": "support", "temparary": "temporary",
    "tempory": "temporary", "usefull": "useful", "writting": "writing",
}
WORD_RE = re.compile(r"[A-Za-z][A-Za-z']*")

SHOUT_RUN_RE = re.compile(r"(?<![\w-])(?:[A-Z]{2,}[!?.,:]*\s+){1,}[A-Z]{2,}[!?.,:]*(?![\w-])")
BANG_RE = re.compile(r"!{2,}|\?{2,}|\?!|!\?")
ACRONYMS = {
    "API", "APIS", "HTTP", "HTTPS", "URL", "URI", "JSON", "XML", "HTML", "CSS", "SQL", "ID",
    "IDS", "UI", "UX", "OK", "CPU", "GPU", "RAM", "IO", "OS", "DB", "UTC", "UUID", "JWT",
    "TLS", "SSL", "SSH", "DNS", "TCP", "UDP", "IP", "CLI", "SDK", "AWS", "GCP", "CI", "CD",
    "PR", "TODO", "FIXME", "NOTE", "HACK", "XXX", "BUG", "GET", "POST", "PUT", "PATCH",
    "DELETE", "HEAD", "OPTIONS", "CRUD", "ORM", "RPC", "REST", "CORS", "CSRF", "XSS", "SSR",
    "CSR", "SPA", "PWA", "CDN", "SEO", "MVP", "MVC", "RFC", "ISO", "UTF", "ASCII", "PDF",
    "PNG", "JPG", "JPEG", "SVG", "GIF", "YAML", "TOML", "CSV", "ENV", "PHP", "JS", "TS",
    "JSX", "TSX", "NPM", "AST", "LRU", "TTL", "FIFO", "LIFO", "MIME", "SMTP", "IMAP", "FTP",
    "SFTP", "LDAP", "SAML", "OAUTH", "OIDC", "SSO", "MFA", "2FA", "OTP", "PII", "GDPR", "HIPAA",
    "PCI", "SLA", "SLO", "SLI", "QA", "E2E", "AND", "OR", "NOT", "NULL", "TRUE", "FALSE",
    "NAN", "EOF", "EOL", "CRLF", "LF", "UTF8", "GMT", "AM", "PM", "US", "UK", "EU", "USD",
    "EUR", "GB", "MB", "KB", "TB", "MS", "IDE", "LLM", "AI", "ML", "CPUS", "VM", "VMS", "K8S",
    "IAM", "ARN", "S3", "EC2", "RDS", "SQS", "SNS", "SES", "ECS", "EKS", "HMAC", "SHA", "MD5",
    "AES", "RSA", "EC", "CSP", "HSTS", "WAF", "DDOS", "VPN", "LAN", "WAN", "ETL", "BI", "KPI",
    "ACL", "RBAC", "ABAC", "DTO", "DAO", "SPI", "FFI", "ABI", "WASM", "GC", "JIT", "AOT",
    "HMR", "RSC", "ISR", "SSG", "CMS", "CRM", "ERP", "SKU", "VAT", "GST", "WCAG", "ARIA",
    "CLS", "LCP", "INP", "FCP", "TTFB", "TBT", "CWV", "RUM", "PSI", "CRUX",
}
MARKER_RE = re.compile(r"\b(TODO|FIXME|HACK|XXX|NOTE|BUG|WARNING|CAUTION|IMPORTANT|DEPRECATED|"
                       r"SAFETY|INVARIANT|PERF|SECURITY)(\([^)]*\))?:")

VAGUE = [
    (r"\b(stuff|things?)\b", "name the actual thing"),
    (r"\b(some|the|black) magic\b|\bmagic (happens|here)\b", "say what it does"),
    (r"\b(whatever|and so on|and so forth|and the like)\b", "list what matters, or stop"),
    (r"\betc\.?(?=\s*$|\s*\)|\s*[.;])", "finish the list or drop 'etc.'"),
    (r"\b(do|does) the (thing|trick|job)\b", "say what it does"),
    (r"\b(handle|deal with|take care of) (it|this|that|them)\b", "say what handling means"),
    (r"\bfor (some|whatever|various) reasons?\b", "state the reason, or say it is unknown"),
    (r"\bmisc(ellaneous)?\b", "name the contents"),
    (r"\bvarious\b", "name them, or say how many"),
]
VAGUE = [(_ci(p), s) for p, s in VAGUE]

# Words that date a comment. Source: Google developer documentation style guide,
# "Timeless documentation". A comment has no publish date; "currently" rots silently.
TIME = [
    (r"\b(currently|presently|nowadays|as of (now|today|this writing)|at the moment|for now|"
     r"right now)\b", "name the version, date, or issue — or drop it"),
    (r"\b(recently|lately|soon|in the future|eventually|not yet|going forward)\b",
     "name the version, date, or issue — or drop it"),
    (r"\b(the )?(new|old|latest|legacy) (way|version|api|approach|implementation|code|logic|"
     r"flow|system)\b", "name it: 'v2 API', 'pre-2025 checkout'"),
]
TIME = [(_ci(p), s) for p, s in TIME]

NEG_RE = _ci(
    r"\bnot (uncommon|unlike|unusual|unreasonable|unimportant|insignificant|invalid|incorrect|"
    r"impossible|improbable|infrequent(ly)?|dissimilar|unknown|undesirable|inconsistent|"
    r"unaware|unnecessary|unhelpful|unlikely|unable|without)\b"
    r"|\b(never|don'?t|doesn'?t|isn'?t|aren'?t|cannot|can'?t) not\b")

# ---------------------------------------------------------------------------
# Grammatical mood of doc-comment summaries
# ---------------------------------------------------------------------------

VERB_BASES = {
    "return", "get", "set", "create", "check", "compute", "calculate", "build", "handle",
    "parse", "convert", "load", "save", "fetch", "update", "delete", "remove", "add", "find",
    "validate", "render", "send", "initialize", "initialise", "generate", "process", "read",
    "write", "apply", "resolve", "format", "normalize", "normalise", "register", "start",
    "stop", "run", "execute", "open", "close", "make", "compare", "merge", "map", "filter",
    "sort", "transform", "extract", "emit", "dispatch", "call", "invoke", "wrap", "append",
    "insert", "clear", "reset", "verify", "ensure", "determine", "retrieve", "store", "cache",
    "decode", "encode", "serialize", "deserialize", "sanitize", "escape", "split", "join",
    "count", "collect", "print", "log", "show", "hide", "toggle", "enable", "disable", "mark",
    "schedule", "wait", "retry", "throw", "raise", "yield", "iterate", "walk", "scan",
    "match", "replace", "strip", "trim", "flush", "commit", "sync", "connect", "disconnect",
    "subscribe", "publish", "notify", "attach", "detach", "mount", "unmount", "install",
    "configure", "provide", "accept", "reject", "allow", "deny", "prevent", "skip", "look",
    "construct", "define", "describe", "emit", "compose", "measure", "track", "record",
    "report", "select", "query", "request", "respond", "serve", "listen", "handle",
    "compile", "evaluate", "test", "assert", "copy", "move", "rename", "lock", "unlock",
    "release", "acquire", "allocate", "free", "destroy", "dispose", "cancel", "abort",
    "refresh", "reload", "sign", "encrypt", "decrypt", "hash", "authenticate", "authorize",
    "redirect", "upload", "download", "import", "export", "pick", "choose", "build", "wrap",
    "memoize", "debounce", "throttle", "batch", "group", "flatten", "pad", "round", "clamp",
}


def _third_person(base):
    if base.endswith(("s", "sh", "ch", "x", "z", "o")):
        return base + "es"
    if base.endswith("y") and base[-2:-1] not in "aeiou":
        return base[:-1] + "ies"
    return base + "s"


THIRD_PERSON = {_third_person(b): b for b in VERB_BASES}

# Languages whose own style authority asks for a third-person summary ("Returns …").
# Google's C++ and JavaScript guides ask for the same; JS/TS are still judged by file majority
# because JSDoc and TSDoc set no mood rule and many codebases follow neither Google guide.
THIRD_PERSON_EXTS = {".java", ".kt", ".kts", ".scala", ".cs", ".swift", ".rs", ".groovy",
                     ".dart", ".c", ".h", ".cc", ".cpp", ".cxx", ".hpp", ".hh"}
# Languages where the summary must end in a period.
PERIOD_EXTS = {".go", ".py", ".pyi", ".java", ".kt", ".kts", ".rs"}

GO_DECL_RE = re.compile(r"^\s*(?:func\s+(?:\([^)]*\)\s*)?|type\s+|var\s+|const\s+)"
                        r"([A-Z]\w*)")

# ---------------------------------------------------------------------------
# Masking — rules must never fire on code, identifiers, URLs, or tag syntax
# ---------------------------------------------------------------------------

CODE_SPAN_RE = re.compile(r"`[^`\n]*`|\{@\w+[^}]*\}|\[\[[^\]]*\]\]")
# Quoted text is a mention ("avoid 'simply'") or a quoted message, never the writer's own prose.
QUOTED_RE = re.compile(r"\"[^\"\n]{1,80}\"|\u201c[^\u201d\n]{1,80}\u201d|"
                       r"(?<![A-Za-z])'[^'\n]{1,40}'(?![A-Za-z])")
URL_RE = re.compile(r"\b[a-z][a-z0-9+.-]*://\S+|\bwww\.\S+|\S+@\S+\.\w+", re.I)
IDENT_RE = re.compile(
    r"(?<![\w$])(?:[\w$]+(?:\.[\w$]+)+\(?\)?|[a-z]+[A-Z]\w*|[A-Z][a-z]+[A-Z]\w*|"
    r"\w+_\w+|[\w$]+\(\)|--?[a-z][\w-]+|\$\w+|[\w.-]*/[\w./-]+)")
TAG_PREFIX_RE = re.compile(
    r"^@(?:param|arg|argument|property|prop|typeparam|template|throws?|exception|raises?)"
    r"(?:\s+\{[^}]*\})?(?:\s+\[?[\w$.\[\]]+\]?)?\s*(?:-\s*)?"
    r"|^@(?:returns?|yields?|type|var)(?:\s+\{[^}]*\})?\s*(?:-\s*)?"
    r"|^@(?:see|link|since|version|author|license|copyright|deprecated|example|internal|"
    r"public|private|protected|override|inheritdoc|readonly)\b.*"
    r"|^:(?:param|type|raises?|returns?|rtype)[^:]*:\s*"
    r"|^[\w*]+(?:\s*\([^)]*\))?:\s")
DOCTEST_RE = re.compile(r"^(>>>|\.\.\.|\$\s|%\s|>\s)")
FENCE_RE = re.compile(r"^(```|~~~)")
SECTION_RE = re.compile(r"^(Args|Arguments|Parameters|Returns|Yields|Raises|Throws|Examples?|"
                        r"Attributes|Note|Notes|See Also|References|Warns?|Todo)\s*:?\s*$")
BULLET_RE = re.compile(r"^([-*+•]|\d+[.)])\s+")
COLUMN_RE = re.compile(r"\S {2,}\S")
PLACEHOLDER = "X"

ABBREV_RE = re.compile(r"\b(e\.g|i\.e|etc|vs|approx|cf|Mr|Mrs|Dr|No|Fig|incl|et al)\.", re.I)

EN_STOP = {
    "the", "a", "an", "is", "are", "was", "be", "to", "of", "and", "or", "in", "on", "for",
    "with", "this", "that", "it", "if", "not", "when", "by", "as", "from", "we", "you",
    "should", "can", "will", "must", "do", "does", "use", "so", "but", "at", "only", "all",
    "no", "then", "than", "into", "before", "after", "because", "each", "any", "which",
}
FOREIGN_STOP = {
    "de", "la", "que", "el", "los", "las", "del", "por", "para", "con", "una", "es", "und",
    "der", "die", "das", "ist", "nicht", "mit", "ein", "eine", "le", "les", "des", "est",
    "une", "pour", "dans", "pas", "qui", "não", "uma", "com", "il", "di", "che", "sono",
    "het", "een", "niet", "van", "och", "att", "som", "ett", "za", "od", "bu", "bir", "için",
    "ile",
}
# Lowercase by convention; a summary that opens with one is correctly capitalized.
LOWERCASE_NAMES = {"npm", "pnpm", "yarn", "git", "iOS", "macOS", "iPadOS", "watchOS", "tvOS",
                   "eBay", "iPhone", "iPad", "jQuery", "webpack", "vite", "esbuild", "rollup",
                   "gRPC", "npx", "pip", "uv", "cURL", "curl", "wget", "systemd", "cron",
                   "kubectl", "nginx", "bash", "zsh", "sh", "stdin", "stdout", "stderr",
                   "localhost", "true", "false", "null", "nil", "undefined", "none"}

SECRET_RULE = "SECRET"

DISPOSITION = {
    "WORDY": "REWRITE", "FILLER": "REWRITE", "HEDGE": "REVIEW", "AI": "REWRITE",
    "OPENER": "REWRITE", "NARRATE": "REWRITE", "PASSIVE": "REVIEW", "LONG": "REWRITE",
    "READ": "REVIEW", "MOOD": "REWRITE", "FORMAT": "REWRITE", "TERM": "REWRITE",
    "SPELL": "REWRITE", "SHOUT": "REWRITE", "VAGUE": "REVIEW", "NEG": "REWRITE",
    "TIME": "REVIEW", "SECRET": "ESCALATE",
}
RULE_HELP = {
    "WORDY": "wordy phrase with a plain replacement",
    "FILLER": "minimizer or throat-clearing word",
    "HEDGE": "hedge that hides what is actually known",
    "AI": "vocabulary or pattern typical of machine-written text",
    "OPENER": "opens by describing the comment, not the code",
    "NARRATE": "first-person or tutorial narration",
    "PASSIVE": "passive voice with a named actor",
    "LONG": "sentence over the word limit",
    "READ": "reading grade over the limit",
    "MOOD": "summary mood breaks the language or file convention",
    "FORMAT": "doc summary capitalization or end punctuation",
    "TERM": "non-inclusive or ableist term",
    "SPELL": "common misspelling",
    "SHOUT": "all-caps or stacked punctuation",
    "VAGUE": "vague reference that names nothing",
    "NEG": "double negative",
    "TIME": "time-relative word that rots",
    "SECRET": "possible credential in a comment",
}
ALL_RULES = list(DISPOSITION)


# ---------------------------------------------------------------------------
# Prose extraction
# ---------------------------------------------------------------------------


class Paragraph:
    """Masked prose from consecutive comment lines, with a map back to source lines."""

    def __init__(self):
        self.text = ""
        self.starts = []        # offset in text where each source line begins
        self.linenos = []
        self.originals = []

    def add(self, lineno, masked, original):
        if self.text:
            self.text += " "
        self.starts.append(len(self.text))
        self.linenos.append(lineno)
        self.originals.append(original)
        self.text += masked

    def line_at(self, off):
        i = max(0, bisect_right(self.starts, off) - 1)
        return self.linenos[i], self.originals[i]


def mask(s):
    s = CODE_SPAN_RE.sub(PLACEHOLDER, s)
    s = QUOTED_RE.sub(PLACEHOLDER, s)
    s = URL_RE.sub(PLACEHOLDER, s)
    s = IDENT_RE.sub(PLACEHOLDER, s)
    return s


def paragraphs(unit, ext):
    """Split a comment unit into prose paragraphs, skipping code, examples, and tags."""
    out, cur, in_fence, in_example = [], Paragraph(), False, False

    def flush():
        nonlocal cur
        if cur.text.strip():
            out.append(cur)
        cur = Paragraph()

    for idx, line in enumerate(unit.lines):
        lineno = unit.start + idx
        s = line.strip()
        if FENCE_RE.match(s):
            in_fence = not in_fence
            flush()
            continue
        if in_fence or not s:
            flush()
            continue
        low = s.lower()
        if low.startswith("@example") or SECTION_RE.match(s) and s.lower().startswith("example"):
            in_example = True
            flush()
            continue
        if in_example:
            if s.startswith("@") or SECTION_RE.match(s):
                in_example = False
            else:
                continue
        if SECTION_RE.match(s):
            flush()
            continue
        if DOCTEST_RE.match(s) or _code_like(s) >= 2 or MARKER_RE.fullmatch(s):
            flush()
            continue
        body = s
        if body.startswith("@") or body.startswith(":") or (
                unit.kind == "docstring" and re.match(r"^[\w*]+(\s*\([^)]*\))?:\s", body)):
            flush()
            body = TAG_PREFIX_RE.sub("", body, count=1)
            if not body.strip():
                continue
        # An aligned column or a `|` continuation is a table row, not part of a sentence.
        row = bool(COLUMN_RE.search(body) or body.startswith("|"))
        if BULLET_RE.match(body) or row:
            flush()
            body = BULLET_RE.sub("", body)
        body = MARKER_RE.sub("", body).strip()
        if body:
            cur.add(lineno, mask(body), s)
        if row:
            flush()
    flush()
    return out


def is_english(text):
    alpha = [c for c in text if c.isalpha()]
    if len(alpha) < 12:
        return True
    non_latin = sum(1 for c in alpha if ord(c) > 0x24F)
    if non_latin / len(alpha) > 0.3:
        return False
    words = [w.lower() for w in WORD_RE.findall(text)]
    if len(words) < 6:
        return True
    en = sum(1 for w in words if w in EN_STOP)
    fr = sum(1 for w in words if w in FOREIGN_STOP)
    return not (fr >= 2 and fr > en and fr / len(words) > 0.12)


def sentences(text):
    protected = ABBREV_RE.sub(lambda m: m.group(0).replace(".", "․"), text)
    parts = re.split(r"(?<=[.!?])\s+(?=[A-Z0-9\"'(\[X])|;\s+", protected)
    return [p.replace("․", ".").strip() for p in parts if p.strip()]


def word_count(s):
    return len(WORD_RE.findall(s))


def syllables(word):
    w = word.lower().strip("'")
    if len(w) <= 3:
        return 1
    w = re.sub(r"(?:es|ed|e)$", "", w) or w
    groups = re.findall(r"[aeiouy]+", w)
    return max(1, len(groups))


def fk_grade(sents):
    """Flesch-Kincaid grade over pre-split sentences; paragraphs never merge into one."""
    words = [w for sent in sents for w in WORD_RE.findall(sent)]
    if not sents or not words:
        return 0.0
    syl = sum(syllables(w) for w in words)
    return 0.39 * (len(words) / len(sents)) + 11.8 * (syl / len(words)) - 15.59


# ---------------------------------------------------------------------------
# Rules
# ---------------------------------------------------------------------------


def _first_word(text):
    m = re.match(r"\s*([A-Za-z]+)", text)
    return m.group(1) if m else ""


def summary_mood(text):
    """'imperative', 'descriptive', or None for a doc summary's first word."""
    w = _first_word(text).lower()
    if w in THIRD_PERSON:
        return "descriptive"
    if w in VERB_BASES:
        return "imperative"
    return None


FUNC_DECL_RE = re.compile(r"\bfunction\b|=>|\bfunc\b|\bfn\b|\bdef\b|\bsub\b|"
                          r"^\s*(?:[\w<>\[\],.?]+\s+)*[\w$]+\s*\([^;]*$")
TYPE_DECL_RE = re.compile(r"\b(class|interface|enum|struct|trait|protocol|record|object|"
                          r"type\s+\w+\s*=|namespace|module)\b")


def doc_target(unit, lines, ext):
    """'function', 'type', or 'other': what a doc comment documents.

    Mood rules (PEP 257's imperative, Javadoc's third person) govern function and method
    summaries. Class and module docs describe an entity, so their mood is never judged.
    """
    if unit.kind == "docstring":
        i = unit.start - 2
        while i >= 0 and not lines[i].strip():
            i -= 1
        prev = lines[i].strip() if i >= 0 else ""
        if prev.startswith(("def ", "async def ")) or re.search(r"\)\s*(->[^:]+)?:\s*$", prev):
            return "function"
        return "type" if prev.startswith("class ") else "other"
    code = unit.next_code[1] if unit.next_code else ""
    if TYPE_DECL_RE.search(code):
        return "type"
    return "function" if FUNC_DECL_RE.search(code) else "other"


def check_unit(unit, ext, cfg, lines=None):
    findings, seen = [], set()

    def add(rule, line, excerpt, why, suggest=""):
        key = (rule, line, why)
        if key in seen:
            return
        seen.add(key)
        findings.append({
            "rule": rule, "line": line, "disposition": DISPOSITION[rule],
            "excerpt": excerpt[:160], "why": why, "suggest": suggest,
        })

    for label, rx in SECRET_PATTERNS:
        if rx.search(unit.raw) and not SECRET_FALSE_POSITIVE_RE.search(rx.search(unit.raw)
                                                                        .group(0)):
            add("SECRET", unit.start, "<redacted>",
                "possible %s — do not rephrase; rotate the value" % label)
            return findings, None

    paras = paragraphs(unit, ext)
    if not paras:
        return findings, None
    prose = " ".join(p.text for p in paras)
    if not is_english(prose):
        return findings, "non-english"

    for p in paras:
        text = p.text

        def scan(table, rule, flags_first=False):
            for rx, suggest in table:
                for m in rx.finditer(text):
                    if m.group(0).strip() in ("", PLACEHOLDER):
                        continue
                    ln, orig = p.line_at(m.start())
                    add(rule, ln, orig, "'%s'" % m.group(0).strip(), suggest)

        scan(WORDY, "WORDY")
        scan(FILLER, "FILLER")
        scan(HEDGE, "HEDGE")
        scan(NARRATE, "NARRATE")
        scan(VAGUE, "VAGUE")
        scan(TIME, "TIME")
        for sent in sentences(text):
            off = text.find(sent)
            for rx, suggest in AI_WORDS:
                for m in rx.finditer(sent):
                    ln, orig = p.line_at(max(0, off) + m.start())
                    add("AI", ln, orig, "'%s'" % m.group(0).strip(), suggest)
        if EMOJI_RE.search(text):
            ln, orig = p.line_at(EMOJI_RE.search(text).start())
            add("AI", ln, orig, "emoji in a comment", "drop it — say it in words")
        for sent in sentences(text):
            if sent.count("—") >= 2:
                ln, orig = p.line_at(max(0, text.find(sent)))
                add("AI", ln, orig, "%d em dashes in one sentence" % sent.count("—"),
                    "split it, or use commas and parentheses")

        for rx, suggest in TERMS:
            for m in rx.finditer(text):
                ln, orig = p.line_at(m.start())
                term = m.group(0).lower().split()[0].replace("-", "")
                code = ((unit.next_code[1] if unit.next_code else "") + " " + unit.own_code)
                if term[:5] in re.sub(r"[^a-z]", "", code.lower()):
                    add("TERM", ln, orig, "'%s' also names code nearby" % m.group(0),
                        "rename in code first (ESCALATE), then the comment")
                    findings[-1]["disposition"] = "ESCALATE"
                else:
                    add("TERM", ln, orig, "'%s'" % m.group(0), suggest)

        for m in WORD_RE.finditer(text):
            fix = MISSPELLINGS.get(m.group(0).lower())
            if fix:
                ln, orig = p.line_at(m.start())
                add("SPELL", ln, orig, "'%s'" % m.group(0), fix)

        for m in SHOUT_RUN_RE.finditer(text):
            words = [w.strip("!?.,:") for w in m.group(0).split()]
            loud = [w for w in words if w not in ACRONYMS and not w.isdigit()]
            if len(loud) >= 2:
                ln, orig = p.line_at(m.start())
                add("SHOUT", ln, orig, "'%s'" % m.group(0).strip(),
                    "state the rule and the reason in sentence case")
        for m in BANG_RE.finditer(text):
            ln, orig = p.line_at(m.start())
            add("SHOUT", ln, orig, "'%s'" % m.group(0), "one period is enough")

        for m in NEG_RE.finditer(text):
            ln, orig = p.line_at(m.start())
            add("NEG", ln, orig, "'%s'" % m.group(0), "say it positively")

        for m in PASSIVE_RE.finditer(text):
            ln, orig = p.line_at(m.start())
            add("PASSIVE", ln, orig, "'%s'" % m.group(0),
                "active voice: '%s <verb>s …'" % m.group(3))

        for sent in sentences(text):
            n = word_count(sent)
            if n > cfg["max_words"]:
                ln, orig = p.line_at(max(0, text.find(sent)))
                add("LONG", ln, orig, "%d words (limit %d)" % (n, cfg["max_words"]),
                    "split it — one idea per sentence")
                # A few words over is a judgment call; far over is a rewrite.
                if n <= cfg["max_words"] + 10:
                    findings[-1]["disposition"] = "REVIEW"

    first = paras[0]
    if OPENER_RE.match(first.text):
        m = OPENER_RE.match(first.text)
        add("OPENER", first.linenos[0], first.originals[0], "'%s'" % m.group(0).strip(),
            "start with the verb or the fact: 'Parses …', 'Retries because …'")

    words = word_count(prose)
    if words >= MIN_WORDS_FOR_GRADE:
        g = fk_grade([sent for p in paras for sent in sentences(p.text)])
        if g > cfg["grade"]:
            add("READ", unit.start, first.originals[0],
                "grade %.1f over %d words (limit %d)" % (g, words, cfg["grade"]),
                "shorter sentences and shorter words")

    mood = None
    if unit.is_doc:
        summary = first.originals[0]
        stripped_summary = TAG_PREFIX_RE.sub("", summary) if summary.startswith("@") else summary
        is_function = lines is None or doc_target(unit, lines, ext) == "function"
        mood = (summary_mood(stripped_summary)
                if not summary.startswith("@") and is_function else None)
        if ext in THIRD_PERSON_EXTS and mood == "imperative":
            w = _first_word(stripped_summary)
            add("MOOD", first.linenos[0], summary, "'%s' is imperative" % w,
                "third person: '%s'" % _third_person(w.lower()).capitalize())
        if not summary.startswith("@"):
            fw = re.match(r"\s*(\S+)", summary)
            if (fw and fw.group(1)[:1].islower() and fw.group(1).isalpha()
                    and fw.group(1) not in LOWERCASE_NAMES
                    and not re.search(r"→|->|[{|]", summary) and ext != ".go"):
                add("FORMAT", first.linenos[0], summary,
                    "summary starts lowercase", "capitalize the first word")
            last_para_line = first.originals[-1].rstrip()
            if (ext in PERIOD_EXTS and len(paras) >= 1 and word_count(first.text) >= 3
                    and not re.search(r"[.!?:)`\]]$", last_para_line)):
                add("FORMAT", first.linenos[-1], last_para_line,
                    "summary has no closing period", "end the sentence with a period")

    if ext == ".go" and unit.kind == "line" and not unit.trailing and unit.next_code \
            and unit.blank_before_code == 0:
        dm = GO_DECL_RE.match(unit.next_code[1])
        if dm:
            name = dm.group(1)
            head = first.originals[0]
            if not re.match(r"^(?:(?:A|An|The)\s+)?%s\b" % re.escape(name), head) \
                    and not head.startswith("Deprecated"):
                add("MOOD", first.linenos[0], head, "Go doc comment does not start with '%s'"
                    % name, "'%s …' — name the symbol first" % name)

    return findings, mood


def apply_file_mood(moods, ext, py_mood):
    """Flag doc summaries that break the mood the rest of the file uses.

    `moods` is a list of (unit, "imperative" | "descriptive"). Third-person languages and Go
    are judged per unit in check_unit, against their own style authority.
    """
    if ext in THIRD_PERSON_EXTS or ext == ".go":
        return []
    imp = sum(1 for _, m in moods if m == "imperative")
    desc = len(moods) - imp
    if ext in (".py", ".pyi") and py_mood in ("imperative", "descriptive"):
        target = py_mood
    elif imp and desc:
        if imp == desc:
            target = "imperative" if ext in (".py", ".pyi") else "descriptive"
        else:
            target = "imperative" if imp > desc else "descriptive"
    else:
        return []
    out = []
    for unit, m in moods:
        if m == target:
            continue
        summary = next((x for x in unit.lines if x), "")
        w = _first_word(summary)
        fix = (THIRD_PERSON.get(w.lower(), w.lower()) if target == "imperative"
               else _third_person(w.lower()))
        out.append({
            "rule": "MOOD", "line": unit.start, "disposition": DISPOSITION["MOOD"],
            "excerpt": summary[:160],
            "why": "'%s' is %s; this file is %s" % (w, m, target),
            "suggest": "'%s'" % fix.capitalize(),
        })
    return out


def scan_file(path, rules, cfg):
    try:
        if os.path.getsize(path) > MAX_FILE_BYTES:
            return None, "too large"
        with open(path, "r", encoding="utf-8", errors="strict") as fh:
            text = fh.read()
    except (OSError, UnicodeDecodeError):
        return None, "unreadable"
    head = "\n".join(text.split("\n", 40)[:40])
    if GENERATED_FILE_RE.search(head):
        return None, "generated"
    if VENDORED_RE.search(text[:600]):
        return None, "vendored"
    if any(len(ln) > 500 for ln in text.split("\n")[:50]):
        return None, "minified"
    units = build_units(path, text)
    if units is None:
        return None, "unsupported"
    ext = os.path.splitext(path)[1].lower()
    src_lines = text.split("\n")
    findings, moods = [], []
    prose = non_english = flagged = 0
    for u in units:
        if u.protected:
            continue
        if sum(1 for ln in u.lines if ln and _code_like(ln) >= 2) > len(u.lines) / 2:
            continue            # commented-out code is comment-cleanup's job, not ours
        got, mood = check_unit(u, ext, cfg, src_lines)
        if mood == "non-english":
            non_english += 1
            continue
        if any(ln for ln in u.lines):
            prose += 1
        if mood in ("imperative", "descriptive"):
            moods.append((u, mood))
        kept = [f for f in got if f["rule"] in rules]
        if kept:
            flagged += 1
        findings += kept
    if "MOOD" in rules:
        extra = apply_file_mood(moods, ext, cfg["python_mood"])
        flagged_lines = {f["line"] for f in findings}
        flagged += sum(1 for f in extra if f["line"] not in flagged_lines)
        findings += extra
    findings.sort(key=lambda f: (f["line"], f["rule"]))
    return {"comments": len(units), "prose": prose, "non_english": non_english,
            "flagged": flagged, "findings": findings}, None


def changed_files(ref, root):
    """Files that differ from `ref`, including uncommitted and untracked ones."""
    names = set()
    for cmd in (["git", "-C", root, "diff", "--name-only", "--diff-filter=ACMR", ref],
                ["git", "-C", root, "ls-files", "--others", "--exclude-standard"]):
        try:
            out = subprocess.run(cmd, capture_output=True, text=True, timeout=60)
        except (OSError, subprocess.SubprocessError):
            return None
        if out.returncode != 0:
            return None
        names |= {os.path.join(root, n) for n in out.stdout.splitlines() if n}
    return names


# ---------------------------------------------------------------------------
# Reporting
# ---------------------------------------------------------------------------


def _clip(s, n):
    s = " ".join(s.split())
    return s if len(s) <= n else s[:n - 1] + "…"


def render(results, totals, stats, root, summary_only, max_per_file):
    out = []
    if not summary_only:
        for path, res in results:
            if not res["findings"]:
                continue
            out.append(os.path.relpath(path, root))
            shown = res["findings"][:max_per_file]
            for f in shown:
                tail = "  → %s" % f["suggest"] if f["suggest"] else ""
                out.append("  %5d  %-8s %-9s %s%s" % (f["line"], f["rule"], f["disposition"],
                                                      f["why"], tail))
                if f["rule"] != "SECRET":
                    out.append("  %5s  %s" % ("", _clip(f["excerpt"], 96)))
            if len(res["findings"]) > len(shown):
                out.append("  ... %d more in this file" % (len(res["findings"]) - len(shown)))
            out.append("")
    pct = (100.0 * stats["flagged"] / stats["prose"]) if stats["prose"] else 0.0
    out.append("── prose scan " + "─" * 46)
    out.append("  files scanned        %d" % stats["files"])
    out.append("  files with findings  %d" % stats["files_with_findings"])
    out.append("  comments             %d" % stats["comments"])
    out.append("  English prose        %d" % stats["prose"])
    out.append("  needing a rewrite    %d (%.0f%%)" % (stats["flagged"], pct))
    out.append("  findings             %d" % sum(totals.values()))
    if stats["non_english"]:
        out.append("  non-English (kept)   %d — never translated" % stats["non_english"])
    if stats["skipped"]:
        out.append("  skipped files        %d (%s)"
                   % (sum(stats["skipped"].values()),
                      ", ".join("%s: %d" % kv for kv in sorted(stats["skipped"].items()))))
    if totals:
        out.append("")
        for rule, n in sorted(totals.items(), key=lambda kv: (-kv[1], kv[0])):
            out.append("  %-8s %5d  %-9s %s" % (rule, n, DISPOSITION[rule], RULE_HELP[rule]))
    out.append("")
    out.append("  Candidates, not verdicts — open each file and decide.")
    out.append("  Rule IDs map to references/REWRITE_RULES.md.")
    return "\n".join(out)


# ---------------------------------------------------------------------------
# Self-test
# ---------------------------------------------------------------------------

FIXTURES = [
    ("wordy.js", "// In order to avoid a race, utilize the lock prior to the write.\nlock();\n",
     {"WORDY"}, set()),
    ("filler.ts", "// Simply call this and it will basically just work.\nrun();\n",
     {"FILLER"}, set()),
    ("hedge.py", "# I think this probably handles the retry case.\nretry()\n", {"HEDGE"}, set()),
    ("ai.js", "// This robust helper seamlessly leverages the cache to delve into results.\n"
              "cache();\n", {"AI"}, set()),
    ("ai_note.js", "// It's important to note that the queue plays a crucial role in ordering.\n"
                   "q();\n", {"AI"}, set()),
    ("emoji.js", "// Fast path 🚀\nfast();\n", {"AI"}, set()),
    ("opener.py", 'def parse(s):\n    """This function is used to parse the header."""\n'
                  "    return s\n", {"OPENER"}, set()),
    ("narrate.js", "// Here we loop over the users. Let's skip the admins.\nfor (;;) {}\n",
     {"NARRATE"}, set()),
    ("passive.js", "// The token is refreshed by the middleware before each call.\nx();\n",
     {"PASSIVE"}, set()),
    ("long.js", "// When the upstream service returns a partial page we keep the cursor, wait "
                "for the configured backoff, retry the request with the same idempotency key, "
                "and only then give up and surface the error to the caller.\nx();\n",
     {"LONG"}, set()),
    ("term.js", "// Only whitelisted hosts reach the sanity check.\nx();\n", {"TERM"}, set()),
    # A term that also names code is escalated, never silently reworded.
    ("term_code.js", "// Connect to the master node.\nconst master = connect();\n", {"TERM"},
     set()),
    ("spell.py", "# Recieve the reponse and seperate the headers.\nx = 1\n", {"SPELL"}, set()),
    ("shout.js", "// DO NOT TOUCH THIS!!!\nx();\n", {"SHOUT"}, set()),
    ("vague.js", "// Handle the stuff for some reason.\nx();\n", {"VAGUE"}, set()),
    ("neg.js", "// It is not uncommon for the socket to close early.\nx();\n", {"NEG"}, set()),
    ("time.js", "// Currently we use the new API until the migration lands soon.\nx();\n",
     {"TIME"}, set()),
    # Aligned rows are a table, not one long sentence.
    ("table.mjs", "/**\n * Priority from four factors.\n"
                  " *   frequency  1-4  how often the affected code path runs in production\n"
                  " *   exposure   1-4  share of real users who reach the affected code path\n"
                  " *   confidence 0-1  how sure we are of the diagnosis and of the fix\n */\n"
                  "export function p() {}\n", set(), {"LONG", "READ"}),
    ("mood.java", "/**\n * Return the tenant's billing owner.\n */\npublic User owner() {}\n",
     {"MOOD"}, set()),
    ("mood_mixed.py", 'def a():\n    """Return the first row."""\n\n'
                      'def b():\n    """Return the last row."""\n\n'
                      'def c():\n    """Returns the middle row."""\n', {"MOOD"}, set()),
    ("mood_go.go", "package util\n\n// Copies from src to dst.\nfunc Copy(dst, src string) {}\n",
     {"MOOD"}, set()),
    # PEP 257's imperative rule is for functions; a class docstring describes an entity.
    ("class_doc.py", 'class Resolver:\n    """Maps a specifier to a file."""\n\n'
                     'def a():\n    """Return the first row."""\n\n'
                     'def b():\n    """Return the last row."""\n', set(), {"MOOD"}),
    # Quoted words are mentions, and "just past" means immediately past.
    ("mention.py", '# Google\'s list bans "simply" and "utilize"; the offset lands just past it.\n'
                   'x = 1\n', set(), {"FILLER", "WORDY"}),
    ("format.py", 'def f():\n    """return the owner"""\n', {"FORMAT"}, set()),
    ("secret.js", "// prod key: sk_live_51H8xQ2abcdefghijkl\nconst a = 1;\n", {"SECRET"}, set()),
    # Code, identifiers, URLs, and tag names are masked — they are never judged as prose.
    ("code_span.js", "// Calls `utilizeCache()` via https://example.com/in-order-to/simply\n"
                     "x();\n", set(), {"WORDY", "FILLER"}),
    ("ident.py", "# Reads master_key from env_just_in_case.\nx = 1\n", set(), {"TERM", "FILLER"}),
    ("tags.php", "<?php\n/**\n * Loads the billing owner for a tenant.\n *\n"
                 " * @param int $simplyId The tenant ID.\n * @return User\n */\n"
                 "function f($simplyId) {}\n", set(), ALL_RULES),
    ("example.ts", "/**\n * Formats a price.\n *\n * @example\n * // Simply call it:\n"
                   " * format(1) // in order to test\n */\nexport function format() {}\n",
     set(), {"FILLER", "WORDY"}),
    # Acronyms are not shouting; markers are labels, not tone.
    ("acronym.js", "// TODO(#12): send the JSON API GET request over HTTPS.\nx();\n",
     set(), {"SHOUT"}),
    # Non-English comments are counted and left alone — never translated.
    ("spanish.js", "// Obtiene el usuario de la base de datos para la sesión actual.\nx();\n",
     set(), ALL_RULES),
    ("arabic.py", "# احصل على المستخدم من قاعدة البيانات\nx = 1\n", set(), ALL_RULES),
    # Protected content is never judged.
    ("pragma.js", "// eslint-disable-next-line no-console\nconsole.log(1);\n", set(), ALL_RULES),
    ("licence.js", "/* Copyright 2026 Example Inc. Licensed under MIT, prior to use. */\n"
                   "const a = 1;\n", set(), ALL_RULES),
    ("dead.py", "# old_total = sum(x.price for x in items)\n# if old_total > limit:\n"
                "#     notify(user)\ntotal = 1\n", set(), ALL_RULES),
    # Good comments must stay quiet.
    ("good.js", "// Upstream 502s under load; 3 retries covers the observed p99.\n"
                "const retries = 3;\n", set(), ALL_RULES),
    ("good.go", "package util\n\n// Copy copies from src to dst and reports whether it "
                "finished.\nfunc Copy(dst, src string) bool { return true }\n", set(), ALL_RULES),
    ("good.py", 'def charge(tenant_id):\n    """Charge the tenant\'s default card.\n\n'
                "    Args:\n        tenant_id: Tenant that owns the invoice.\n\n"
                '    Returns:\n        The settled charge, or None when no card exists.\n'
                '    """\n', set(), ALL_RULES),
]


def self_test():
    import tempfile
    failures = []
    cfg = {"max_words": DEFAULT_MAX_WORDS, "grade": DEFAULT_GRADE, "python_mood": "consistent"}
    with tempfile.TemporaryDirectory() as tmp:
        for name, src, expect, forbid in FIXTURES:
            path = os.path.join(tmp, name)
            with open(path, "w", encoding="utf-8") as fh:
                fh.write(src)
            res, why = scan_file(path, set(ALL_RULES), cfg)
            if res is None:
                failures.append("%s: not scanned (%s)" % (name, why))
                continue
            got = {f["rule"] for f in res["findings"]}
            missing = expect - got
            leaked = got & set(forbid)
            if missing:
                failures.append("%s: expected %s, got %s" % (name, sorted(missing), sorted(got)))
            if leaked:
                failures.append("%s: false positive %s" % (name, sorted(leaked)))
            for f in res["findings"]:
                if f["rule"] == "SECRET" and f["excerpt"] != "<redacted>":
                    failures.append("%s: SECRET finding echoed the value" % name)
            if name == "term_code.js" and any(f["rule"] == "TERM"
                                              and f["disposition"] != "ESCALATE"
                                              for f in res["findings"]):
                failures.append("term_code.js: a term that names code must ESCALATE")
            if name in ("spanish.js", "arabic.py") and res["non_english"] != 1:
                failures.append("%s: non-English comment not counted" % name)

    for f in failures:
        print("FAIL  " + f, file=sys.stderr)
    if failures:
        print("\n%d/%d fixtures failed" % (len(failures), len(FIXTURES)), file=sys.stderr)
        return 1
    print("scan-prose self-test: %d fixtures passed" % len(FIXTURES))
    return 0


# ---------------------------------------------------------------------------


def main(argv):
    ap = argparse.ArgumentParser(add_help=True, description=__doc__.split("\n")[0])
    ap.add_argument("paths", nargs="*", default=None,
                    help="files or directories to scan (default: repository root)")
    ap.add_argument("--json", action="store_true", help="emit JSON instead of a table")
    ap.add_argument("--rules", default="", help="comma-separated rule IDs to report")
    ap.add_argument("--since", metavar="REF",
                    help="only files changed since a git ref (e.g. origin/main), plus "
                         "uncommitted and untracked files")
    ap.add_argument("--max-words", type=int, default=DEFAULT_MAX_WORDS,
                    help="sentence word limit (default %d)" % DEFAULT_MAX_WORDS)
    ap.add_argument("--grade", type=int, default=DEFAULT_GRADE,
                    help="Flesch-Kincaid grade limit (default %d)" % DEFAULT_GRADE)
    ap.add_argument("--python-mood", choices=("consistent", "imperative", "descriptive"),
                    default="consistent",
                    help="docstring summary mood for Python (default: match the file)")
    ap.add_argument("--summary-only", action="store_true", help="totals only, no per-file list")
    ap.add_argument("--max-per-file", type=int, default=25, help="findings shown per file")
    ap.add_argument("--self-test", action="store_true", help="run the built-in fixtures")
    args = ap.parse_args(argv)

    if args.self_test:
        return self_test()

    rules = set(ALL_RULES)
    if args.rules:
        asked = {r.strip().upper() for r in args.rules.split(",") if r.strip()}
        unknown = asked - rules
        if unknown:
            print("unknown rule(s): %s" % ", ".join(sorted(unknown)), file=sys.stderr)
            return 0
        rules = asked
    cfg = {"max_words": args.max_words, "grade": args.grade, "python_mood": args.python_mood}

    paths = args.paths or ["."]
    root = os.getcwd()
    try:
        top = subprocess.run(["git", "rev-parse", "--show-toplevel"], capture_output=True,
                             text=True, timeout=30)
        if top.returncode == 0 and top.stdout.strip():
            root = top.stdout.strip()
    except (OSError, subprocess.SubprocessError):
        pass

    files = discover(paths, root)
    if args.since:
        changed = changed_files(args.since, root)
        if changed is None:
            print("could not diff against %r — is it a valid git ref?" % args.since,
                  file=sys.stderr)
            return 0
        files = [f for f in files if os.path.abspath(f) in changed]

    results, totals, skipped = [], {}, {}
    comments = prose = non_english = flagged = files_with = 0
    for path in files:
        res, why = scan_file(path, rules, cfg)
        if res is None:
            skipped[why] = skipped.get(why, 0) + 1
            continue
        comments += res["comments"]
        prose += res["prose"]
        non_english += res["non_english"]
        flagged += res["flagged"]
        if res["findings"]:
            files_with += 1
            for f in res["findings"]:
                totals[f["rule"]] = totals.get(f["rule"], 0) + 1
        results.append((path, res))

    stats = {"files": len(results), "files_with_findings": files_with, "comments": comments,
             "prose": prose, "flagged": flagged, "non_english": non_english,
             "skipped": skipped}

    if args.json:
        print(json.dumps({
            "version": 1,
            "root": root,
            "config": cfg,
            "stats": stats,
            "totals": totals,
            "dispositions": DISPOSITION,
            "files": [{"path": os.path.relpath(p, root), "comments": r["comments"],
                       "findings": r["findings"]}
                      for p, r in results if r["findings"]],
        }, indent=2, ensure_ascii=False))
    else:
        print(render(results, totals, stats, root, args.summary_only, args.max_per_file))
    return 0


if __name__ == "__main__":
    try:
        sys.exit(main(sys.argv[1:]))
    except KeyboardInterrupt:
        sys.exit(130)
    except BrokenPipeError:           # output piped into `head`
        sys.stderr.close()
        sys.exit(0)
